import {transact} from '../database.js';
import {createEntityId} from './contracts.js';
import {validateActivity,exportActivity,importActivity} from './definition.js';
import {readUpload} from '../images.js';
const urls=new Map();
export const activityAssets={async upload(file,{original=false}={}){let blob;if(original){if(!file||!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>10*1024*1024)throw Error('Choose a PNG, JPEG or WEBP up to 10 MB.');const bitmap=await createImageBitmap(file).catch(()=>{throw Error('Image could not be read.');});if(bitmap.width*bitmap.height>40000000){bitmap.close();throw Error('Choose a background up to 40 megapixels.');}bitmap.close();blob=file;}else({blob}=await readUpload(file));const id=createEntityId();await transact('readwrite',s=>s.put({id,blob}),'activityAssets');return {type:'asset',assetId:id};},async get(id){return (await transact('readonly',s=>s.get(id),'activityAssets'))?.blob;},async mediaURL(ref){if(ref.type==='url')return ref.url;if(!urls.has(ref.assetId)){const blob=await this.get(ref.assetId);if(!blob)throw Error('Image unavailable. Replace it.');urls.set(ref.assetId,URL.createObjectURL(blob));}return urls.get(ref.assetId);}};
addEventListener('pagehide',()=>{urls.forEach(URL.revokeObjectURL);urls.clear();});
export function activityRepository(registry){return {async list(){return transact('readonly',s=>s.getAll(),'activities');},async get(id){return transact('readonly',s=>s.get(id),'activities');},async save(data){const previous=await transact('readonly',s=>s.get(data.id),'activities');const clean=validateActivity(data,registry,{previousDeckCount:previous?.content?.type==='cardDecks'?previous.content.data.decks.length:0});await transact('readwrite',s=>s.put(clean),'activities');return clean;}};}
function refs(value,found=new Set()){if(value&&typeof value==='object'){if(value.type==='asset'&&typeof value.assetId==='string')found.add(value.assetId);Object.values(value).forEach(v=>refs(v,found));}return found;}
export async function exportBundle(activity,registry){const assets=[];for(const id of refs(activity.content.data)){const blob=await activityAssets.get(id);if(!blob)throw Error('An image is missing. Replace it before export.');const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob);});assets.push({id,data});}return JSON.stringify({format:'sunny-stacy-activity-bundle',version:1,definition:JSON.parse(exportActivity(activity,registry)),assets},null,2);}
export async function importBundle(text,registry){if(text.length>40*1024*1024)throw Error('File is too large (40 MB maximum).');let bundle;try{bundle=JSON.parse(text);}catch{throw Error('Invalid JSON.');}if(bundle.format!=='sunny-stacy-activity-bundle'||bundle.version!==1||!Array.isArray(bundle.assets))throw Error('Choose an activity export. Concept Sets are imported in My Sets.');const activity=importActivity(JSON.stringify(bundle.definition),registry);const map=new Map(),records=[];for(const asset of bundle.assets){if(typeof asset.id!=='string'||map.has(asset.id))throw Error('Invalid or duplicate asset ID.');const match=typeof asset.data==='string'&&asset.data.match(/^data:(image\/(?:png|jpeg|webp));base64,([A-Za-z0-9+/=]+)$/);if(!match||match[2].length>14*1024*1024)throw Error('Invalid image data.');const blob=new Blob([Uint8Array.from(atob(match[2]),c=>c.charCodeAt(0))],{type:match[1]});const bitmap=await createImageBitmap(blob).catch(()=>{throw Error('Damaged image.');});bitmap.close();const id=createEntityId();map.set(asset.id,id);records.push({id,blob});}for(const id of refs(activity.content.data))if(!map.has(id))throw Error('Export is missing a referenced image.');function remap(v){if(v&&typeof v==='object'){if(v.type==='asset')v.assetId=map.get(v.assetId);Object.values(v).forEach(remap);}}remap(activity.content.data);activity.id=createEntityId();activity.metadata.createdAt=activity.metadata.updatedAt=new Date().toISOString();for(const record of records)await transact('readwrite',s=>s.put(record),'activityAssets');return activityRepository(registry).save(activity);}
