import {setupThemePreview} from '../../shared/setup-preview.js';
import {mountSetupMenu} from '../../shared/setup-menu.js';
import {celebrate,clearCelebration} from './celebration.js';
import {createSettingsPreview} from '../../shared/settings-preview.js';
import {ANSWER_REVEAL_MS,concealTask,revealTask} from './task-presentation.js';
import {TicTacToe} from './engine.js';
import {marker} from './markers.js';
import {loadPreferences,savePreferences,gameURL} from './settings.js';
import {setRepository} from '../../shared/sets.js';
import {validatePlayableSet} from '../../shared/content-rules.js';
import {prepareItems,showImage} from '../../shared/images.js';
import {importSet} from '../../shared/transfer.js';
import {THEME_OPTIONS} from '../../shared/themes.js';
// Reuse the established theme renderer, sound and exact set resolution unchanged.
import {applyTheme} from '../dobble/theme-view.js';
import {playFeedback} from '../dobble/sound.js';
import {resolveSetReference} from '../dobble/resolution.js';
const $=id=>document.getElementById(id),settings=loadPreferences();let game=null,sets=[],selected=null,requested,imported,busy=false,loading=false,lastSound=-Infinity;
let setupMenu,activeSetupKey=null;
const delay=ms=>new Promise(r=>setTimeout(r,ms)),reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
const name=p=>settings[p].trim()||'Player '+p,description=p=>marker(settings.theme,p)+' '+name(p);
function sound(correct){if(settings.sound&&performance.now()-lastSound>=540){lastSound=performance.now();playFeedback(correct);}}
function persist(){savePreferences(settings);history.replaceState(null,'',gameURL(settings));}
function fail(error){$('error').textContent=error.message||String(error);$('error').hidden=false;}
function fit(){if(!game)return;const area=$('playArea'),board=$('board');const other=[...area.children].filter(el=>el!==board&&!el.hidden).reduce((sum,el)=>{const css=getComputedStyle(el);return sum+el.getBoundingClientRect().height+parseFloat(css.marginTop)+parseFloat(css.marginBottom);},0);const top=area.getBoundingClientRect().top;const height=(visualViewport?.height||innerHeight)-top-other-22;const size=Math.max(1,Math.floor(Math.min(area.clientWidth,height,900)));board.style.setProperty('--board-size',size+'px');if($('task').open)positionTask();}
function render(){if(!game)return;document.body.dataset.state=game.state;for(const p of ['X','O']){const host=document.querySelector('[data-player='+p+']');host.classList.toggle('active',game.current===p&&!['WIN','DRAW'].includes(game.state));host.querySelector('.player-marker').textContent=marker(settings.theme,p);}
 for(const [i,cell] of [...$('cells').children].entries()){const player=game.board[i];cell.disabled=game.state!=='SELECT_CELL'||player!==null;cell.dataset.player=player||'';cell.classList.toggle('pending',game.pending===i);cell.querySelector('.cell-marker').textContent=player?marker(settings.theme,player):'';cell.setAttribute('aria-label','Square '+(i+1)+(player?', '+name(player)+' ('+player+')':', empty'));}
 $('turn').textContent=game.state==='STEAL_TASK'?description(game.current)+' can steal square '+(game.pending+1)+'!':game.state==='SELECT_CELL'?description(game.current)+' — choose a square':game.state==='TASK'?description(game.current)+' — square '+(game.pending+1):'';
 if(['WIN','DRAW'].includes(game.state)){$('result').hidden=false;$('resultText').textContent=game.state==='WIN'?description(game.result.winner)+' wins!':"It's a draw!";}
 requestAnimationFrame(fit);
}
// Stable viewport positioning, independent of the pending square.
function positionTask(){const dialog=$('task');if(!dialog.open)return;const v=visualViewport;dialog.style.left=((v?.offsetLeft||0)+(v?.width||innerWidth)/2)+'px';dialog.style.top=((v?.offsetTop||0)+(v?.height||innerHeight)/2)+'px';dialog.style.maxHeight=((v?.height||innerHeight)-24)+'px';}
function task(){const attempt=game.attempt;$('taskContext').textContent=game.state==='STEAL_TASK'?description(game.current)+' can steal square '+(game.pending+1)+'!':description(game.current)+' · Square '+(game.pending+1);$('taskText').textContent=game.concept.word;$('task').dataset.concept=game.concept.id;showImage($('taskImage'),game.concept.image,'Task picture');concealTask($('task'),settings.taskMode);$('correct').onclick=()=>answer(true,attempt);$('incorrect').onclick=()=>answer(false,attempt);if(!$('task').open)$('task').showModal();positionTask();}
function lock(value){$('correct').disabled=value;$('incorrect').disabled=value;$('reveal').disabled=value||$('task').dataset.revealed==='true';}
$('reveal').onclick=()=>{if(busy||!['TASK','STEAL_TASK'].includes(game?.state)||$('task').dataset.revealed==='true')return;revealTask($('task'));$('reveal').disabled=true;};
async function choose(index){if(busy||!game?.choose(index))return;busy=true;lock(true);render();const cell=$('cells').children[index];cell.classList.add('selecting');await delay(reduced()?0:130);cell.classList.remove('selecting');task();busy=false;lock(false);$('correct').focus();}
async function answer(correct,attempt){if(busy||attempt!==game.attempt||!['TASK','STEAL_TASK'].includes(game.state))return;busy=true;lock(true);const wasRevealed=$('task').dataset.revealed==='true';revealTask($('task'));if(!wasRevealed)await delay(reduced()?0:ANSWER_REVEAL_MS);const result=game.answer(correct,attempt);if(!result){busy=false;lock(false);return;}sound(correct);render();const cell=$('cells').children[game.pending];if(result==='steal'){cell.classList.add('steal');task();await delay(560);cell.classList.remove('steal');busy=false;lock(false);$('correct').focus();return;}
 $('task').close();if(result==='placed')cell.classList.add('placed');await delay(reduced()?40:320);cell.classList.remove('placed');game.finish();render();if(game.state==='WIN'){$('board').classList.add('won');const line=game.result.line;line.forEach((index,i)=>{const c=$('cells').children[index];c.style.setProperty('--win-delay',i*100+'ms');c.classList.add('winner');});const start=line[0],end=line[2],svg=$('winLine').querySelector('line');for(const [key,value] of Object.entries({x1:(start%3)*100+50,y1:Math.floor(start/3)*100+50,x2:(end%3)*100+50,y2:Math.floor(end/3)*100+50}))svg.setAttribute(key,value);$('winLine').removeAttribute('hidden');celebrate(settings.sound);await delay(reduced()?0:450);$('result').showModal();$('again').focus();}else if(game.state==='DRAW'){$('board').classList.add('draw');$('result').showModal();$('again').focus();}else{const next=[...$('cells').children].find(c=>!c.disabled);next?.focus();}busy=false;
}
function resetPresentation(){clearCelebration();$('result').close();$('board').classList.remove('won','draw');$('winLine').setAttribute('hidden','');$('result').hidden=true;for(const c of $('cells').children)c.classList.remove('winner','placed','pending','steal');}
function summarize(){selected=sets.find(s=>s.id===$('setSelect').value);$('setSummary').textContent=selected?selected.name+' · '+selected.items.length+' concepts · This set will be used.':'';try{validatePlayableSet(setupMenu?.sessionSet(selected)||selected);$('setupError').textContent='';$('play').disabled=false;}catch(e){$('setupError').textContent=selected?'Include at least 5 valid concepts to play.':e.message;$('play').disabled=true;}setupMenu?.sync();}
function setup(){if(game)selected=sets.find(s=>s.id===settings.set)||selected;if(!selected)return;$('setSelect').value=selected.id;$('themeSelect').value=settings.theme;$('sound').checked=settings.sound;$('taskMode').value=settings.taskMode;$('steal').checked=settings.steal;setupMenu?.begin();summarize();$('setup').showModal();}
function populate(){for(const id of ['setSelect','replacement']){const host=$(id);host.replaceChildren();if(id==='replacement'){const option=new Option('Choose a set','');host.append(option);}for(const set of sets)host.append(new Option(set.name,set.id));}}
function replace(set){selected=set;requested=set.id;settings.set=set.id;persist();$('missing').hidden=true;$('welcome').hidden=false;populate();setup();}
async function launch(event){event.preventDefault();if(loading||$('play').disabled)return;loading=true;const controls=[...$('setupForm').querySelectorAll('input,select,button')];controls.forEach(el=>el.disabled=true);try{selected=await setRepository.get($('setSelect').value);const content=setupMenu.sessionSet(selected);validatePlayableSet(content);await prepareItems(content.items);const nextKey=JSON.stringify([setupMenu.contentKey(selected),$('steal').checked]),restart=!game||nextKey!==activeSetupKey;Object.assign(settings,{set:selected.id,theme:$('themeSelect').value,sound:$('sound').checked,taskMode:$('taskMode').value,steal:$('steal').checked});persist();applyTheme(settings.theme);setupMenu.commit();activeSetupKey=nextKey;if(!restart){$('setup').close();render();return;}game=new TicTacToe(content.items,Math.random,{steal:settings.steal});$('nameX').value=settings.X;$('nameO').value=settings.O;$('setName').textContent=selected.name;$('welcome').hidden=true;$('missing').hidden=true;$('error').hidden=true;$('playArea').hidden=false;resetPresentation();render();$('turn').textContent=description(game.starter)+' starts! Choose a square.';$('setup').close();$('cells').children[0].focus();fit();}catch(e){$('setupError').textContent=e.message;}finally{loading=false;controls.forEach(el=>el.disabled=false);setupMenu.sync();}}
for(let i=0;i<9;i++){const cell=document.createElement('button');cell.className='cell';cell.innerHTML='<span class="cell-number">'+(i+1)+'</span><span class="cell-marker"></span>';cell.onclick=()=>choose(i);$('cells').append(cell);}
for(const p of ['X','O'])$('name'+p).addEventListener('input',e=>{settings[p]=e.target.value;savePreferences(settings);render();});
$('again').onclick=()=>{if(busy||!game.playAgain())return;resetPresentation();render();$('turn').textContent=description(game.starter)+' starts! Choose a square.';$('cells').children[0].focus();};
$('result').addEventListener('cancel',e=>e.preventDefault());addEventListener('pagehide',clearCelebration);$('task').addEventListener('cancel',e=>e.preventDefault());$('setupForm').onsubmit=launch;$('setupCancel').onclick=()=>{if(!loading)$('setup').close();};$('setup').addEventListener('cancel',e=>{if(loading)e.preventDefault();});$('setSelect').onchange=summarize;$('setupOpen').onclick=setup;
for(const id of ['themeSelect','liveTheme'])for(const [value,label] of THEME_OPTIONS)$(id).append(new Option(label,value));
const preview=createSettingsPreview(settings,['theme','sound','taskMode'],()=>{applyTheme(settings.theme);render();});
$('settingsOpen').onclick=()=>{if(!game){setup();return;}if(busy||$('task').open)return;preview.begin();$('liveTheme').value=settings.theme;$('liveSound').checked=settings.sound;$('liveTaskMode').value=settings.taskMode;$('preferences').showModal();};
$('liveTheme').onchange=()=>preview.update({theme:$('liveTheme').value});
$('liveSound').onchange=()=>preview.update({sound:$('liveSound').checked});
$('liveTaskMode').onchange=()=>preview.update({taskMode:$('liveTaskMode').value});
$('prefCancel').onclick=()=>{preview.cancel();$('preferences').close();};$('preferences').addEventListener('cancel',()=>preview.cancel());$('preferences').addEventListener('close',()=>{if(!$('preferences').open)preview.cancel();});
$('prefForm').onsubmit=e=>{e.preventDefault();preview.update({theme:$('liveTheme').value,sound:$('liveSound').checked,taskMode:$('liveTaskMode').value});preview.commit();persist();$('preferences').close();};
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch(e){fail(Error('Fullscreen is not available in this browser.'));}};
$('copyLink').onclick=async()=>{try{await navigator.clipboard.writeText(gameURL(settings));$('turn').textContent='Game link copied. Import this set on other devices first.';}catch{fail(Error('Copy this game link: '+gameURL(settings)));}};
$('importFile').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>40*1024*1024)throw Error('Maximum JSON file size is 40 MB.');imported=await importSet(await file.text(),{requestedId:requested});sets=await setRepository.list();populate();if(imported.id===requested)replace(imported);else{$('importStatus').textContent='This file contains a different set. Use it only if you want to replace the set requested by this link.';$('useImported').hidden=false;}}catch(e){$('importStatus').textContent=e.message;}};
$('useImported').onclick=()=>{if(imported)replace(imported);};$('useReplacement').onclick=()=>{const set=sets.find(s=>s.id===$('replacement').value);if(set)replace(set);};
addEventListener('resize',fit);visualViewport?.addEventListener('resize',fit);document.addEventListener('fullscreenchange',fit);new ResizeObserver(fit).observe($('turn'));
setupMenu=mountSetupMenu({dialog:$('setup'),form:$('setupForm'),title:$('setupTitle'),setSelect:$('setSelect'),themeSelect:$('themeSelect'),sound:$('sound'),getSets:()=>sets,setSets:next=>{sets=next;},onContentChange:summarize,gameplay:[$('taskMode').closest('label'),$('steal').closest('label')],status:[$('setupError')],footer:$('setupForm').querySelector('.dialog-actions'),committedTheme:()=>settings.theme});
$('settingsOpen').onclick=()=>{if(!busy&&!$('task').open)setup();};
applyTheme(settings.theme);
try{sets=await setRepository.list();const params=new URLSearchParams(location.search);requested=params.has('set')?params.get('set'):undefined;selected=resolveSetReference(sets,requested,settings.set);populate();if(selected){settings.set=selected.id;setup();}else{$('welcome').hidden=true;$('missing').hidden=false;}if(setRepository.warnings.length)fail(Error(setRepository.warnings.join('\n')));}catch(e){fail(e);}

setupThemePreview($('setup'),$('themeSelect'),()=>settings.theme,theme=>{const saved=settings.theme;settings.theme=theme;applyTheme(theme);render();settings.theme=saved;});
