import {activityRegistry} from '../shared/activity/catalog.js';
import {editorTypes} from '../shared/editors/register.js';
import {emptyContent} from '../shared/editors/models.js';
import {mountSetupMenu} from '../shared/setup-menu.js';
import {activityRepository,activityAssets,exportBundle,importBundle} from '../shared/activity/repository.js';
import {createEntityId} from '../shared/activity/contracts.js';
import {el,action} from '../shared/editors/common.js';
import {themes} from '../shared/themes.js';
import {confirmDialog} from '../shared/ui.js';
const $=id=>document.getElementById(id),repo=activityRepository(activityRegistry),template=$('editorForm').cloneNode(true);let active,controller,dirty=false,busy=0,revision=0;
const message=e=>{$('notice').textContent=e.message||e;};
for(const [type,title] of editorTypes)$('newTypes').append(action('+ '+title,()=>openEditor(type)));
async function list(){try{const records=await repo.list();$('activities').replaceChildren();if(!records.length)$('activities').append(el('p','','No activities yet. Choose an editor above.'));for(const item of records){const row=el('section','editor-section');row.append(el('h2','',item.name),el('p','',editorTypes.find(([type])=>type===item.content?.type)?.[1]||'Unsupported activity'),action('Edit',()=>openEditor(item.content.type,item)),action('Export JSON',async()=>{try{const text=await exportBundle(item,activityRegistry),url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=el('a');a.href=url;a.download='activity.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){message(e);}}));for(const game of activityRegistry.games().filter(game=>game.runtime&&game.supportedContentTypes.includes(item.content?.type))){const link=el('a','button primary','Play '+(game.name||game.id));const url=new URL('../'+game.runtime,import.meta.url);url.searchParams.set('activity',item.id);link.href=url.href;row.append(link);}$('activities').append(row);}}catch(e){message(e);}}
function openEditor(type,saved){try{if(!emptyContent[type])throw Error('This activity editor is not available.');controller?.destroy();const form=template.cloneNode(true);$('editorForm').replaceWith(form);const now=new Date().toISOString();active=saved?structuredClone(saved):{id:createEntityId(),name:'',gameType:'authoring-'+type,schemaVersion:1,content:{type,version:1,data:emptyContent[type]()},themeConfig:{theme:'notebook',sound:true},gameplayConfig:{},metadata:{createdAt:now,updatedAt:now}};dirty=false;revision=0;const changed=()=>{dirty=true;revision++;};$('activityName').value=active.name;$('activityName').oninput=changed;$('theme').replaceChildren(...themes.map(t=>new Option(t.name,t.id)));$('theme').value=active.themeConfig.theme||'notebook';$('sound').checked=active.themeConfig.sound!==false;$('theme').onchange=$('sound').onchange=changed;$('editorTitle').textContent=editorTypes.find(([id])=>id===type)[1];
 const services={mediaURL:ref=>activityAssets.mediaURL(ref),async upload(file){busy++;$('save').disabled=true;try{return await activityAssets.upload(file);}finally{busy--;$('save').disabled=!!busy;}}};
 controller=mountSetupMenu({activity:active,dialog:$('editorDialog'),form,title:$('editorTitle'),themeSelect:$('theme'),sound:$('sound'),gameplay:[$('gameplayNote')],footer:$('editorFooter'),committedTheme:()=>active.themeConfig.theme,editorServices:services,onContentChange:changed});
 $('editorDialog').querySelector('[data-panel=content]').prepend($('nameLabel'));controller.begin();$('editorDialog').showModal();
 const close=async()=>{if(busy){$('saveError').textContent='Wait for the image upload to finish.';return;}if(dirty&&!await confirmDialog('Close without saving?','Your unsaved activity edits will be lost.','Close'))return;dirty=false;$('editorDialog').close();};$('cancel').onclick=close;$('editorDialog').oncancel=e=>{e.preventDefault();close();};
 form.onsubmit=async e=>{e.preventDefault();if(busy)return;const rev=revision;try{$('saveError').textContent='';const candidate={...active,name:$('activityName').value,content:{...active.content,data:controller.readContent()},themeConfig:{theme:$('theme').value,sound:$('sound').checked},metadata:{...active.metadata,updatedAt:new Date().toISOString()}};const saved=await repo.save(candidate);active=saved;if(rev===revision){controller.commit();dirty=false;$('saveError').textContent='Saved';}else $('saveError').textContent='Saved. More recent edits are still unsaved.';await list();}catch(error){$('saveError').textContent=error.message;}};
}catch(e){message(e);}}
$('import').onclick=()=>$('importFile').click();$('importFile').onchange=async()=>{const file=$('importFile').files[0];if(!file)return;try{if(file.size>40*1024*1024)throw Error('File is too large.');await importBundle(await file.text(),activityRegistry);message('Imported as a new activity.');await list();}catch(e){message(e);}$('importFile').value='';};
addEventListener('beforeunload',e=>{if(dirty||busy){e.preventDefault();e.returnValue='';}});list();
