import {createCompletion} from '../../shared/completion.js';
import {SpySession,prepareScene,TARGET_TRANSITION_MS} from './engine.js';
import {definition,normalizeGameplay} from './activity.js';
import {preferences,savePreferences,gameURL} from './settings.js';
import {activityRegistry} from '../../shared/activity/catalog.js';
import {activityRepository,activityAssets} from '../../shared/activity/repository.js';
import {createActivityRegistry} from '../../shared/activity/registry.js';
import {mountSetupMenu} from '../../shared/setup-menu.js';
import {themes} from '../../shared/themes.js';
import {applyTheme} from '../dobble/theme-view.js';
import {playCorrect,playWrong,stopAllAudio} from '../../shared/audio.js';
import {trackGameViewport} from '../../shared/visual-viewport.js';
const $=id=>document.getElementById(id),repo=activityRepository(activityRegistry);let settings=preferences(),scenes=[],session=null,loadedActivity=null,retryActivity=null,ratio=1,transitionTimer,pendingAdvance=false,attempt=0,busy=false,menu,choice;const effects=new Map();
const completion=createCompletion({dialog:$('complete'),sound:()=>settings.sound});
const isModalOpen=()=>!!document.querySelector('dialog[open]');
for(const id of ['theme','liveTheme'])$(id).replaceChildren(...themes.map(t=>new Option(t.name,t.id)));
function fit(){const area=$('sceneArea');if(!$('playArea').hidden&&ratio){const w=Math.max(0,Math.min(area.clientWidth,area.clientHeight*ratio));$('scene').style.width=w+'px';$('scene').style.height=w/ratio+'px';}}
trackGameViewport(fit);new ResizeObserver(fit).observe($('sceneArea'));
function persist(){savePreferences(settings);history.replaceState(null,'',gameURL(settings));}
function cancelTimers(){clearTimeout(transitionTimer);pendingAdvance=false;for(const timer of effects.values())clearTimeout(timer);effects.clear();}
function error(message){cancelTimers();session=null;document.body.dataset.state='ERROR';$('playArea').hidden=true;$('empty').hidden=true;$('errorPanel').hidden=false;$('errorText').textContent=message;}
function updateStatus(){if(!session)return;$('progress').textContent=`Target ${session.activeTargetIndex+1} of ${session.targetOrder.length}`;$('progress').hidden=!settings.showProgress;$('prompt').textContent=session.target.prompt;$('counter').textContent=`${session.found.size} / ${session.target.answers.length}`;$('targetSuccess').hidden=!session.isTransitioning;$('scene').dataset.target=session.target.id;for(const button of $('scene').querySelectorAll('.spy-object')){const found=session.objectFound(button.dataset.objectId);button.classList.toggle('found',found);button.setAttribute('aria-pressed',String(found));}document.body.dataset.state=session.sessionComplete?'COMPLETE':session.isTransitioning?'TRANSITION':'INPUT';fit();}
function feedback(button,kind){const visual=button.querySelector('.object-visual');clearTimeout(effects.get(button));visual.classList.remove('correct','wrong');void visual.offsetWidth;visual.classList.add(kind);effects.set(button,setTimeout(()=>{visual.classList.remove(kind);effects.delete(button);},340));}
function advance(){if(!session?.isTransitioning)return;if(isModalOpen()){pendingAdvance=true;return;}pendingAdvance=false;session.advance();updateStatus();if(session.sessionComplete){$('completeCount').textContent=`${session.targetOrder.length} / ${session.targetOrder.length} targets found`;completion.show();}}
function hit(id,button,event){if(!session||busy||isModalOpen())return;const rect=$('scene').getBoundingClientRect(),x=event?.detail===0&&button?undefined:(event?.clientX-rect.left)/rect.width,y=event?.detail===0&&button?undefined:(event?.clientY-rect.top)/rect.height;const result=session.hit(id,x,y);if(result.kind==='wrong'){if(button)feedback(button,'wrong');playWrong(settings.sound&&settings.wrongAnswerSound);return;}if(result.kind!=='correct')return;updateStatus();if(button&&result.answer.type==='object')feedback(button,'correct');playCorrect(settings.sound);if(result.completed){const current=session;transitionTimer=setTimeout(()=>{if(session===current)advance();},TARGET_TRANSITION_MS);}}
async function loadImage(ref){const src=await activityAssets.mediaURL(ref);return new Promise((resolve,reject)=>{const image=new Image(),timer=setTimeout(()=>{image.onload=image.onerror=null;reject(Error('Image timed out.'));},8000);image.referrerPolicy='no-referrer';image.onload=()=>{clearTimeout(timer);if(!image.naturalWidth||!image.naturalHeight)reject(Error('Invalid image.'));else resolve({src,width:image.naturalWidth,height:image.naturalHeight});};image.onerror=()=>{clearTimeout(timer);reject(Error('Image could not load.'));};image.src=src;});}
async function start(activity){completion.reset();retryActivity=activity;const token=++attempt;cancelTimers();stopAllAudio();busy=true;$('play').disabled=true;$('errorPanel').hidden=true;$('complete').close();try{if(activity?.content?.type!=='scene'||![1,2].includes(activity.content.version))throw Error('This activity is not a supported scene. Choose a Scene from My Content.');const nextRaw=structuredClone(activity.content.data),nextSession=new SpySession(nextRaw,settings);let background;try{background=await loadImage(nextSession.scene.background);}catch{throw Error('The scene background could not load. Replace it in My Content or try again.');}if(token!==attempt)return;
 const assets=new Map();for(const asset of nextSession.scene.assets)if(asset&&typeof asset.id==='string'&&!assets.has(asset.id))assets.set(asset.id,asset);const media=new Map();await Promise.all([...new Set(nextSession.scene.objects.map(o=>o.assetId))].map(async id=>{try{const asset=assets.get(id);if(!asset?.media)throw Error();media.set(id,await loadImage(asset.media));}catch{media.set(id,null);}}));if(token!==attempt)return;
 session=nextSession;loadedActivity=structuredClone(activity);ratio=background.width/background.height;const success=$('targetSuccess');$('scene').replaceChildren();$('scene').append(success);const bg=new Image();bg.id='sceneBackground';bg.alt='';bg.src=background.src;$('scene').append(bg);let failed=0;
 for(const object of session.scene.objects){const button=document.createElement('button');button.type='button';button.className='spy-object';button.dataset.objectId=object.id;button.style.left=object.x*100+'%';button.style.top=object.y*100+'%';button.style.width=object.width*100+'%';button.style.height=object.height*100+'%';const asset=assets.get(object.assetId),label=typeof asset?.name==='string'?asset.name:'Scene object';button.setAttribute('aria-label',label);const visual=document.createElement('span');visual.className='object-visual';const imageData=media.get(object.assetId);if(imageData){const img=new Image();img.alt='';img.draggable=false;img.src=imageData.src;visual.append(img);}else{failed++;const placeholder=document.createElement('span');placeholder.className='missing-image';placeholder.textContent='?';placeholder.title='Image unavailable';visual.append(placeholder);button.setAttribute('aria-label',label+' — image unavailable');}button.append(visual);button.onclick=e=>{e.stopPropagation();hit(object.id,button,e);};$('scene').append(button);}
 $('assetWarning').textContent=[failed?'Some object images could not load; their positions are marked with ?.':'',session.scene.skippedTargets?'Some incomplete targets were skipped for this game.':''].filter(Boolean).join(' ');$('assetWarning').hidden=!$('assetWarning').textContent;$('sceneName').textContent=activity.name||'Scene';$('empty').hidden=true;$('playArea').hidden=false;$('setup').close();applyTheme(settings.theme);persist();updateStatus();
 }catch(e){if(token===attempt){$('setup').close();error(e.message);}}finally{if(token===attempt){busy=false;$('play').disabled=false;}}}
function syncChoice(){const current=scenes.find(a=>a.id===choice?.value);$('play').disabled=busy;try{if(!current)throw Error(scenes.length?'Choose a saved scene.':'No scenes yet. Create one in My Content.');const prepared=prepareScene(current.content.data);$('sceneSummary').textContent=`${current.name} · ${prepared.objects.length} scene objects · ${prepared.targets.length} targets`;$('setupMessage').textContent='This scene will be used.';}catch(e){$('sceneSummary').textContent='';$('setupMessage').textContent=e.message;$('play').disabled=true;}}
const pickerRegistry=createActivityRegistry();pickerRegistry.registerContent({type:'scene',version:1,validate:()=>{},resolve:data=>data,editor:'picker'});pickerRegistry.registerGame({...definition,editors:{scene:'picker'}});pickerRegistry.registerEditor('picker',({host})=>{const label=document.createElement('label');label.textContent='Scene';choice=document.createElement('select');choice.id='sceneChoice';label.append(choice);const summary=document.createElement('p');summary.id='sceneSummary';const link=document.createElement('a');link.className='button';link.href='../../activities/';link.textContent='Create / edit scenes';host.append(label,summary,link);choice.onchange=syncChoice;return {read:()=>({activityId:choice.value}),sync:syncChoice};});
menu=mountSetupMenu({gameType:'i-spy',registry:pickerRegistry,activity:{gameType:'i-spy',content:{type:'scene',version:1,data:{}}},dialog:$('setup'),form:$('setupForm'),title:$('setupTitle'),themeSelect:$('theme'),sound:$('sound'),gameplay:[$('orderLabel'),$('wrongLabel'),$('progressLabel')],status:[$('setupMessage')],footer:$('setupForm').querySelector('.dialog-actions'),committedTheme:()=>settings.theme});
async function openSetup(){try{scenes=(await repo.list()).filter(a=>a?.content?.type==='scene'&&[1,2].includes(a.content.version));choice.replaceChildren(new Option('Choose a scene',''),...scenes.map(a=>new Option(a.name||'Untitled scene',a.id)));const explicit=new URLSearchParams(location.search).has('activity');choice.value=scenes.some(a=>a.id===settings.activity)?settings.activity:explicit?'':scenes[0]?.id||'';$('theme').value=settings.theme;$('sound').checked=settings.sound;$('order').value=settings.targetOrder;$('wrongSound').checked=settings.wrongAnswerSound;$('showProgress').checked=settings.showProgress;menu.begin();syncChoice();if(explicit&&!scenes.some(a=>a.id===settings.activity))$('setupMessage').textContent='The requested scene is unavailable on this device. Import it in My Content or choose another scene.';$('setup').showModal();}catch(e){error(e.message);}}
$('setupForm').onsubmit=async e=>{e.preventDefault();if(busy||$('play').disabled)return;const activityId=choice.value;busy=true;document.getElementById("play").disabled=true;settings={...settings,...normalizeGameplay({targetOrder:$('order').value,wrongAnswerSound:$('wrongSound').checked,showProgress:$('showProgress').checked}),theme:$('theme').value,sound:$('sound').checked,activity:activityId};menu.commit();try{const activity=await repo.get(activityId);if(!activity)throw Error('This scene is no longer available.');await start(activity);}catch(errorMessage){$('setup').close();error(errorMessage.message);}finally{busy=false;syncChoice();}};
$('cancelSetup').onclick=()=>$('setup').close();$('setup').addEventListener('close',()=>{if(pendingAdvance&&!isModalOpen())advance();});
$('scene').onclick=e=>hit(null,null,e);
$('chooseScene').onclick=$('chooseStart').onclick=openSetup;
$('settingsOpen').onclick=()=>{if(!session){openSetup();return;}$('liveOrder').value=settings.targetOrder;$('liveWrongSound').checked=settings.wrongAnswerSound;$('liveProgress').checked=settings.showProgress;$('liveTheme').value=settings.theme;$('liveSound').checked=settings.sound;$('preferences').showModal();};
$('preferencesForm').onsubmit=async e=>{e.preventDefault();const previous=settings.targetOrder;settings={...settings,...normalizeGameplay({targetOrder:$('liveOrder').value,wrongAnswerSound:$('liveWrongSound').checked,showProgress:$('liveProgress').checked}),theme:$('liveTheme').value,sound:$('liveSound').checked};persist();applyTheme(settings.theme);if(!settings.sound)stopAllAudio();if(previous!==settings.targetOrder){cancelTimers();$('preferences').close();await start(loadedActivity);}else{$('preferences').close();updateStatus();}};
$('cancelPreferences').onclick=()=>$('preferences').close();$('preferences').addEventListener('close',()=>{if(pendingAdvance&&!isModalOpen())advance();});
$('again').onclick=()=>{if(busy||!loadedActivity)return;$('complete').close();start(loadedActivity);};$('retry').onclick=()=>{if(retryActivity)start(retryActivity);else openSetup();};
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{}};
$('copyLink').onclick=async()=>{try{await navigator.clipboard.writeText(gameURL(settings));$('copyLink').textContent='Link copied';setTimeout(()=>$('copyLink').textContent='Copy Game Link',1200);}catch{$('copyLink').textContent='Copy the address from your browser';}};
addEventListener('pagehide',()=>{attempt++;cancelTimers();stopAllAudio();completion.destroy();menu.destroy();});applyTheme(settings.theme);openSetup();



 document.getElementById('complete').addEventListener('cancel',e=>e.preventDefault());

