import {mountPawnPicker} from './pawn-picker.js';
import {pawnGraphic} from './pawn.js';
import {createDie} from './dice.js';
import {BoardRace,EFFECT_LABELS} from './engine.js';
import {windingBoard} from './geometry.js';
import {PAWN_COLORS,normalizeGameplay,pawnColor} from './activity.js';
import {conceptEvents} from './content.js';
import {preferences,savePreferences,gameURL} from './settings.js';
import {setRepository} from '../../shared/sets.js';
import {validatePlayableSet} from '../../shared/content-rules.js';
import {renderConcept} from './content-view.js';
import {ANSWER_REVEAL_MS,revealTask} from '../../shared/concept-blur.js';
import {mountSetupMenu} from '../../shared/setup-menu.js';
import {themes} from '../../shared/themes.js';
import {applyTheme} from '../dobble/theme-view.js';
import {createCompletion} from '../../shared/completion.js';
import {playCorrect,stopAllAudio} from '../../shared/audio.js';
import {trackGameViewport} from '../../shared/visual-viewport.js';
const $=id=>document.getElementById(id),el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;},pause=ms=>new Promise(r=>setTimeout(r,ms));
let settings=preferences(),sets=[],game,events,activeSet,activeKey,menu,geometry,epoch=0,loading=false,setupNames=[],draft=null,intro=false;
const completion=createCompletion({dialog:$('complete'),sound:()=>settings.sound}),symbols={forward:'+2',back:'−2',again:'↻',skip:'Ⅱ'};
for(const theme of themes)$('themeSelect').append(new Option(theme.name,theme.id));
const title=i=>settings.names[i]||'Player '+(i+1),color=i=>pawnColor(settings.colors[i])||PAWN_COLORS[i].hex,die=createDie($('die'));
function gameplayKey(value){const {style,taskMode,...rules}=normalizeGameplay(value);return rules;}
function persist(){savePreferences(settings);history.replaceState(null,'',gameURL(settings));}
function playerForms(){ $('playerSetup').replaceChildren();setupNames.forEach((value,i)=>{const row=el('div');row.className='player-form';const label=el('label'),input=el('input');label.append(el('span','Player / Team '+(i+1)));input.value=value;input.maxLength=40;input.id='name'+i;input.oninput=()=>setupNames[i]=input.value;label.append(input);row.append(label);if(setupNames.length>2){const remove=el('button','×');remove.type='button';remove.className='remove-player';remove.setAttribute('aria-label','Remove player '+(i+1));remove.onclick=()=>{setupNames.splice(i,1);playerForms();};row.append(remove);}$('playerSetup').append(row);});$('addPlayer').disabled=setupNames.length>=4;}
function summary(){const selected=sets.find(s=>s.id===$('setSelect').value);$('setupError').textContent='';try{validatePlayableSet(menu?.sessionSet(selected)||selected);$('play').disabled=loading;}catch(e){$('setupError').textContent=e.message;$('play').disabled=true;}}
function openSetup(){if(intro||game&&game.phase!=='READY'&&game.phase!=='COMPLETE')return;$('setSelect').value=settings.set;$('themeSelect').value=settings.theme;$('sound').checked=settings.sound;$('mode').value=settings.mode;$('size').value=settings.size;$('sizeValue').textContent=settings.size;$('style').value=settings.style;$('taskMode').value=settings.taskMode;$('special').checked=settings.special;setupNames=settings.names.slice(0,settings.players);playerForms();menu.begin();menu.sync();summary();$('setup').showModal();}
function readSettings(){return {...settings,...normalizeGameplay({taskMode:$('taskMode').value,mode:$('mode').value,size:$('size').value,style:$('style').value,special:$('special').checked,players:setupNames.length}),set:$('setSelect').value,theme:$('themeSelect').value,sound:$('sound').checked,names:Array.from({length:4},(_,i)=>setupNames[i]?.trim()||settings.names[i]||'Team '+(i+1)),colors:[...settings.colors]};}
function pawnChoices(){mountPawnPicker($('pawnChoices'),draft.settings);}
function fit(){if(!game||$('playArea').hidden)return;const area=$('boardArea');if(area.clientWidth<40||area.clientHeight<40)return;geometry=windingBoard({...game.options,width:area.clientWidth,height:area.clientHeight});$('board').dataset.style=settings.style;$('board').style.setProperty('--tile-size',geometry.diameter+'px');$('board').style.setProperty('--piece-size',Math.max(15,Math.min(46,geometry.diameter*.55))+'px');$('board').dataset.layout=geometry.layout;$('path').setAttribute('viewBox',`0 0 ${geometry.width} ${geometry.height}`);$('path').replaceChildren();const line=document.createElementNS('http://www.w3.org/2000/svg','polyline');line.setAttribute('points',[...geometry.curve,...(geometry.closed?[geometry.curve[0]]:[])].map(p=>p.x+','+p.y).join(' '));if(settings.style==='circles')$('path').append(line);
 if(settings.style==='tiles'){geometry.segments.forEach((segment,i)=>{const index=i-(geometry.closed?0:1),path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',segment.path);path.setAttribute('class','track-segment'+(index===-1?' start':game.options.mode==='race'&&index===game.options.size-1?' finish':game.revealed.has(index)&&game.specials[index]?' special':''));path.dataset.index=index;$('path').append(path);});} const ordered=[];for(let i=0;i<ordered.length-(geometry.closed?0:1);i++){const a=ordered[i],b=ordered[(i+1)%ordered.length],dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy),x=(a.x+b.x)/2,y=(a.y+b.y)/2;if(len<geometry.diameter*1.15)continue;const arrow=document.createElementNS('http://www.w3.org/2000/svg','polyline');arrow.setAttribute('class','direction');const ux=dx/len,uy=dy/len;arrow.setAttribute('points',`${x-ux*3-uy*3},${y-uy*3+ux*3} ${x+ux*3},${y+uy*3} ${x-ux*3+uy*3},${y-uy*3-ux*3}`);$('path').append(arrow);}
 $('tiles').replaceChildren();function tile(p,index){const node=el('div');node.className='race-tile';node.dataset.index=index;node.style.left=p.x+'px';node.style.top=p.y+'px';if(index===-1){node.classList.add('start');node.append(el('small','START'));}else{node.append(el('span',index+1));if(game.options.mode==='race'&&index===game.options.size-1){node.classList.add('finish');node.append(el('small','FINISH'));}else if(game.revealed.has(index)&&game.specials[index]){node.classList.add('special');node.append(el('small',symbols[game.specials[index]]));node.title=EFFECT_LABELS[game.specials[index]];}}$('tiles').append(node);}if(geometry.start)tile(geometry.start,-1);geometry.tiles.forEach(tile);positionPieces();}
function positionPieces(){if(!geometry||!game)return;for(const p of game.players){let node=$('pieces').children[p.id];if(!node){node=el('span');node.className='race-piece';node.style.setProperty('--piece-color',color(p.id));node.dataset.player=p.id;$('pieces').append(node);}node.replaceChildren(pawnGraphic(color(p.id)));const point=p.position<0?geometry.start:geometry.tiles[p.position];const crowded=game.players.filter(x=>x.position===p.position),index=crowded.indexOf(p),offset=(index-(crowded.length-1)/2)*geometry.diameter*.18;node.style.setProperty('--piece-size',geometry.diameter*.78+'px');node.style.left=(point.x+offset)+'px';node.style.top=(point.y+geometry.diameter*.08+Math.abs(offset)*.15)+'px';node.classList.toggle('active',p.id===game.current);node.setAttribute('aria-label',`${title(p.id)}, ${p.position<0?'Start':'tile '+(p.position+1)}`);}}
function render(){if(!game)return;document.body.dataset.state=game.phase;$('roll').disabled=game.phase!=='READY'||intro;$('roll').setAttribute('aria-label',game.phase==='READY'?'Roll dice':'Rolled '+game.roll);$('endNow').disabled=game.phase!=='READY'||intro;$('endNow').hidden=game.options.mode!=='endless';$('settingsOpen').disabled=!['READY','COMPLETE'].includes(game.phase)||intro;$('players').replaceChildren();for(const p of game.players){const card=el('div');card.className='player-status'+(p.id===game.current?' active':'');card.dataset.player=p.id;const avatar=el('span');avatar.append(pawnGraphic(color(p.id)));avatar.className='avatar';const text=el('span');text.append(el('strong',title(p.id)),el('small',game.options.mode==='endless'?`Lap ${p.lap} · ${p.totalSpacesMoved} spaces`:(p.position<0?'Start':`Tile ${p.position+1}`)));if(p.skip)text.append(el('small',' · skips next turn'));card.append(avatar,text);$('players').append(card);}$('turn').textContent=intro?title(game.current)+' goes first!':game.phase==='ROLLING'?title(game.current)+' is rolling…':game.phase==='READY'?`${game.skipped?.length?game.skipped.map(title).join(', ')+' skipped. ':''}${title(game.current)} — roll the dice!`:game.phase==='MOVING'?`${title(game.current)} rolled ${game.roll}!`:game.phase==='SPECIAL'?EFFECT_LABELS[game.effect]:game.phase==='COMPLETE'?'Well played!':`${title(game.current)} — your challenge`;positionPieces();}
function complete(){render();$('completeTitle').textContent=game.winners.length>1?"It's a tie!":title(game.winners[0])+' wins!';$('results').replaceChildren(...[...game.players].sort((a,b)=>b.totalSpacesMoved-a.totalSpacesMoved).map(p=>el('p',`${title(p.id)} — ${p.totalSpacesMoved} spaces${game.options.mode==='endless'?' · Lap '+p.lap:''}`)));completion.show();}
async function resolve(token){while(token===epoch){if(game.phase==='MOVING'){game.step();render();await pause(280);continue;}if(game.phase==='COMPLETE'){complete();return;}if(game.phase==='SPECIAL'){$('effectIcon').textContent=symbols[game.effect];$('effectText').textContent=EFFECT_LABELS[game.effect];fit();$('specialOverlay').showModal();render();return;}if(game.phase==='CONTENT'){const event=events.next();if(event?.type==='concept'){$('taskPlayer').textContent=title(game.current)+' · Tile '+(game.player.position+1);renderConcept($('task'),event.concept,settings.taskMode);$('taskDone').disabled=false;$('task').showModal();}else throw Error('Unsupported landing event.');render();return;}return;}}
async function roll(){if(intro||!game||game.phase!=='READY'||document.querySelector('dialog[open]'))return;const token=epoch;if(!game.beginRoll())return;render();const settled=await die.roll(game.roll,settings.sound);if(!settled||token!==epoch)return;game.settleRoll();render();await resolve(token);}
function start(){epoch++;die.reset();completion.reset();stopAllAudio();for(const id of ['complete','task','specialOverlay','endConfirm'])$(id).close();geometry=null;game=new BoardRace(settings,()=>Math.random());events=conceptEvents(activeSet.items);$('pieces').replaceChildren();$('welcome').hidden=true;$('error').hidden=true;$('playArea').hidden=false;$('context').textContent=activeSet.name+' · '+(settings.mode==='race'?'Race':'Endless Fun');intro=true;render();fit();const token=epoch;setTimeout(()=>{if(token!==epoch)return;intro=false;render();},1000);}
menu=mountSetupMenu({gameType:'board-race',dialog:$('setup'),form:$('setupForm'),title:$('setupTitle'),setSelect:$('setSelect'),themeSelect:$('themeSelect'),sound:$('sound'),getSets:()=>sets,setSets:next=>sets=next,onContentChange:summary,visuals:[$('styleLabel')],gameplay:['modeLabel','sizeLabel','displayLabel','specialLabel','playersLabel'].map($),status:[$('setupError')],footer:$('setupForm').querySelector('.dialog-actions'),committedTheme:()=>settings.theme});
$('addPlayer').onclick=()=>{if(setupNames.length<4){setupNames.push('Team '+(setupNames.length+1));playerForms();$('name'+(setupNames.length-1)).focus();}};$('size').oninput=()=>$('sizeValue').textContent=$('size').value;$('setSelect').onchange=summary;
$('setupForm').onsubmit=async e=>{e.preventDefault();if(loading||$('play').disabled)return;loading=true;$('play').disabled=true;try{const content=menu.sessionSet(await setRepository.get($('setSelect').value));validatePlayableSet(content);const next=readSettings(),key=JSON.stringify([menu.contentKey(content),gameplayKey(next),next.names]);const restart=!game||key!==activeKey||game.phase==='COMPLETE';menu.commit();$('setup').close();if(!restart){settings=next;persist();applyTheme(settings.theme);if(!settings.sound)stopAllAudio();fit();render();return;}draft={settings:next,content,key};pawnChoices();$('pawns').showModal();}catch(error){$('setupError').textContent=error.message;}finally{loading=false;summary();}};
$('backPawns').onclick=()=>{$('pawns').close();$('setup').showModal();};$('pawns').addEventListener('cancel',e=>{e.preventDefault();$('backPawns').click();});$('startGame').onclick=()=>{if(!draft)return;settings=draft.settings;activeSet=draft.content;activeKey=draft.key;draft=null;persist();applyTheme(settings.theme);$('pawns').close();start();};
$('ackEffect').onclick=()=>{if(game?.phase!=='SPECIAL')return;$('specialOverlay').close();game.resolveSpecial();render();resolve(epoch).catch(error=>{$('error').textContent=error.message;$('error').hidden=false;});};
$('reveal').onclick=()=>{if(game?.phase!=='CONTENT'||$('task').dataset.revealed==='true')return;revealTask($('task'));$('reveal').disabled=true;};
$('taskDone').onclick=async()=>{if(game?.phase!=='CONTENT'||$('taskDone').disabled)return;$('taskDone').disabled=true;const token=epoch,wasRevealed=$('task').dataset.revealed==='true';revealTask($('task'));$('reveal').disabled=true;if(!wasRevealed&&!matchMedia('(prefers-reduced-motion: reduce)').matches)await pause(ANSWER_REVEAL_MS);if(token!==epoch)return;playCorrect(settings.sound);$('task').close();game.finishContent();render();};
for(const id of ['specialOverlay','task','complete'])$(id).addEventListener('cancel',e=>e.preventDefault());
$('roll').onclick=()=>roll().catch(error=>{$('error').textContent=error.message;$('error').hidden=false;});$('settingsOpen').onclick=$('chooseStart').onclick=openSetup;$('cancelSetup').onclick=()=>$('setup').close();$('endNow').onclick=()=>{if(game?.phase==='READY')$('endConfirm').showModal();};$('cancelEnd').onclick=()=>$('endConfirm').close();$('confirmEnd').onclick=()=>{if(!game||game.options.mode!=='endless')return;epoch++;$('endConfirm').close();game.endNow();complete();};$('again').onclick=start;
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{}};$('copyLink').onclick=async()=>{try{await navigator.clipboard.writeText(gameURL(settings));$('turn').textContent='Link copied. Import the set on other devices first.';}catch{$('turn').textContent='Copy the game address from your browser.';}};
trackGameViewport(fit);new ResizeObserver(fit).observe($('boardArea'));addEventListener('pagehide',()=>{epoch++;die.destroy();completion.destroy();stopAllAudio();});applyTheme(settings.theme);
try{sets=await setRepository.list();$('setSelect').replaceChildren(...sets.map(set=>new Option(set.name,set.id)));if(!sets.some(s=>s.id===settings.set)&&!new URLSearchParams(location.search).has('set'))settings.set=sets[0]?.id||'';openSetup();}catch(error){$('error').hidden=false;$('error').textContent=error.message;}

