import {BoostRace} from './boost-engine.js';
import {presentBoost} from './boost-view.js';
import {mountBoostOptions,BOOSTS} from './boosts.js';
import {activityAssets} from '../../shared/activity/repository.js';
import {cardsBoard} from './adaptive-geometry.js';
import {DeckSession,assignDeckSpaces,similarColors} from './decks.js';
import {mountDeckSelection} from './deck-selection.js';
import {createDeckView} from './deck-view.js';
import {contrastInk} from './track-palette.js';
import {spacePaint} from './track-palette.js';
import {mountPawnPicker} from './pawn-picker.js';
import {pawnGraphic} from './pawn.js';
import {createDie} from './dice.js';
import {BoardRace,EFFECT_LABELS} from './engine.js';
import {windingBoard,chooseRoute} from './geometry.js';
import {PAWN_COLORS,normalizeGameplay,pawnColor} from './activity.js';
import {conceptEvents} from './content.js';
import {preferences,savePreferences,gameURL} from './settings.js';
import {setRepository} from '../../shared/sets.js';
import {validatePlayableSet} from '../../shared/content-rules.js';
import {renderConcept} from './content-view.js';
import {ANSWER_REVEAL_MS,revealTask} from '../../shared/concept-blur.js';
import {mountSetupMenu} from '../../shared/setup-menu.js';
import {themes} from '../../shared/themes.js';
import {applyTheme} from '../dobble/theme-view.js';
import {createCompletion} from '../../shared/completion.js';
import {playCorrect,stopAllAudio} from '../../shared/audio.js';
import {trackGameViewport} from '../../shared/visual-viewport.js';
const $=id=>document.getElementById(id),el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;},pause=ms=>new Promise(r=>setTimeout(r,ms));
let settings=preferences(),sets=[],game,events,activeSet,activeKey,menu,geometry,epoch=0,loading=false,setupNames=[],draft=null,intro=false,routeLayout='winding',geometryKey='',deckSession=null,deckSpaces=[],boostPaints=[],effectAnimating=false;
const completion=createCompletion({dialog:$('complete'),sound:()=>settings.sound}),symbols={forward:'+2',back:'−2',again:'↻',skip:'Ⅱ',switch:'⇄',shield:'🛡',pass:'↗',lucky:'⚄',team:'♧',steal:'↶',shuffle:'⤨',reverse:'←'};
for(const theme of themes)$('themeSelect').append(new Option(theme.name,theme.id));
const title=i=>settings.names[i]||'Player '+(i+1),color=i=>pawnColor(settings.colors[i])||PAWN_COLORS[i].hex,die=createDie($('die'));
function gameplayKey(value){const {style,taskMode,...rules}=normalizeGameplay(value);return rules;}
function persist(){savePreferences(settings);history.replaceState(null,'',gameURL(settings));}
function playerForms(){ $('playerSetup').replaceChildren();setupNames.forEach((value,i)=>{const row=el('div');row.className='player-form';const label=el('label'),input=el('input');label.append(el('span','Player / Team '+(i+1)));input.value=value;input.maxLength=40;input.id='name'+i;input.oninput=()=>setupNames[i]=input.value;label.append(input);row.append(label);if(setupNames.length>2){const remove=el('button','×');remove.type='button';remove.className='remove-player';remove.setAttribute('aria-label','Remove player '+(i+1));remove.onclick=()=>{setupNames.splice(i,1);playerForms();};row.append(remove);}$('playerSetup').append(row);});$('addPlayer').disabled=setupNames.length>=4;}
function summary(){const selected=sets.find(s=>s.id===$('setSelect').value);$('setupError').textContent='';try{if(deckSelection?.mode==='decks'){const decks=deckSelection.read();if($('special').checked&&boostOptions.read().length&&!availableBoostPaints(decks,$('themeSelect').value).length)throw Error('No distinct boost colors available. Change deck colors or turn Special tiles off.');}else validatePlayableSet(menu?.sessionSet(selected)||selected);$('play').disabled=loading;}catch(e){$('setupError').textContent=e.message;$('play').disabled=true;}}
async function openSetup(){if(intro||game&&game.phase!=='READY'&&game.phase!=='COMPLETE')return;$('setSelect').value=settings.set;$('themeSelect').value=settings.theme;$('sound').checked=settings.sound;$('mode').value=settings.mode;$('size').value=settings.size;$('sizeValue').textContent=settings.size;$('style').value=settings.style;$('taskMode').value=settings.taskMode;$('special').checked=settings.special;setupNames=settings.names.slice(0,settings.players);playerForms();boostOptions.begin(settings.boosts);menu.begin();await deckSelection.begin(settings);menu.sync();summary();$('setup').showModal();}
function readSettings(){return {...settings,boosts:boostOptions.read(),contentMode:deckSelection.mode,deckRefs:deckSelection.refs(),...normalizeGameplay({taskMode:$('taskMode').value,mode:$('mode').value,size:$('size').value,style:$('style').value,special:$('special').checked,players:setupNames.length}),set:$('setSelect').value,theme:$('themeSelect').value,sound:$('sound').checked,names:Array.from({length:4},(_,i)=>setupNames[i]?.trim()||settings.names[i]||'Player '+(i+1)),colors:[...settings.colors]};}
function pawnChoices(){mountPawnPicker($('pawnChoices'),draft.settings);}
function paintSpace(node,index){let paint=spacePaint(settings.theme,index,game.options.size,game.options.mode==='race'&&index===game.options.size);if(deckSession&&index>=0&&index<game.options.size){const assigned=deckSpaces[index];const fill=assigned.type==='deck'?deckSession.decks.find(d=>d.key===assigned.deckKey).deck.color:boostPaints[index%boostPaints.length];paint={fill,ink:contrastInk(fill)};}node.style.setProperty('--space-fill',paint.fill);node.style.setProperty('--space-ink',paint.ink);}
function fit(){if(!game||$('playArea').hidden)return;const area=$('boardArea');if(area.clientWidth<40||area.clientHeight<40)return;const key=[settings.contentMode,game.options.size,game.options.mode,routeLayout,area.clientWidth,area.clientHeight].join(':');if(!geometry||geometryKey!==key){try{geometry=(deckSession?cardsBoard:windingBoard)({...game.options,layout:routeLayout,width:area.clientWidth,height:area.clientHeight});geometryKey=key;$('board').hidden=false;$('roll').disabled=game.phase!=='READY'||intro;$('error').hidden=true;}catch(error){$('error').textContent=error.message;$('error').hidden=false;$('board').hidden=true;$('roll').disabled=true;return;}}$('board').dataset.style=settings.style;$('board').style.setProperty('--number-size',Math.max(11,Math.min(25,(settings.style==='circles'?geometry.diameter:geometry.trackWidth)*.52))+'px');$('board').style.setProperty('--tile-size',geometry.diameter+'px');$('board').style.setProperty('--piece-size',Math.max(15,Math.min(46,geometry.diameter*.55))+'px');$('board').dataset.layout=geometry.layout;$('path').setAttribute('viewBox',`0 0 ${geometry.width} ${geometry.height}`);$('path').replaceChildren();const line=document.createElementNS('http://www.w3.org/2000/svg','polyline');line.setAttribute('points',[...geometry.connector,...(geometry.closed?[geometry.connector[0]]:[])].map(p=>p.x+','+p.y).join(' '));if(settings.style==='circles')$('path').append(line);
 if(settings.style==='tiles'){geometry.segments.forEach((segment,i)=>{const index=i-(geometry.closed?0:1),path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',segment.path);path.setAttribute('class','track-segment'+(index===-1?' start':game.options.mode==='race'&&index===game.options.size?' finish':game.revealed.has(index)&&game.specials[index]?' special':''));path.dataset.index=index;paintSpace(path,index);$('path').append(path);});} const ordered=[];for(let i=0;i<ordered.length-(geometry.closed?0:1);i++){const a=ordered[i],b=ordered[(i+1)%ordered.length],dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy),x=(a.x+b.x)/2,y=(a.y+b.y)/2;if(len<geometry.diameter*1.15)continue;const arrow=document.createElementNS('http://www.w3.org/2000/svg','polyline');arrow.setAttribute('class','direction');const ux=dx/len,uy=dy/len;arrow.setAttribute('points',`${x-ux*3-uy*3},${y-uy*3+ux*3} ${x+ux*3},${y+uy*3} ${x-ux*3+uy*3},${y-uy*3-ux*3}`);$('path').append(arrow);}
 $('tiles').replaceChildren();function tile(p,index){const node=el('div');node.className='race-tile';node.dataset.index=index;paintSpace(node,index);node.style.left=p.x+'px';node.style.top=p.y+'px';if(index===-1){node.classList.add('start');node.append(el('small','START'));}else{if(index<game.options.size)node.append(el('span',index+1));if(game.options.mode==='race'&&index===game.options.size){node.classList.add('finish');node.append(el('small','FINISH'));}else if(game.revealed.has(index)&&game.specials[index]){node.classList.add('special');node.append(el('small',symbols[game.specials[index]]));node.title=BOOSTS.find(b=>b.id===game.specials[index])?.name||game.specials[index];}}$('tiles').append(node);}if(geometry.start)tile(geometry.start,-1);geometry.tiles.forEach(tile);if(geometry.finish)tile(geometry.finish,game.options.size);positionPieces();if(deckSession)deckView.render(deckSession.decks,geometry.center,deckSession.required);}
function positionPieces(){if(!geometry||!game)return;for(const p of game.players){let node=$('pieces').children[p.id];if(!node){node=el('span');node.className='race-piece';node.style.setProperty('--piece-color',color(p.id));node.dataset.player=p.id;$('pieces').append(node);}node.replaceChildren(pawnGraphic(color(p.id)));const point=p.position<0?geometry.start:p.position===game.options.size?geometry.finish:geometry.tiles[p.position];const crowded=game.players.filter(x=>x.position===p.position),index=crowded.indexOf(p),offset=(index-(crowded.length-1)/2)*geometry.diameter*.18;node.style.setProperty('--piece-size',geometry.diameter*.78+'px');node.style.left=(point.x+offset)+'px';node.style.top=(point.y-geometry.diameter*.10)+'px';node.classList.toggle('active',p.id===game.current);node.setAttribute('aria-label',`${title(p.id)}, ${p.position<0?'Start':p.position===game.options.size?'Finish':'tile '+(p.position+1)}`);}}
function render(){if(!game)return;document.body.dataset.state=game.phase;$('roll').disabled=effectAnimating||$('board').hidden||game.phase!=='READY'||intro;$('roll').setAttribute('aria-label',game.phase==='READY'?'Roll dice':'Rolled '+game.roll);$('endNow').disabled=effectAnimating||game.phase!=='READY'||intro;$('endNow').hidden=game.options.mode!=='endless';$('settingsOpen').disabled=effectAnimating||!['READY','COMPLETE'].includes(game.phase)||intro;$('players').replaceChildren();for(const p of game.players){const card=el('div');card.className='player-status'+(p.id===game.current?' active':'');card.dataset.player=p.id;const avatar=el('span');avatar.append(pawnGraphic(color(p.id)));avatar.className='avatar';const text=el('span');text.append(el('strong',(p.ability==='shield'?'🛡 ':p.ability==='pass'?'↗ ':'')+title(p.id)),el('small',game.options.mode==='endless'?`Lap ${p.lap} · ${p.totalSpacesMoved} spaces`:(p.position<0?'Start':p.position===game.options.size?'Finish':`Tile ${p.position+1}`)));if(p.skip)text.append(el('small',' · skips next turn'));card.append(avatar,text);$('players').append(card);}$('turn').textContent=intro?title(game.current)+' goes first!':game.phase==='ROLLING'?title(game.current)+' is rolling…':game.phase==='READY'?`${game.skipped?.length?game.skipped.map(title).join(', ')+' skipped. ':''}${title(game.current)} — roll the dice!`:game.phase==='MOVING'?`${title(game.current)} rolled ${game.roll}!`:game.phase==='SPECIAL'?(BOOSTS.find(b=>b.id===game.effect)?.name||EFFECT_LABELS[game.effect]):game.phase==='COMPLETE'?'Well played!':deckSession?`${title(game.current)} — choose your deck`:`${title(game.current)} — your challenge`;positionPieces();}
function complete(){render();$('completeTitle').textContent=game.winners.length>1?"It's a tie!":title(game.winners[0])+' wins!';$('results').replaceChildren(...[...game.players].sort((a,b)=>b.totalSpacesMoved-a.totalSpacesMoved).map(p=>el('p',`${title(p.id)} — ${p.totalSpacesMoved} spaces${game.options.mode==='endless'?' · Lap '+p.lap:''}`)));completion.show();}
async function resolve(token){while(token===epoch){if(game.phase==='MOVING'){game.step();render();await pause(560);continue;}if(game.phase==='LUCKY_ROLL'){const a=1+Math.floor(Math.random()*6),b=1+Math.floor(Math.random()*6);$('turn').textContent=title(game.current)+' — Lucky Roll';await die.roll(a,settings.sound);if(token!==epoch)return;await pause(350);await die.roll(b,settings.sound);if(token!==epoch)return;game.applyLucky(a,b);render();continue;}if(game.phase==='COMPLETE'){complete();return;}if(game.phase==='SPECIAL'){presentBoost({game,dialog:$('specialOverlay'),heading:$('effectText'),icon:$('effectIcon'),ack:$('ackEffect'),title,onResolve:resolveBoost});fit();$('specialOverlay').showModal();render();return;}if(game.phase==='CONTENT'){if(deckSession){const space=deckSpaces[game.player.position];if(space?.type==='deck'){deckSession.wait(space.deckKey);fit();$('turn').textContent=title(game.current)+' — choose your deck';render();return;}game.finishContent();render();continue;}const event=events.next();if(event?.type==='concept'){$('taskPlayer').textContent=title(game.current)+' · Tile '+(game.player.position+1);renderConcept($('task'),event.concept,settings.taskMode);$('taskDone').disabled=false;$('task').showModal();}else throw Error('Unsupported landing event.');render();return;}return;}}
async function roll(){if(effectAnimating||$('board').hidden||intro||!game||game.phase!=='READY'||document.querySelector('dialog[open]'))return;const token=epoch;if(!game.beginRoll())return;render();const settled=await die.roll(game.roll,settings.sound);if(!settled||token!==epoch)return;game.settleRoll();render();await resolve(token);}
function start(){epoch++;effectAnimating=false;deckView.cancel();deckSession?.cancel();die.reset();completion.reset();stopAllAudio();for(const id of ['complete','task','specialOverlay','endConfirm'])$(id).close();geometry=null;game=new BoostRace(settings,()=>Math.random());routeLayout=chooseRoute(settings.mode);deckSession=settings.contentMode==='decks'?new DeckSession(activeSet.decks):null;deckSpaces=deckSession?assignDeckSpaces(settings.size,deckSession.decks,game.specials):[];boostPaints=deckSession?availableBoostPaints(deckSession.decks,settings.theme):[];events=deckSession?null:conceptEvents(activeSet.items);$('pieces').replaceChildren();$('welcome').hidden=true;$('error').hidden=true;$('playArea').hidden=false;$('context').textContent=activeSet.name+' · '+(settings.mode==='race'?'Race':'Endless Fun');intro=true;render();fit();const token=epoch;setTimeout(()=>{if(token!==epoch)return;intro=false;render();},1000);}

let deckSelection;const boostOptions=mountBoostOptions($('special'));
function availableBoostPaints(decks,theme){return [...new Set(Array.from({length:40},(_,i)=>spacePaint(theme,i,40).fill))].filter(c=>decks.every(d=>!similarColors(c,d.deck.color)));}
const deckView=createDeckView({board:$('board'),sound:()=>settings.sound,onDraw:async(key,button)=>{if(!deckSession||game.phase!=='CONTENT'||deckSession.state!=='WAIT_FOR_DRAW')return;const draw=deckSession.draw(key);if(!draw){deckView.deny(button);return;}const token=epoch;try{if(await deckView.open(draw)&&token===epoch)deckSession.open(draw.generation);}catch(error){$('error').textContent=error.message;$('error').hidden=false;deckSession.cancel();deckView.cancel();deckSession.wait(key);fit();}},onContinue:async()=>{const token=epoch,key=deckSession?.required,cardToken=deckSession?.returnCard();if(cardToken==null)return;if(await deckView.close(key)&&token===epoch&&deckSession.finish(cardToken)){game.finishContent();fit();render();await resolve(epoch);}}});
menu=mountSetupMenu({gameType:'board-race',dialog:$('setup'),form:$('setupForm'),title:$('setupTitle'),setSelect:$('setSelect'),themeSelect:$('themeSelect'),sound:$('sound'),getSets:()=>sets,setSets:next=>sets=next,onContentChange:summary,visuals:[$('styleLabel')],gameplay:['modeLabel','sizeLabel','displayLabel','playersLabel'].map($),status:[$('setupError')],footer:$('setupForm').querySelector('.dialog-actions'),committedTheme:()=>settings.theme,extraTabs:[{id:'boosts',label:'Boosts',nodes:[boostOptions.panel]}]});
deckSelection=mountDeckSelection($('setup').querySelector('[data-panel=content]'),summary);
$('addPlayer').onclick=()=>{if(setupNames.length<4){setupNames.push('Player '+(setupNames.length+1));playerForms();$('name'+(setupNames.length-1)).focus();}};$('size').oninput=()=>$('sizeValue').textContent=$('size').value;$('setSelect').onchange=summary;
$('setupForm').onsubmit=async e=>{e.preventDefault();if(loading||$('play').disabled)return;loading=true;$('play').disabled=true;try{const content=deckSelection.mode==='decks'?{name:'Cards / Decks',decks:deckSelection.read()}:menu.sessionSet(await setRepository.get($('setSelect').value));if(!content.decks)validatePlayableSet(content);else for(const entry of content.decks)for(const card of entry.deck.cards)if(card.image?.type==='asset'&&!await activityAssets.get(card.image.assetId))throw Error(entry.deck.name+': an image is missing. Replace it before playing.');const next=readSettings(),key=JSON.stringify([content.decks?content.decks:menu.contentKey(content),gameplayKey(next),next.boosts,next.names]);const restart=!game||key!==activeKey||game.phase==='COMPLETE';menu.commit();$('setup').close();if(!restart){settings=next;persist();applyTheme(settings.theme);if(!settings.sound)stopAllAudio();if(deckSession)boostPaints=availableBoostPaints(deckSession.decks,settings.theme);fit();render();return;}draft={settings:next,content,key};pawnChoices();$('pawns').showModal();}catch(error){$('setupError').textContent=error.message;}finally{loading=false;summary();}};
$('backPawns').onclick=()=>{$('pawns').close();$('setup').showModal();};$('pawns').addEventListener('cancel',e=>{e.preventDefault();$('backPawns').click();});$('startGame').onclick=()=>{if(!draft)return;settings=draft.settings;activeSet=draft.content;activeKey=draft.key;draft=null;persist();applyTheme(settings.theme);$('pawns').close();start();};
async function resolveBoost(choice={}){if(game?.phase!=='SPECIAL')return;const effect=game.effect;if(!game.resolveSpecial(choice))return;effectAnimating=['switch','shuffle'].includes(effect)&&choice.use;$('specialOverlay').close();render();if(['switch','shuffle'].includes(effect)&&choice.use){const token=epoch;await pause(500);if(token!==epoch)return;}effectAnimating=false;render();resolve(epoch).catch(error=>{$('error').textContent=error.message;$('error').hidden=false;});}
$('ackEffect').onclick=()=>resolveBoost();
$('reveal').onclick=()=>{if(game?.phase!=='CONTENT'||$('task').dataset.revealed==='true')return;revealTask($('task'));$('reveal').disabled=true;};
$('taskDone').onclick=async()=>{if(game?.phase!=='CONTENT'||$('taskDone').disabled)return;$('taskDone').disabled=true;const token=epoch,wasRevealed=$('task').dataset.revealed==='true';revealTask($('task'));$('reveal').disabled=true;if(!wasRevealed&&!matchMedia('(prefers-reduced-motion: reduce)').matches)await pause(ANSWER_REVEAL_MS);if(token!==epoch)return;playCorrect(settings.sound);$('task').close();game.finishContent();render();await resolve(epoch);};
for(const id of ['specialOverlay','task','complete'])$(id).addEventListener('cancel',e=>e.preventDefault());
$('roll').onclick=()=>roll().catch(error=>{$('error').textContent=error.message;$('error').hidden=false;});$('settingsOpen').onclick=$('chooseStart').onclick=openSetup;$('cancelSetup').onclick=()=>$('setup').close();$('endNow').onclick=()=>{if(game?.phase==='READY')$('endConfirm').showModal();};$('cancelEnd').onclick=()=>$('endConfirm').close();$('confirmEnd').onclick=()=>{if(!game||game.options.mode!=='endless')return;epoch++;$('endConfirm').close();game.endNow();complete();};$('again').onclick=start;
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{}};$('copyLink').onclick=async()=>{try{await navigator.clipboard.writeText(gameURL(settings));$('turn').textContent='Link copied. Import the set on other devices first.';}catch{$('turn').textContent='Copy the game address from your browser.';}};
trackGameViewport(fit);new ResizeObserver(fit).observe($('boardArea'));addEventListener('pagehide',()=>{epoch++;deckView.destroy();die.destroy();completion.destroy();stopAllAudio();});applyTheme(settings.theme);
try{sets=await setRepository.list();$('setSelect').replaceChildren(...sets.map(set=>new Option(set.name,set.id)));if(!sets.some(s=>s.id===settings.set)&&!new URLSearchParams(location.search).has('set'))settings.set=sets[0]?.id||'';await openSetup();}catch(error){$('error').hidden=false;$('error').textContent=error.message;}

