import assert from 'node:assert/strict';
import {activityRegistry as registry} from '../shared/activity/catalog.js';
import {createActivity,updateActivity,validateActivity,createRuntimeSession,exportActivity,importActivity,activityResult} from '../shared/activity/definition.js';
import {migrate,entityIndex,validateReferences,normalizedRect,jsonCopy} from '../shared/activity/contracts.js';
import {validateMediaRef,resolveMedia} from '../shared/activity/media.js';
const base={id:'activity-stable',name:'Animals practice',gameType:'wordly',content:{type:'conceptSet',version:1,data:{setId:'animals-1'}},gameplayConfig:{length:3,selection:'mastery'},themeConfig:{theme:'ocean',sound:true}};
const a=createActivity(base,registry),before=JSON.stringify(a);
assert.deepEqual(importActivity(exportActivity({...a,state:{attempts:9}},registry),registry),a);
assert.equal(a.content.data.setId,'animals-1');assert.equal(a.gameplayConfig.selection,'mastery');
assert.equal(registry.game('wordly').capabilities.assignment,false);
const set={id:'animals-1',name:'Animals',items:['cat','dog','pig','cow','owl'].map((word,i)=>({id:'concept-'+i,word,image:{type:'emoji',value:'🐱'}}))};
const services={sets:{get:async()=>set}};
const one=await createRuntimeSession(a,registry,services),two=await createRuntimeSession(a,registry,services);
one.content.items.reverse();one.content.items[0].word='changed';one.gameplayConfig.length=8;one.events.push({conceptId:'concept-1',attempt:'CAT'});
assert.equal(set.items[0].word,'cat');assert.equal(two.content.items[4].word,'owl');assert.equal(JSON.stringify(a),before);
assert.throws(()=>{one.definition.content.data.setId='changed';},TypeError);
assert.equal(activityResult(one,{completed:true,details:{response:'open response'}}).details.response,'open response');
assert.equal('score' in activityResult(one),false);
await assert.rejects(()=>createRuntimeSession(a,registry,{sets:{get:async()=>null}}),/unavailable/);
assert.throws(()=>importActivity('{bad',registry),/Invalid/);
assert.throws(()=>validateActivity({...a,schemaVersion:99},registry),/version/);
assert.throws(()=>validateActivity({...a,gameType:'future'},registry),/Unsupported/);
assert.throws(()=>validateActivity({...a,content:{type:'scene',version:1,data:{}}},registry),/incompatible/);
assert.throws(()=>jsonCopy(JSON.parse('{"__proto__":{}}')),/Unsafe/);
assert.throws(()=>jsonCopy({image:new Blob(['image'])}),/portable/);
assert.throws(()=>jsonCopy({number:NaN}),/portable/);
assert.deepEqual(migrate({schemaVersion:1,old:'x'},3,{1:v=>({schemaVersion:2,name:v.old}),2:v=>({...v,schemaVersion:3})}),{schemaVersion:3,name:'x'});
assert.throws(()=>migrate({schemaVersion:1},2,{}),/Missing migration/);
assert.throws(()=>migrate({schemaVersion:1},2,{1:v=>v}),/advance/);
// Test-only extensibility fixture: arbitrary graph-shaped author content, not a game.
registry.registerContent({type:'fixture',version:2,migrations:{1:v=>({...v,version:2,data:{...v.data,caption:'migrated'}})},validate(data){const index=entityIndex(data.entities);data.groups.forEach(g=>validateReferences(g.entityIds,index));},resolve:data=>data,editor:'fixture-editor'});
registry.registerGame({id:'fixture-game',supportedContentTypes:['fixture'],defaultGameplayConfig:{},normalizeGameplay:raw=>({tries:Number.isInteger(raw.tries)?raw.tries:2}),editors:{fixture:'fixture-editor'},capabilities:{teacherReview:true,customEditor:true}});
const mount=()=>{};registry.registerEditor('fixture-editor',mount);assert.equal(registry.editor('fixture-game','fixture'),mount);assert.throws(()=>registry.editor('wordly','fixture'));
const structured=createActivity({...base,gameType:'fixture-game',content:{type:'fixture',version:1,data:{entities:[{id:'object-a'},{id:'object-b'}],groups:[{id:'group-a',entityIds:['object-a','object-b']},{id:'group-b',entityIds:['object-a']}]}}},registry);
const roundtrip=importActivity(exportActivity(structured,registry),registry);assert.equal(roundtrip.content.version,2);assert.equal(roundtrip.content.data.caption,'migrated');assert.deepEqual(roundtrip.content.data.groups[1].entityIds,['object-a']);
assert.throws(()=>entityIndex([{id:'a'},{id:'a'}]),/Duplicate/);assert.throws(()=>validateReferences(['missing'],entityIndex([{id:'a'}])),/Missing reference/);
assert.deepEqual(normalizedRect({x:.2,y:.3,width:.1,height:.2}),{x:.2,y:.3,width:.1,height:.2});assert.throws(()=>normalizedRect({x:42,y:68,width:10,height:12}));
assert.equal(await resolveMedia({type:'asset',assetId:'asset-a'},{assets:{get:async id=>id}}),'asset-a');assert.throws(()=>validateMediaRef({type:'url',url:'file:///C:/image.png'}));assert.throws(()=>validateMediaRef({type:'url',url:'javascript:alert(1)'}));
assert.deepEqual(registry.game('dobble').normalizeGameplay({selection:'mastery'}),registry.game('dobble').defaultGameplayConfig);
assert.deepEqual(registry.game('wordly').normalizeGameplay({count:4}),registry.game('wordly').defaultGameplayConfig);
console.log('PASS Activity JSON, detached runtime, immutable author data, live set reference, per-game config, capabilities, editor routing, migrations, stable many-to-many references and media contracts');

const renamed=updateActivity(a,{name:'Renamed',id:'replacement',metadata:{createdAt:'wrong'}},registry);assert.equal(renamed.id,a.id);assert.equal(renamed.metadata.createdAt,a.metadata.createdAt);assert.equal(renamed.name,'Renamed');
