import assert from 'node:assert/strict';
import {BoardRace,distributeSpecials} from '../games/board-race/engine.js';
import {generateBoard,compactBoard} from '../games/board-race/geometry.js';
import {conceptEvents} from '../games/board-race/content.js';
let count=0;for(const mode of ['race','endless'])for(const layout of ['winding','snake','spiral','random'])for(const size of [12,24,40])for(const [width,height] of [[1100,570],[760,360],[370,480],[760,210]])for(let seed=0;seed<5;seed++){let n=seed+1;const b=generateBoard({mode,layout,size,width,height,random:()=>((n=Math.imul(n,1664525)+1013904223>>>0)/2**32)});assert.equal(b.tiles.length,size);for(const p of b.points){assert(p.x-b.diameter/2>=0&&p.x+b.diameter/2<=width);assert(p.y-b.diameter/2>=0&&p.y+b.diameter/2<=height);}for(let i=0;i<b.points.length;i++)for(let j=0;j<i;j++)assert(Math.hypot(b.points[i].x-b.points[j].x,b.points[i].y-b.points[j].y)>b.diameter);assert(b.diameter>=12);count++;}
const drain=g=>{if(g.phase==='ROLLING')g.settleRoll();while(g.phase==='MOVING')g.step();};
let g=new BoardRace({size:24,special:false},()=>0);assert.equal(g.player.position,-1);assert(g.beginRoll(4));assert(!g.beginRoll(6));assert.equal(g.phase,'ROLLING');assert.equal(g.step(),false);g.settleRoll();g.step();assert.equal(g.player.position,0);drain(g);assert.equal(g.player.position,3);assert.equal(g.phase,'CONTENT');g.finishContent();assert.equal(g.current,1);
g.player.position=22;g.beginRoll(6);drain(g);assert.equal(g.phase,'COMPLETE');assert.deepEqual(g.winners,[1]);assert.equal(g.player.totalSpacesMoved,2);
g=new BoardRace({mode:'endless',size:24,special:false},()=>0);assert.equal(g.player.position,0);assert.equal(g.player.lap,1);assert.equal(g.phase,'READY');g.player.position=21;g.beginRoll(5);drain(g);assert.equal(g.player.position,2);assert.equal(g.player.lap,2);assert.equal(g.player.totalSpacesMoved,5);g.finishContent();assert.equal(g.current,1);g.endNow();assert.deepEqual(g.winners,[0]);
g=new BoardRace({mode:'endless'},()=>0);g.endNow();assert.deepEqual(g.winners,[0,1]);
for(const effect of ['forward','back','again','skip']){g=new BoardRace({mode:'endless',special:false},()=>0);g.specials={1:effect,3:'again',23:'again'};g.beginRoll(1);drain(g);assert.equal(g.phase,'SPECIAL');assert.equal(g.player.position,1);assert.equal(g.specialResolved,false);g.resolveSpecial();drain(g);assert.equal(g.phase,effect==='again'||effect==='skip'?'READY':'CONTENT');assert.equal(g.specialResolved,true);assert.equal(g.players[0].position,effect==='forward'?3:effect==='back'?0:1);assert.equal(g.players[0].totalSpacesMoved,effect==='forward'?3:effect==='back'?0:1);if(g.phase==='CONTENT')g.finishContent();assert.equal(g.current,effect==='again'?0:1);if(effect==='skip'){g.beginRoll(2);drain(g);g.finishContent();assert.equal(g.current,1);assert.equal(g.players[0].skip,false);assert.deepEqual(g.skipped,[0]);}}
g=new BoardRace({mode:'endless',special:false},()=>0);g.specials={0:'again'};assert.equal(g.phase,'READY');g.player.position=23;g.beginRoll(1);drain(g);assert.equal(g.effect,'again');assert.equal(g.player.lap,2);
for(const mode of ['race','endless'])for(let size=12;size<=40;size++){assert.deepEqual(distributeSpecials(size,mode,false),{});const s=distributeSpecials(size,mode,true);assert(Object.keys(s).length>=1);assert.equal(Object.keys(s).length,Math.round(size*.25));for(const key of Object.keys(s)){if(mode==='race')assert(+key>=2&&+key<size);assert(!(String(+key+1) in s));}}
const items=Array.from({length:5},(_,id)=>({id})),copy=JSON.stringify(items),events=conceptEvents(items);assert.equal(new Set(Array.from({length:5},()=>events.next().concept.id)).size,5);assert.equal(JSON.stringify(items),copy);
console.log(`PASS Board Race: ${count} geometries, bounds/non-overlap, Race finish, tile steps, lap wrap, actual movement, initial spawn, all effects, no chains, skip once, extra roll, ties, content isolation.`);

for(const style of ['tiles','circles'])for(const mode of ['race','endless'])for(let size=12;size<=40;size++)for(const [width,height] of [[1100,500],[370,470],[800,190]]){const b=compactBoard({style,mode,size,width,height});assert.equal(b.tiles.length,size);for(const p of b.points){assert(p.x-b.diameter/2>=0&&p.x+b.diameter/2<=width);assert(p.y-b.diameter/2>=0&&p.y+b.diameter/2<=height);}let close=0;for(let i=0;i<b.points.length;i++)for(let j=0;j<i;j++){const a=b.points[i],c=b.points[j],dx=Math.abs(a.x-c.x),dy=Math.abs(a.y-c.y);assert(style==='tiles'?dx>=b.diameter||dy>=b.diameter:Math.hypot(dx,dy)>=b.diameter);if(j===i-1&&Math.abs(Math.hypot(dx,dy)/b.diameter-1.5)<.01)close++;}if(style==='circles')assert(close>=b.points.length*.65);assert(b.diameter>=22);}
for(const fraction of [0,.3,.6,.99]){const g=new BoardRace({players:4,special:false},()=>fraction);assert.equal(g.current,Math.floor(fraction*4));assert.equal(g.revealed.size,0);}
console.log('PASS compact board: 348 configurations, tile bounds/non-overlap, circle radius gaps, random starters, locked ROLLING state.');

// Numbered N is a playable landing; the following step reaches the separate Finish.
g=new BoardRace({size:12,special:false},()=>0);g.player.position=10;g.beginRoll(1);drain(g);assert.equal(g.player.position,11);assert.equal(g.phase,'CONTENT');g.finishContent();g.current=0;g.beginRoll(1);drain(g);assert.equal(g.player.position,12);assert.equal(g.phase,'COMPLETE');
