import assert from 'node:assert/strict';
import {BoostRace} from '../games/board-race/boost-engine.js';
import {distributeSpecials} from '../games/board-race/engine.js';
const fresh=(options={})=>new BoostRace({mode:'endless',size:30,special:false,...options},()=>0);
const hit=(g,e)=>{g.effect=e;g.phase='SPECIAL';g.specialResolved=false;};
const drain=g=>{while(g.phase==='MOVING')g.step();};
for(const enabled of [[],['shield'],['forward','team']])for(let i=0;i<30;i++)assert(Object.values(distributeSpecials(30,'race',true,Math.random,enabled)).every(v=>enabled.includes(v)));
for(const ability of ['shield','pass'])for(const use of [false,true]){const g=fresh();g.player.ability=ability;hit(g,'forward');assert.equal(g.resolveSpecial(),false);assert(g.resolveSpecial({use,recipient:1}));drain(g);assert.equal(g.players[0].ability,null);assert.equal(g.players[0].position,use?0:2);assert.equal(g.players[1].position,use&&ability==='pass'?2:0);}
let g=fresh();hit(g,'shield');g.resolveSpecial({use:true});g.current=g.turnSeat=0;hit(g,'pass');assert.equal(g.resolveSpecial({use:true}),false);g.resolveSpecial({use:true,keep:'old'});assert.equal(g.players[0].ability,'shield');g.current=g.turnSeat=0;hit(g,'pass');g.resolveSpecial({use:true,keep:'new'});assert.equal(g.players[0].ability,'pass');
g=fresh();g.player.ability='pass';hit(g,'again');g.resolveSpecial({use:true,recipient:1});assert.equal(g.current,1);assert.equal(g.bonusRemaining,1);g.beginRoll(1);g.settleRoll();drain(g);g.finishContent();assert.equal(g.current,1);g.beginRoll(1);g.settleRoll();drain(g);g.finishContent();assert.equal(g.current,0);
g=fresh();Object.assign(g.players[0],{position:24,lap:3,totalSpacesMoved:84});Object.assign(g.players[1],{position:2,lap:1,totalSpacesMoved:2});hit(g,'switch');g.resolveSpecial({use:true,recipient:1});assert.deepEqual(g.players.map(p=>[p.position,p.lap,p.totalSpacesMoved]),[[2,1,2],[24,3,84]]);
g=fresh();Object.assign(g.players[0],{position:24,lap:3,totalSpacesMoved:84});Object.assign(g.players[1],{position:2,lap:1,totalSpacesMoved:2});hit(g,'shuffle');g.resolveSpecial({use:true});assert.deepEqual(g.players.map(p=>[p.position,p.lap,p.totalSpacesMoved]),[[2,4,84],[24,1,2]]);
g=fresh();g.players[0].position=4;g.players[1].position=19;hit(g,'shuffle');g.resolveSpecial({use:true});assert(g.players.every(p=>p.lap===1));
for(const n of [3,4]){g=fresh({players:n});g.players.forEach((p,i)=>{p.position=i*4;p.totalSpacesMoved=i*10;});const positions=g.players.map(p=>p.position).sort((a,b)=>a-b);hit(g,'shuffle');g.resolveSpecial({use:true});assert.deepEqual(g.players.map(p=>p.position).sort((a,b)=>a-b),positions);assert.deepEqual(g.players.map(p=>p.totalSpacesMoved),Array.from({length:n},(_,i)=>i*10));}
g=fresh();hit(g,'lucky');g.resolveSpecial();assert.equal(g.phase,'LUCKY_ROLL');g.applyLucky(2,5);drain(g);assert.equal(g.player.position,5);assert.equal(g.player.totalSpacesMoved,5);
g=fresh();hit(g,'reverse');g.resolveSpecial();g.phase='CONTENT';g.finishContent();assert.equal(g.current,0);g.beginRoll(2);g.settleRoll();drain(g);assert.equal(g.player.position,0);assert.equal(g.player.totalSpacesMoved,0);assert.equal(g.player.lap,1);assert.equal(g.player.reverse,false);
g=fresh({players:3});hit(g,'steal');g.resolveSpecial({recipient:1});assert.equal(g.current,0);assert.equal(g.turnSeat,1);g.beginRoll(1);g.settleRoll();drain(g);g.finishContent();assert.equal(g.current,2);
g=fresh();hit(g,'team');g.resolveSpecial({recipient:1});g.phase='CONTENT';g.finishContent();assert.equal(g.current,0);g.beginRoll(3);g.settleRoll();drain(g);assert.deepEqual(g.players.map(p=>p.position),[3,3]);g.finishContent();assert.equal(g.current,1);assert.equal(g.phase,'CONTENT');g.finishContent();assert.equal(g.current,1);assert.equal(g.phase,'READY');
g=fresh({mode:'race',size:12});g.players.forEach(p=>p.position=10);g.turnPartner=1;g.beginRoll(3);g.settleRoll();drain(g);assert.equal(g.phase,'COMPLETE');assert.deepEqual(g.winners,[0,1]);
for(const effect of ['switch','shuffle','shield','pass']){g=fresh();const positions=g.players.map(p=>p.position);hit(g,effect);g.resolveSpecial({use:false});assert.deepEqual(g.players.map(p=>p.position),positions);assert.equal(g.players[0].ability,null);}
console.log('PASS boost selection, optional decisions, ability consumption/conflict, delayed bonus roll, swaps, shuffle laps/totals, lucky, reverse, stolen turn, Team Up tasks/shared victory');
