import {THEME_IDS} from '../shared/themes.js';
const f=document.querySelector('iframe'),out=document.querySelector('pre'),pause=ms=>new Promise(r=>setTimeout(r,ms));let d;const $=s=>d.querySelector(s),cells=()=>[...d.querySelectorAll('.cell')],check=(v,m)=>{if(!v)throw Error(m)},wait=async fn=>{for(let i=0;i<200;i++){if(fn())return;await pause(20)}throw Error('Timeout')},pass=m=>out.textContent+='PASS '+m+'\n';
async function open(w,h,theme,mode,sound=false){f.style.width=w+'px';f.style.height=h+'px';f.src='../games/tic-tac-toe/?set=animals-1&steal=true&theme='+theme+'&taskMode='+mode+'&sound='+sound;await new Promise(r=>f.onload=r);d=f.contentDocument;await wait(()=>$('#setup').open);$('#setupX').value='Masha';$('#setupO').value='Sasha';$('#play').click();await wait(()=>!$('#playArea').hidden)}
async function choose(i){cells()[i].click();await wait(()=>$('#task').open&&!$('#correct').disabled)}
async function answer(correct){$(correct?'#correct':'#incorrect').click();await wait(()=>d.body.dataset.state==='SELECT_CELL'||$('#result').open||(d.body.dataset.state==='STEAL_TASK'&&!$('#correct').disabled))}
function bounds(w,h){const r=$('#task').getBoundingClientRect();check(Math.abs(r.x+r.width/2-w/2)<1&&Math.abs(r.y+r.height/2-h/2)<1,'Not centered');for(const id of ['task','correct','incorrect']){const b=$('#'+id).getBoundingClientRect();check(b.x>=0&&b.y>=0&&b.right<=w&&b.bottom<=h,'Clipped '+id)}check(d.documentElement.scrollWidth<=w,'Horizontal overflow');return JSON.stringify([r.x,r.y,r.width,r.height])}
document.querySelector('#run').onclick=async()=>{out.textContent='';const key='sunny-stacy.tictactoe.settings.v1',saved=localStorage.getItem(key);try{let n=0;for(const [w,h] of [[390,844],[412,915],[844,390],[915,412],[820,1180],[1024,768],[1366,768],[1920,1080]]){await open(w,h,THEME_IDS[n%8],n++%2?'word-blur':'picture-blur');for(let i=0;i<9;i++){await choose(i);const r=bounds(w,h),dialog=$('#task');$('#incorrect').click();await pause(50);check(bounds(w,h)===r&&dialog.dataset.revealed==='true','Reveal jump');await wait(()=>d.body.dataset.state==='STEAL_TASK'&&!$('#correct').disabled);check($('#task')===dialog&&bounds(w,h)===r,'Steal jump');await answer(false);check(!cells()[i].dataset.player,'Failed steal claimed cell')}pass(w+'x'+h+' all 9 cells: centered TASK / reveal / STEAL, controls fit')}
for(const sound of [false,true]){await open(1366,768,'space','word-blur',sound);let bursts=0,closes=0,notes=[];new f.contentWindow.MutationObserver(records=>{for(const r of records)for(const n of r.addedNodes)if(n.classList?.contains('victory-confetti'))bursts++}).observe(d.body,{childList:true});f.contentWindow.AudioContext=class{currentTime=0;destination={};resume(){return Promise.resolve()}createOscillator(){return {type:'',frequency:{value:0,setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){},start(t){notes.push(t)},stop(){},disconnect(){}}}createGain(){return {gain:{setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){},disconnect(){}}}};const start=$('.player.active').dataset.player;for(const i of [0,3,1,4,2]){await choose(i);await answer(true)}check($('#result').open&&$('#result').matches(':modal'),'End dialog not blocking');check($('#resultText').textContent===(start==='X'?'🚀 Masha wins!':'🛸 Sasha wins!'),'Winner name/marker');check(bursts===1,'Confetti count');check(notes.length===(sound?21:0),'Victory sound not exactly one six-note sting');check(cells().every(c=>c.disabled),'Board unlocked');await pause(3300);check(!$('.victory-confetti'),'Confetti remains');$('#again').click();check(!$('#result').open&&$('#winLine').hasAttribute('hidden')&&cells().every(c=>!c.dataset.player),'Reset residue');check($('.player.active').dataset.player!==start,'Starter');await choose(0);check($('#task').dataset.taskMode==='word-blur','Mode lost');pass('Win sound='+sound+': one burst/sting, modal, winner, cleanup, Play Again')}
await open(1366,768,'candy','picture-blur');for(const i of [0,1,2,4,3,5,7,6,8]){await choose(i);await answer(true)}check($('#result').open&&$('#resultText').textContent==="It's a draw!"&&!$('.victory-confetti')&&$('#winLine').hasAttribute('hidden'),'Draw celebration');pass('Draw remains neutral');out.textContent+='ALL CENTERING AND VICTORY CHECKS PASSED';}catch(e){out.textContent+='FAIL: '+e.message;console.error(e)}finally{f.src='about:blank';saved===null?localStorage.removeItem(key):localStorage.setItem(key,saved)}};
