import {activityRegistry} from '../shared/activity/catalog.js';
import {activityRepository,activityAssets,exportBundle,importBundle} from '../shared/activity/repository.js';
import {transact} from '../shared/database.js';
const frame=document.querySelector('iframe'),out=document.querySelector('pre'),repo=activityRepository(activityRegistry),pause=ms=>new Promise(r=>setTimeout(r,ms));let doc,ids=[],assetIds=[];
const $=s=>doc.querySelector(s),btn=t=>[...doc.querySelectorAll('button')].find(b=>b.textContent===t),check=(v,m)=>{if(!v)throw Error(m);},pass=t=>out.textContent+='PASS '+t+'\n';
async function wait(fn){for(let i=0;i<400;i++){if(await fn())return;await pause(20);}throw Error('Timed out: '+fn);}
async function load(url){frame.src=url;await new Promise(r=>frame.onload=r);doc=frame.contentDocument;}
function fill(node,value){node.value=value;node.dispatchEvent(new frame.contentWindow.Event('input',{bubbles:true}));}
async function imageFile(){const canvas=document.createElement('canvas');canvas.width=1920;canvas.height=1080;const c=canvas.getContext('2d');c.fillStyle='#d9ecca';c.fillRect(0,0,1920,1080);c.font='110px serif';for(const x of [.2,.5,.8])c.fillText('⭐',1920*x-50,400);c.fillStyle='#40857b';c.font='32px sans-serif';c.fillText('Find the three stars',650,850);return new File([await new Promise(r=>canvas.toBlob(r))],'high-resolution.png',{type:'image/png'});}
async function upload(file){btn('+ Add image').click();const input=$('.image-input-dialog input[type=file]'),transfer=new frame.contentWindow.DataTransfer();transfer.items.add(file);input.files=transfer.files;input.dispatchEvent(new frame.contentWindow.Event('change',{bubbles:true}));await wait(()=>$('.scene-background-column img, .scene-background')?.naturalWidth>0);}
async function draw(x,y,w,h){await pause(35);const canvas=$('.scene-canvas'),r=canvas.getBoundingClientRect(),W=frame.contentWindow;canvas.setPointerCapture=()=>{};const p=(type,xx,yy)=>canvas.dispatchEvent(new W.PointerEvent(type,{bubbles:true,button:0,pointerId:1,clientX:r.left+xx*r.width,clientY:r.top+yy*r.height}));p('pointerdown',x,y);p('pointermove',x+w,y+h);p('pointerup',x+w,y+h);}
function clickScene(x,y,target=$('#scene')){const r=$('#scene').getBoundingClientRect();const fire=()=>target.dispatchEvent(new frame.contentWindow.MouseEvent('click',{bubbles:true,detail:1,clientX:r.left+x*r.width,clientY:r.top+y*r.height}));const lens=$('.spy-lens'),l=lens?.getBoundingClientRect(),inside=l&&!lens.hidden&&Math.hypot(r.left+x*r.width-l.left-l.width/2,r.top+y*r.height-l.top-l.height/2)<=l.width/2;fire();if(!inside)fire();}
const rect=()=>{const r=$('#scene').getBoundingClientRect();return [r.x,r.y,r.width,r.height];};const same=(a,b)=>a.every((n,i)=>Math.abs(n-b[i])<1);
document.querySelector('#run').onclick=async()=>{out.textContent='';document.querySelector('#run').disabled=true;const settingsKey='sunny-stacy.i-spy.settings.v1',saved=localStorage.getItem(settingsKey);try{
await load('../sets/');await wait(()=>$('#create'));$('#create').click();check($('#createContent').open,'Picker opens');check(doc.querySelectorAll('.content-types a').length===5,'Five types');await load('../content/editor.html?type=scene');await wait(()=>btn('+ Add image'));check(!doc.querySelector('dialog[open]'),'Full-page editor');fill($('#contentName'),'__hotspot_test_'+Date.now());await upload(await imageFile());check($('.scene-background-column img, .scene-background').naturalWidth===1920,'Editor original resolution');btn('+ Add Prompt').click();fill($('.scene-prompt-row textarea'),'Find three stars.');btn('Next').click();await wait(()=>$('.scene-background')?.naturalWidth>0);btn('Add Hotspot').click();for(const x of [.15,.45,.75])await draw(x,.25,.12,.16);check(doc.querySelectorAll('.scene-hotspot').length===3,'Three drawn hotspots');btn('Add Hotspot').click();check($('.scene-arrange-toolbar'),'Compact arrange toolbar');$('#contentForm').requestSubmit();await wait(()=>$('#status').textContent==='Saved');const id=new URL(frame.contentWindow.location.href).searchParams.get('id');ids.push(id);const record=await repo.get(id);assetIds.push(record.content.data.background.assetId);check(record.content.version===2&&record.content.data.assets.length===0,'Hotspot-only saved');check(record.content.data.targets[0].answers.length===3,'Generic answers');pass('My Content picker → full-page Scene → original upload → draw 3 hotspots → compact target → save with zero assets');
await load('../content/editor.html?id='+id);await wait(()=>btn('Next'));btn('Next').click();await wait(()=>$('.scene-hotspot'));check(doc.querySelectorAll('.scene-hotspot').length===3,'Reopen');const spot=$('.scene-hotspot');spot.setPointerCapture=()=>{};const rr=$('.scene-canvas').getBoundingClientRect(),W=frame.contentWindow;spot.dispatchEvent(new W.PointerEvent('pointerdown',{button:0,bubbles:true,pointerId:2,clientX:rr.left+rr.width*.15,clientY:rr.top+rr.height*.25}));spot.dispatchEvent(new W.PointerEvent('pointermove',{button:0,bubbles:true,pointerId:2,clientX:rr.left+rr.width*.16,clientY:rr.top+rr.height*.26}));spot.dispatchEvent(new W.PointerEvent('pointerup',{button:0,bubbles:true,pointerId:2}));check($('.scene-resize'),'Hotspot has resize handle');$('#contentForm').requestSubmit();await wait(()=>$('#status').textContent==='Saved');pass('Hotspots reopen, move, select and expose resize controls');
const updated=await repo.get(id),copy=await importBundle(await exportBundle(updated,activityRegistry),activityRegistry);ids.push(copy.id);assetIds.push(copy.content.data.background.assetId);const bitmap=await createImageBitmap(await activityAssets.get(copy.content.data.background.assetId));check(bitmap.width===1920&&bitmap.height===1080,'Portable original image');bitmap.close();pass('Export/import retains full 1920×1080 background and answer IDs');
// Second target shares a hotspot and has a long prompt to catch layout shifts.
updated.content.data.targets.push({id:'second',prompt:'Find the first star again. This longer prompt must not move the scene when the next target appears.',answers:[{id:'again',type:'hotspot',hotspotId:updated.content.data.hotspots[0].id}]});await repo.save(updated);const before=JSON.stringify(await repo.get(id));
await load('../games/i-spy/?activity='+id+'&order=in-order&sound=false');await wait(()=>$('#setup')?.open);$('#setupForm').requestSubmit();await wait(()=>doc.body.dataset.state==='INPUT');check($('#sceneBackground').naturalWidth===1920&&$('#sceneBackground').naturalHeight===1080,'Runtime original resolution');check(!$('.scene-hotspot')&&!$('.spy-object'),'No hotspot DOM hints');clickScene(.2,.3);check($('#counter').textContent==='1 / 3','First hotspot');clickScene(.2,.3);clickScene(.95,.9);check($('#counter').textContent==='1 / 3','Repeat and wrong neutral progress');clickScene(.5,.3);const a=rect();clickScene(.8,.3);check(!$('#targetSuccess').hidden&&same(a,rect()),'Stable completion overlay');await wait(()=>$('#scene').dataset.target==='second');check(same(a,rect()),'Stable next long prompt');check($('#counter').textContent==='0 / 1','Reused hotspot reset');pass('Invisible hotspot gameplay, repeated/wrong clicks, generic counter, reused region and zero-shift overlay/next prompt');
for(const [w,h] of [[1100,850],[768,900],[390,700],[844,390]]){frame.style.width=w+'px';frame.style.height=h+'px';await pause(150);const r=rect();check(Math.abs(r[2]/r[3]-1920/1080)<.01,'Aspect ratio');check(r[0]>=0&&r[1]>=0&&r[0]+r[2]<=w+1&&r[1]+r[3]<=h+1,'Full scene fits');}clickScene(.2,.3);await wait(()=>$('#complete').open);check(JSON.stringify(await repo.get(id))===before,'No runtime persistence');pass('Desktop/tablet/mobile landscape/portrait mapping and immutable saved content');
frame.style.width='1100px';frame.style.height='850px';const crowded=structuredClone(updated);crowded.id=crypto.randomUUID();ids.push(crowded.id);crowded.name='__50_assets';crowded.content.data.assets=Array.from({length:50},(_,i)=>({id:'asset'+i,name:'Element '+i,media:updated.content.data.background}));crowded.content.data.targets=Array.from({length:10},(_,i)=>({...updated.content.data.targets[0],id:'t'+i}));await repo.save(crowded);await load('../content/editor.html?id='+crowded.id);await wait(()=>$('.scene-prepare-images button'));check(doc.querySelectorAll('.scene-prepare-images button').length===50,'50 prepared assets');check(doc.querySelectorAll('.scene-prompt-row').length===10,'10 editable prompts');const panel=$('.scene-prompts');check(panel.scrollHeight>panel.clientHeight,'Prompts independently scroll');btn('Next').click();btn('Select Elements').click();check(doc.querySelectorAll('.scene-element-picker button').length===50,'All assets available for placement');check(!$('.scene-palette'),'No permanent sidebar');pass('50 assets, 10 editable prompts and transient placement tray');
const alpha=document.createElement('canvas');alpha.width=200;alpha.height=200;const ctx=alpha.getContext('2d');ctx.fillStyle='#cf4a72';ctx.beginPath();ctx.arc(100,100,45,0,Math.PI*2);ctx.fill();const media=await activityAssets.upload(new File([await new Promise(r=>alpha.toBlob(r))],'transparent.png',{type:'image/png'}));assetIds.push(media.assetId);const hybrid=structuredClone(updated);hybrid.id=crypto.randomUUID();ids.push(hybrid.id);hybrid.name='Hybrid verification';hybrid.content.data.assets=[{id:'fruit',name:'Fruit',media}];hybrid.content.data.objects=[{id:'edge',assetId:'fruit',x:-.08,y:.72,width:.2,height:.2},{id:'decoy',assetId:'fruit',x:.16,y:.26,width:.12,height:.16}];hybrid.content.data.targets[0].answers.push({id:'edge-answer',type:'object',sceneObjectId:'edge'});await repo.save(hybrid);await load('../games/i-spy/?activity='+hybrid.id+'&sound=false&order=in-order');await wait(()=>$('#setup')?.open);$('#setupForm').requestSubmit();await wait(()=>doc.body.dataset.state==='INPUT');clickScene(.2,.3,$('[data-object-id="decoy"]'));check($('#counter').textContent==='1 / 4','Decoy passes through to hotspot');clickScene(.02,.82,$('[data-object-id="edge"]'));check($('#counter').textContent==='2 / 4','Clipped object remains valid');const image=$('[data-object-id="edge"] img'),style=frame.contentWindow.getComputedStyle(image),sceneStyle=frame.contentWindow.getComputedStyle($('#scene'));check(style.filter.includes('drop-shadow'),'Alpha silhouette filter');check(sceneStyle.overflow==='hidden','Scene clips feedback');check(frame.contentWindow.getComputedStyle($('[data-object-id="edge"]'),'::after').content==='none','No rectangle pseudo-element');pass('Hybrid precedence, partial off-canvas object, alpha-aware glow and clipping');
out.textContent+='ALL CONTENT / HOTSPOT CHECKS PASSED';
}catch(e){out.textContent+='FAIL '+e.stack;console.error(e);}finally{for(const id of ids)await transact('readwrite',s=>s.delete(id),'activities');for(const id of assetIds)await transact('readwrite',s=>s.delete(id),'activityAssets');if(saved===null)localStorage.removeItem(settingsKey);else localStorage.setItem(settingsKey,saved);document.querySelector('#run').disabled=false;}};
