import {setRepository,newId} from '../shared/sets.js';
import {exportSet} from '../shared/transfer.js';
const out=document.querySelector('#result'),frame=document.querySelector('#frame');
const wait=async(fn,label='condition')=>{for(let i=0;i<180;i++){if(fn())return;await new Promise(r=>setTimeout(r,60));}throw Error('Timed out: '+label);};
const assert=(v,m)=>{if(!v)throw Error(m);};const pass=m=>out.textContent+='PASS: '+m+'\n';
const open=async url=>{frame.src=url;await new Promise(r=>frame.onload=r);await wait(()=>frame.contentDocument?.querySelector('#setLabel'));};
const doc=()=>frame.contentDocument,params=()=>new URL(frame.contentWindow.location.href).searchParams;
const clickText=(root,text)=>[...root.querySelectorAll('button')].find(b=>b.textContent===text).click();
const config='&mode=images&count=2&movement=fast&theme=candy&sound=false&autoNext=false&delay=1000';
const preserved=()=>{assert(params().get('movement')==='fast'&&params().get('theme')==='candy'&&params().get('autoNext')==='false','Lost URL config');};
const upload=async(set)=>{const transfer=new frame.contentWindow.DataTransfer();transfer.items.add(new frame.contentWindow.File([await exportSet(set)],'set.json',{type:'application/json'}));const input=doc().querySelector('#missingFile');input.files=transfer.files;input.dispatchEvent(new frame.contentWindow.Event('change'));};
const start=async()=>{await wait(()=>doc().querySelector('.pregame[open]'),'pre-game');assert(!doc().querySelector('[name=per]')&&!doc().querySelector('[data-key=per]'),'Per control remains');assert(!doc().querySelector('.card'),'Premature launch');clickText(doc().querySelector('.pregame'),'Play');await wait(()=>doc().querySelectorAll('.card').length===2,'cards');await new Promise(r=>setTimeout(r,200));};
document.querySelector('#run').onclick=async()=>{out.textContent='';const owned=[],saved=localStorage.getItem('sunny-stacy.dobble.settings.v1');try{
 const base=await setRepository.get('animals-1'),set=await setRepository.create({...base,name:'__delta existing '+newId()});owned.push(set.id);
 await open('../games/dobble/?set='+set.id+config);await start();assert(params().get('set')===set.id,'Existing set replaced');preserved();pass('A/K: exact existing set, required setup, preserved config, no per UI');
 let copied='';Object.defineProperty(frame.contentWindow.navigator,'clipboard',{configurable:true,value:{writeText:async text=>{copied=text;}}});doc().querySelector('#copyLink').click();await wait(()=>copied);const link=new URL(copied);assert(link.searchParams.get('set')===set.id&&!link.searchParams.has('per')&&!link.searchParams.has('items'),'Bad copied link');pass('G: copied active set, all settings, no per/items');
 const cards=[...doc().querySelectorAll('.card')],target=[...cards[0].children].find(el=>[...cards[1].children].some(other=>other.dataset.id===el.dataset.id));target.click();await wait(()=>doc().querySelector('#score').textContent==='1');const signature=()=>[...doc().querySelectorAll('.item')].map(el=>[el.dataset.id,el.dataset.scale,el.style.getPropertyValue('--angle')].join(':')).join('|');const before=signature();
 for(const [w,h] of [[390,844],[412,915],[844,390],[915,412],[820,1180],[1024,768]]){frame.style.width=w+'px';frame.style.height=h+'px';await new Promise(r=>setTimeout(r,250));for(const card of doc().querySelectorAll('.card')){const box=card.getBoundingClientRect();assert(Math.abs(box.width-box.height)<1,'Not circular');assert(box.top>=0&&box.bottom<=h&&box.left>=0&&box.right<=w,'Card outside viewport '+w+'x'+h+' '+JSON.stringify(box));}assert(before===signature()&&doc().querySelector('#score').textContent==='1','Resize reset state');pass('H: '+w+'x'+h+' both cards visible, same target/score/scales/angles');}
 const missing='delta-'+newId();await open('../games/dobble/?set='+missing+config);await wait(()=>!doc().querySelector('#missingSet').hidden);assert(!doc().querySelector('.card')&&params().get('set')===missing,'Silent fallback');preserved();pass('B: missing ID remains authoritative');
 const matching={...base,id:missing,name:'__delta matching'};await upload(matching);await wait(()=>doc().querySelector('.pregame[open]'));owned.push(missing);assert(params().get('set')===missing,'Matching import ID lost');preserved();await start();pass('C: exact JSON resolves requested ID');
 const otherMissing='delta-'+newId();await open('../games/dobble/?set='+otherMissing+config);await wait(()=>!doc().querySelector('#missingSet').hidden);const other={...base,id:'delta-'+newId(),name:'__delta different '+newId()};await upload(other);await wait(()=>!doc().querySelector('#differentImport').hidden);const imported=(await setRepository.list()).find(s=>s.name===other.name);owned.push(imported.id);assert(imported.id===other.id,'Portable ID changed unnecessarily');assert(params().get('set')===otherMissing&&!doc().querySelector('.card'),'Different import replaced requested ID');preserved();pass('D: different JSON waits for explicit replacement');doc().querySelector('#useImported').click();await wait(()=>doc().querySelector('.pregame[open]'));assert(params().get('set')===imported.id,'Explicit import replacement failed');preserved();pass('E: Use this set keeps configuration');
 await open('../games/dobble/?set=delta-missing-choice'+config);await wait(()=>!doc().querySelector('#missingSet').hidden);doc().querySelector('#chooseMissing').click();doc().querySelector('#replacementSet').value=set.id;doc().querySelector('#useReplacement').click();await wait(()=>doc().querySelector('.pregame[open]'));assert(params().get('set')===set.id,'Chosen set not active');preserved();pass('F: explicit local replacement');
 await open('../games/dobble/');await wait(()=>doc().querySelector('.pregame[open]'));assert(!doc().querySelector('.card'),'Remembered config bypassed setup');pass('K: plain Hub launch always opens setup');
 out.textContent+='ALL DELTA CHECKS PASSED';
 }catch(error){out.textContent+='FAIL: '+error.message;console.error(error);}finally{frame.src='about:blank';for(const id of owned)await setRepository.delete(id);if(saved===null)localStorage.removeItem('sunny-stacy.dobble.settings.v1');else localStorage.setItem('sunny-stacy.dobble.settings.v1',saved);}};
