import {upgradeScene} from '../shared/activity/scene.js';
import assert from 'node:assert/strict';
import {CONTENT_LIMITS as L,validateConceptCapacity} from '../shared/activity/limits.js';
import {validators,sentenceDiff} from '../shared/editors/models.js';
import {activityRegistry} from '../shared/activity/catalog.js';
import {exportActivity,importActivity,createRuntimeSession} from '../shared/activity/definition.js';
const fixture=(type,data)=>({id:'author',name:'Example',gameType:'authoring-'+type,schemaVersion:1,content:{type,version:1,data},themeConfig:{theme:'notebook'},gameplayConfig:{},metadata:{createdAt:'2026-10-05T00:00:00Z',updatedAt:'2026-10-05T00:00:00Z'}});
const bridge={bridges:[{id:'b',bricks:[{id:'a',text:'The'},{id:'b',text:'cat'}],gaps:[{id:'gap1',brickId:'a',groupId:'group'},{id:'gap2',brickId:'b',groupId:'group'}],groups:[{id:'group',distractors:[{id:'d',text:'dog'}]}]}]};validators.bridge(bridge);const data=structuredClone(bridge);data.bridges[0].bricks.reverse();validators.bridge(data);assert.equal(data.bridges[0].gaps[0].brickId,'a');assert.throws(()=>validators.bridge({bridges:Array.from({length:L.bridge.bridges+1},(_,i)=>({...bridge.bridges[0],id:'b'+i}))}),/maximum/);
const gapOver=structuredClone(bridge);gapOver.bridges[0].gaps=Array.from({length:6},(_,i)=>({id:'g'+i,brickId:'a',groupId:'group'}));assert.throws(()=>validators.bridge(gapOver),/maximum/);
const scene={background:{type:'asset',assetId:'bg'},assets:[{id:'apple',media:{type:'asset',assetId:'apple-media'}}],objects:[{id:'one',assetId:'apple',x:.2,y:.3,width:.1,height:.1},{id:'two',assetId:'apple',x:.5,y:.5,width:.1,height:.1}],targets:[{id:'red',prompt:'Find red',objectIds:['one','two']},{id:'food',prompt:'Find food',objectIds:['one']}]};validators.scene(scene);const missing=structuredClone(scene);missing.targets[0].objectIds=['missing'];assert.throws(()=>validators.scene(missing),/Missing/);const overflow=structuredClone(scene);overflow.objects=Array.from({length:51},(_,i)=>({...scene.objects[0],id:'o'+i}));assert.throws(()=>validators.scene(overflow),/maximum/);
assert.throws(()=>validators.sentenceCorrection({sentences:[{id:'x',incorrect:'Same',correct:'Same'}]}),/differ/);const diff=sentenceDiff("She don't likes apples.","She doesn't like apples.");assert.equal(diff.left.filter(t=>t.changed).map(t=>t.text).join(''),"don'tlikes");assert.equal(diff.right.filter(t=>t.changed).map(t=>t.text).join(''),"doesn'tlike");
const decks={decks:Array.from({length:4},(_,i)=>({id:'deck'+i,name:'Deck',color:'#123456',cards:Array.from({length:25},(_,j)=>({id:'card'+i+'-'+j,text:'Hello'}))}))};validators.cardDecks(decks);decks.decks[0].cards.push({id:'extra',text:'No'});assert.throws(()=>validators.cardDecks(decks),/maximum 100/);decks.decks[0].cards.pop();const snapshot=JSON.stringify(decks);const session=await createRuntimeSession(fixture('cardDecks',decks),activityRegistry);session.content.decks[0].cards.reverse();assert.equal(JSON.stringify(decks),snapshot);
for(const [type,content] of [['bridge',bridge],['scene',scene],['sentenceCorrection',{sentences:[{id:'s',incorrect:'She go.',correct:'She goes.'}]}],['cardDecks',decks]]){const a=fixture(type,content);assert.deepEqual(importActivity(exportActivity(a,activityRegistry),activityRegistry).content.data,type==='scene'?upgradeScene(content):content);assert.equal(typeof activityRegistry.editor('authoring-'+type,type),'function');}
assert.throws(()=>validateConceptCapacity({items:Array(51)}),/maximum 50/);validateConceptCapacity({items:Array(70)},70);assert.throws(()=>validateConceptCapacity({items:Array(71)},70));
assert.equal(activityRegistry.games().some(g=>/oddOneOut|storyPrompt/.test(g.id)),false);
console.log('PASS centralized limits, boundary rejection, legacy capacity, stable gaps/groups, scene many-to-many refs, live diff, 100-card cap, serialization and runtime order isolation');
