import {activityRegistry} from '../shared/activity/catalog.js';
import {activityRepository} from '../shared/activity/repository.js';
import {transact} from '../shared/database.js';
const frame=document.querySelector('iframe'),out=document.querySelector('pre'),repo=activityRepository(activityRegistry),pause=ms=>new Promise(r=>setTimeout(r,ms));let doc,ids=[];
const $=s=>doc.querySelector(s),btn=t=>[...doc.querySelectorAll('button')].find(b=>b.textContent===t),field=t=>[...doc.querySelectorAll('label')].find(l=>l.firstChild?.textContent===t)?.querySelector('input,textarea'),check=(v,m)=>{if(!v)throw Error(m);};
async function wait(fn){for(let i=0;i<250;i++){if(await fn())return;await pause(20);}throw Error('Timed out');}async function load(type){frame.src='../content/editor.html?type='+type;await new Promise(r=>frame.onload=r);doc=frame.contentDocument;await wait(()=>$ ('.structured-editor'));}function fill(n,v){n.value=v;n.dispatchEvent(new frame.contentWindow.Event('input',{bubbles:true}));}async function save(type){fill($('#contentName'),'__full_page_'+type);$('#contentForm').requestSubmit();await wait(()=>$('#status').textContent==='Saved');const id=new URL(frame.contentWindow.location.href).searchParams.get('id');ids.push(id);return repo.get(id);}
 document.querySelector('#run').onclick=async()=>{out.textContent='';try{
 await load('bridge');btn('+ Add bridge').click();fill(field('Brick 1'),'The');btn('+ Add brick').click();fill(field('Brick 2'),'cat');btn('Select gap').click();btn('Select gap').click();const selects=doc.querySelectorAll('.gap-panel select');selects[1].value=selects[0].value;selects[1].dispatchEvent(new frame.contentWindow.Event('change'));btn('+ Add distractor').click();fill(field('Distractor 1'),'dog');const bridge=await save('bridge');check(bridge.content.data.bridges[0].gaps.length===2,'Bridge gaps');out.textContent+='PASS Full-page Bridge: grouped gaps, distractor and save\n';
 await load('sentenceCorrection');btn('+ Add sentence').click();fill(field('Incorrect sentence'),"She don't likes apples.");fill(field('Correct sentence'),"She doesn't like apples.");check(doc.querySelectorAll('.diff-incorrect mark').length>=2,'Diff');await save('sentence');out.textContent+='PASS Full-page Sentence Correction: live diff and save\n';
 await load('cardDecks');btn('+ Add deck').click();fill(field('Deck name'),'Vocabulary');btn('+ Add card').click();fill(field('Card text'),'First');btn('+ Add card').click();fill(doc.querySelectorAll('.deck-card textarea')[1],'Second');doc.querySelectorAll('.deck-card')[1].querySelectorAll('button')[1].click();const deck=await save('deck');check(deck.content.data.decks[0].cards[0].text==='Second','Order');out.textContent+='PASS Full-page Card Deck: order and save\n';
 frame.src='../content/editor.html?id='+bridge.id;await new Promise(r=>frame.onload=r);doc=frame.contentDocument;await wait(()=>field('Brick 2'));check(field('Brick 2').value==='cat','Reopen');out.textContent+='PASS Reopen preserves content and stable ID\nALL EDITOR WORKFLOW CHECKS PASSED';
 }catch(e){out.textContent+='FAIL '+e.stack;console.error(e);}finally{for(const id of ids)await transact('readwrite',s=>s.delete(id),'activities');}};
