import {createRound,RotationPool} from '../games/dobble/engine.js';
import {mountCards} from '../games/dobble/render.js';
import {setRepository,newId} from '../shared/sets.js';
const out=document.querySelector('#result'),host=document.querySelector('#game');
const words=['cat','dog','elephant','butterfly','hippopotamus','fish','rabbit','crocodile','horse','ladybird','lion','tiger','bear','panda','frog','pig','cow','monkey','fox','wolf','deer','zebra','giraffe','camel','kangaroo','koala','mouse','hamster','hedgehog','squirrel','owl','eagle','duck','chicken','penguin','turtle','snake','octopus','whale','dolphin'];
const emojis=['🐱','🐶','🐘','🦋','🦛','🐟','🐰','🐊','🐴','🐞','🦁','🐯','🐻','🐼','🐸','🐷','🐮','🐵','🦊','🐺','🦌','🦓','🦒','🐪','🦘','🐨','🐭','🐹','🦔','🐿️','🦉','🦅','🦆','🐔','🐧','🐢','🐍','🐙','🐳','🐬'];
const items=Array.from({length:40},(_,i)=>({id:'c'+i,word:words[i],image:emojis[i]}));
const renderedItems=items.map((item,i)=>i%3===0?{...item,image:{src:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFAAAAAoCAYAAABpYH0BAAAAX0lEQVR4nO3QMQ0AIADAMLwgG01oAg88ZEmP/UvHXPvovfF7oB5AgADTAQQIMB1AgADTAQQIMB1AgADTAQQIMB1AgADTAQQIMB1AgADTAQQIMB1AgADTAQQIMB1AgH+7RWu+0uniOcEAAAAASUVORK5CYII=',width:80,height:40}}:item);
function checkBounds(){for(const card of host.children){const bounds=card.getBoundingClientRect(),border=parseFloat(getComputedStyle(card).borderLeftWidth),radius=card.clientWidth/2,cx=bounds.left+border+radius,cy=bounds.top+border+radius;const rects=[...card.children].map(item=>item.getBoundingClientRect());for(let i=0;i<rects.length;i++){const r=rects[i];if(Math.hypot(Math.max(Math.abs(r.left-cx),Math.abs(r.right-cx)),Math.max(Math.abs(r.top-cy),Math.abs(r.bottom-cy)))>radius+.1)throw Error('Rendered item outside circular card');for(const b of rects.slice(i+1))if(Math.min(r.right,b.right)-Math.max(r.left,b.left)>.1&&Math.min(r.bottom,b.bottom)-Math.max(r.top,b.top)>.1)throw Error('Rendered AABBs overlap');}}}
document.querySelector('#run').onclick=async()=>{out.textContent='';let mounted;document.querySelector('#run').disabled=true;try{for(const per of [2,3,4,5,6,7,8,9,10])for(const mode of ['images','words','mixed'])for(const movement of (per===3||per===10?['off','slow','medium','fast']:['off','fast'])){const settings={per,mode,count:mode==='mixed'?2:4,movement};mounted=mountCards(host,createRound(renderedItems,settings,null,Math.random,new RotationPool(renderedItems)),settings,()=>{});for(let f=0;f<45;f++){await new Promise(requestAnimationFrame);checkBounds();}mounted.destroy();out.textContent+='PASS: '+per+'/card '+mode+' '+movement+' — rendered bounds and intersections\n';}out.textContent+='ALL RENDERED CHECKS PASSED\n';}catch(error){out.textContent+='FAIL: '+error.message;console.error(error);}finally{mounted?.destroy();document.querySelector('#run').disabled=false;}};
document.querySelector('#demo').onclick=async()=>{const set=await setRepository.create({name:'Stage 2.1 — 40 concepts',imageSource:'emoji',items:items.map(item=>({...item,id:newId(),image:{type:'emoji',value:item.image}}))});out.textContent='Created demo. ';const link=document.createElement('a');link.textContent='Play 40 concepts';link.href='../games/dobble/?set='+set.id;out.append(link);};
