import assert from 'node:assert/strict';import {createSettingsPreview} from '../shared/settings-preview.js';import {itemScales} from '../games/dobble/sizing.js';import {MARKERS} from '../games/tic-tac-toe/markers.js';import {ANSWER_REVEAL_MS,normalizeTaskMode} from '../games/tic-tac-toe/task-presentation.js';
assert.deepEqual(MARKERS,{notebook:['X','O'],chalkboard:['🔵','🔴'],'board-game':['❤️','⭐'],ocean:['🐟','🦀'],nature:['🌸','🍄'],space:['🚀','🛸'],candy:['🍦','🍩'],'magic-school':['🪄','🕯️']});assert(ANSWER_REVEAL_MS>0&&ANSWER_REVEAL_MS<=180);assert.equal(normalizeTaskMode('bad'),'picture-blur');assert.equal(normalizeTaskMode('word-blur'),'word-blur');
const settings={theme:'notebook',sound:false,count:2};let renders=0;const preview=createSettingsPreview(settings,['theme','sound'],()=>renders++);preview.begin();preview.update({theme:'space',sound:true,count:4});assert.deepEqual(settings,{theme:'space',sound:true,count:2});preview.cancel();assert.deepEqual(settings,{theme:'notebook',sound:false,count:2});preview.begin();preview.update({theme:'candy'});preview.commit();preview.cancel();assert.equal(settings.theme,'candy');assert.equal(renders,3);
let seed=10;const random=()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/2**32);for(let count=2;count<=10;count++)for(let n=0;n<100;n++){const sizes=itemScales(count,random).sort((a,b)=>a-b);assert(sizes[0]>=.132&&sizes[0]<=.138);assert(sizes.at(-1)>=.2376&&sizes.at(-1)<=.2484);assert(Math.abs(sizes.at(-1)/sizes[0]-1.8)<1e-12);const step=sizes[1]-sizes[0];for(let i=1;i<count;i++)assert(Math.abs(sizes[i]-sizes[i-1]-step)<1e-12);}console.log('PASS: exact themed markers, 140ms fallback reveal, safe settings transaction, 900 smooth 1.8:1 size hierarchies.');
const {celebrate,clearCelebration,VICTORY_NOTES}=await import('../games/tic-tac-toe/celebration.js');
assert.equal(VICTORY_NOTES.length,6);assert.ok(Math.max(...VICTORY_NOTES.map(n=>n.at+n.duration))>=1.3);
globalThis.innerWidth=1366;globalThis.innerHeight=768;globalThis.requestAnimationFrame=()=>1;globalThis.cancelAnimationFrame=()=>{};
let reducedMotion=false,appends=0,removed=0;
globalThis.matchMedia=()=>({matches:reducedMotion});
globalThis.document={createElement:()=>({dataset:{},style:{setProperty(){}},setAttribute(){},append(){},remove(){removed++}}),body:{append(){appends++}}};
celebrate(false);assert.equal(appends,1);clearCelebration();clearCelebration();assert.equal(removed,1);
reducedMotion=true;celebrate(false);assert.equal(appends,1);
console.log('PASS victory notes, one-shot cleanup and reduced-motion suppression');
