import {setRepository} from '../shared/sets.js';
import {loadSettings,saveSettings} from '../shared/storage.js';
const frame=document.querySelector('#frame'),out=document.querySelector('#result');
const wait=async fn=>{for(let i=0;i<150;i++){if(fn())return;await new Promise(r=>setTimeout(r,100));}throw Error('Timed out');};
const assert=(v,m)=>{if(!v)throw Error(m);};
document.querySelector('#run').onclick=async()=>{let fixture;const saved=loadSettings();out.textContent='';try{
fixture=await setRepository.create({name:'Temporary pre-game check',items:Array.from({length:5},(_,i)=>({id:'test-'+i,word:'word'+i,image:{type:'emoji',value:'🐱'}}))});
frame.src='../sets/';await wait(()=>frame.contentDocument?.querySelector('article[aria-label="Temporary pre-game check"]'));const doc=frame.contentDocument;doc.querySelector('article[aria-label="Temporary pre-game check"] button').click();await wait(()=>doc.querySelector('dialog[open]'));let dialog=doc.querySelector('dialog'),buttons=[...dialog.querySelectorAll('.choice-row button')];assert(buttons.length===20,'All supported controls stay visible');
const click=(key,value)=>dialog.querySelector('[data-key="'+key+'"][data-value="'+value+'"]').click();
click('mode','images');click('count',2);click('per',3);click('count',4);assert(dialog.querySelector('[data-key="per"][aria-pressed="true"]').dataset.value==='2','Reduce invalid item count');assert(dialog.querySelector('[data-key="per"][data-value="10"]').disabled,'Ten stays visible disabled');click('mode','mixed');assert(dialog.querySelector('[data-key="count"][data-value="4"]').disabled,'Mixed disables four cards');assert(buttons.every(b=>b.isConnected),'Options were not replaced');assert(dialog.scrollWidth<=dialog.clientWidth,'No horizontal overflow at 390px');out.textContent+='PASS: stable options, adaptive values, mixed restrictions, 390px layout\n';
[...dialog.querySelectorAll('button')].find(b=>b.textContent==='Cancel').click();assert(JSON.stringify(loadSettings())===JSON.stringify(saved),'Cancel changed stored settings');out.textContent+='PASS: Cancel preserves settings\n';doc.querySelector('article[aria-label="Temporary pre-game check"] button').click();dialog=doc.querySelector('dialog');click('mode','words');click('count',4);click('movement','medium');[...dialog.querySelectorAll('button')].find(b=>b.textContent==='Play').click();await wait(()=>frame.contentDocument?.querySelectorAll('#game .card').length===4);const params=new URL(frame.contentWindow.location.href).searchParams;assert(params.get('set')===fixture.id&&params.get('mode')==='words'&&params.get('count')==='4'&&params.get('per')==='2'&&params.get('movement')==='medium','Launch settings mismatch');out.textContent+='PASS: Play applies set and all selected settings\n';out.textContent+='ALL PRE-GAME CHECKS PASSED';
}catch(e){out.textContent+='FAIL: '+e.message;console.error(e);}finally{saveSettings(saved);if(fixture)await setRepository.delete(fixture.id);}};