import {setRepository,newId} from '../shared/sets.js';
import {folderRepository} from '../shared/folders.js';
const frame=document.querySelector('iframe'),out=document.querySelector('pre'),pause=ms=>new Promise(r=>setTimeout(r,ms)),check=(v,m)=>{if(!v)throw Error(m);};
async function wait(fn){for(let n=0;n<300;n++){if(fn())return;await pause(20);}throw Error('Timed out');}
document.querySelector('#run').onclick=async event=>{event.target.disabled=true;out.textContent='';let set,folder;const saved=new Map(Object.keys(localStorage).filter(k=>k.includes('settings')).map(k=>[k,localStorage.getItem(k)]));try{
 set=await setRepository.create({name:'__Unified setup '+newId(),items:['cat','bat','hat','rat','mat','cap'].map((word,i)=>({id:'setup-'+i,word,image:{type:'emoji',value:'🐱'}}))});folder=await folderRepository.create('__Setup folder');await folderRepository.move(set.id,folder.id);const before=JSON.stringify(await setRepository.get(set.id));
 for(const game of ['dobble','wordly','tic-tac-toe','story-dice']){
  frame.src='../games/'+game+'/?set='+set.id+'&theme=notebook&sound=false'+(game==='story-dice'?'&mode=concept':'');await new Promise(r=>frame.onload=r);const d=frame.contentDocument,$=s=>d.querySelector(s);await wait(()=>$('dialog.unified-setup[open] .setup-concept'));await wait(()=>$('[data-folder-id="'+folder.id+'"]'));const dialog=$('dialog.unified-setup[open]');
  const tab=name=>dialog.querySelector('[data-tab='+name+']').click();check(dialog.querySelectorAll('[role=tab]').length===3,'Wrong tabs');$('[data-folder-id="'+folder.id+'"]').click();check(dialog.querySelectorAll('.setup-set').length===1,'Folder filtering');
  const exclude=index=>{const input=dialog.querySelector('[data-concept-id="setup-'+index+'"] input');input.checked=!input.checked;input.dispatchEvent(new frame.contentWindow.Event('change',{bubbles:true}));};exclude(0);check(dialog.querySelectorAll('.excluded').length===1,'Missing exclusion feedback');tab('themes');$('[data-theme-option=space]').click();check(d.body.dataset.theme==='space','Theme preview');tab('gameplay');await pause(120);tab('content');check(!dialog.querySelector('[data-concept-id=setup-0] input').checked,'Tab reset exclusion');exclude(1);const play=[...dialog.querySelectorAll('button')].find(b=>b.textContent==='Play');check(play.disabled,'Below minimum still playable');exclude(1);check(!play.disabled,'Included concepts did not restore Play');check(JSON.stringify(await setRepository.get(set.id))===before,'Saved content changed');check(dialog.scrollWidth<=dialog.clientWidth&&play.getBoundingClientRect().bottom<=844,'Overflow/hidden Play');
  play.click();await wait(()=>!$('dialog.unified-setup[open]'));check(new URL(frame.contentWindow.location.href).searchParams.get('set')===set.id,'Set ID changed');out.textContent+='PASS '+game+': folders, temporary exclusions/minimum, tabs, instant themes, mobile layout, same set ID\n';
 }
 out.textContent+='ALL UNIFIED SETUP CHECKS PASSED';
}catch(error){out.textContent+='FAIL '+error.stack;console.error(error);}finally{frame.src='about:blank';if(set)await setRepository.delete(set.id);if(folder)await folderRepository.delete(folder.id);for(const key of Object.keys(localStorage).filter(k=>k.includes('settings')))if(!saved.has(key))localStorage.removeItem(key);for(const [key,value] of saved)localStorage.setItem(key,value);event.target.disabled=false;}};
