import {THEME_IDS} from '../shared/themes.js';
import {createWheelPicker} from '../shared/wheel-picker.js';
const f=document.querySelector('iframe'),out=document.querySelector('pre'),pause=ms=>new Promise(r=>setTimeout(r,ms));let d;const $=s=>d.querySelector(s),all=s=>[...d.querySelectorAll(s)],check=(v,m)=>{if(!v)throw Error(m)},wait=async fn=>{for(let i=0;i<250;i++){if(fn())return;await pause(20);}throw Error('Timeout');},pass=m=>out.textContent+='PASS '+m+'\n';
async function open(game){f.src='../games/'+game+'/?set=animals-1&theme=nature&sound=false&movement=off&mode='+(game==='story-dice'?'sentence':game==='dobble'?'images':'mixed');await new Promise(r=>f.onload=r);d=f.contentDocument;await wait(()=>$('dialog[open]'));}
function theme(value){const dialog=$('dialog[open]'),button=dialog.querySelector('[data-theme-option="'+value+'"],[data-key=theme][data-value="'+value+'"]');check(button,'Theme buttons missing');button.click();}
function action(text){const b=all('dialog[open] button').find(b=>b.textContent.trim()===text);check(b,'Missing '+text);b.click();}
function snapshot(game){if(game==='dobble')return all('.item').map(n=>n.textContent+'|'+n.style.cssText).join('/')+' score '+$('#score').textContent;if(game==='tic-tac-toe')return all('.cell').map(n=>n.dataset.player).join('/')+'|'+d.body.dataset.state;if(game==='wordly')return $('#grid').innerHTML+'|'+$('#attemptLabel').textContent+'|'+$('#hint').textContent;return all('.die').map(n=>n.dataset.id+'|'+n.querySelector('.die-label').textContent).join('/');}
document.querySelector('#run').onclick=async()=>{out.textContent='';const saved=new Map(Object.keys(localStorage).filter(k=>k.includes('settings')).map(k=>[k,localStorage.getItem(k)]));try{for(const game of ['dobble','tic-tac-toe','wordly','story-dice']){
 await open(game);await pause(120);const header=$('.game-header');check(header&&header.querySelector('h1').textContent.toLowerCase().replaceAll(' ','-').startsWith(game==='wordly'?'wordly':game),'Missing title '+game);check(getComputedStyle(header).backgroundColor==='rgba(0, 0, 0, 0)','Opaque header');theme('candy');check(d.body.dataset.theme==='candy','Setup preview '+game);action('Cancel');await pause(30);check(d.body.dataset.theme==='nature','Setup Cancel '+game);if(game==='dobble')$('#startSetup').click();else if(game==='story-dice')$('#modeOpen').click();else $('#setupOpen').click();await pause(80);theme('space');action('Play');await wait(()=>!$('dialog[open]'));await pause(200);check(d.body.dataset.theme==='space','Setup commit '+game);if(game==='wordly'){$('#grid').dispatchEvent(new f.contentWindow.KeyboardEvent('keydown',{key:'a',bubbles:true}));$('#hint').click();await pause(330);}if(game==='story-dice'){$('[data-category=subject]').click();await wait(()=>!$('.rolling'));}
 const before=snapshot(game);for(const value of THEME_IDS){$('#settingsOpen').click();await wait(()=>$('dialog[open]'));await pause(50);theme(value);check(d.body.dataset.theme===value,'Live preview '+game);check(getComputedStyle(header.querySelector('h1')).color===getComputedStyle(d.body).getPropertyValue('--game-title-color').trim()||getComputedStyle(header.querySelector('h1')).color!=='','Title theme');check(snapshot(game)===before,'Theme changed state '+game);action('Cancel');await wait(()=>d.body.dataset.theme==='space');check(d.body.dataset.theme==='space','Live cancel '+game);check(snapshot(game)===before,'Cancel changed state '+game);}
 $('#settingsOpen').click();await pause(60);theme('magic-school');const submit=$('dialog[open] [type=submit]')||all('dialog[open] button').find(b=>['Done','Apply settings'].includes(b.textContent.trim()));check(submit,'Commit button');submit.click();await pause(60);check(d.body.dataset.theme==='magic-school','Live commit');check(snapshot(game)===before,'Apply reset game '+game);check(getComputedStyle(d.body).getPropertyValue('--surface-glow').includes('C9A45C'),'No shared glow');pass(game+' setup/live preview, Cancel/commit, all themes, unchanged state, transparent header');
 }
 let selected;const picker=createWheelPicker({label:'Test picker',value:'b',options:[{value:'a',label:'A'},{value:'b',label:'B'},{value:'c',label:'C',disabled:true},{value:'d',label:'D'},{value:'e',label:'E'}],onChange:v=>selected=v});document.body.append(picker.element);picker.setValue('b');picker.element.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));check(selected==='d','Wheel failed to skip disabled');picker.element.dispatchEvent(new KeyboardEvent('keydown',{key:'Home',bubbles:true}));check(selected==='a','Wheel Home');picker.element.remove();pass('Reusable wheel keyboard navigation and disabled options');out.textContent+='ALL SHARED SYSTEM CHECKS PASSED\n';
 }catch(e){out.textContent+='FAIL '+e.stack;console.error(e);}finally{for(const [k,v] of saved)localStorage.setItem(k,v);}};
