import assert from 'node:assert/strict';
import {DiceTable,grammarOptions,TIMES,ASPECTS} from '../games/story-dice/engine.js';
import {storyItems,sentencePools,timePools} from '../games/story-dice/pools.js';
let seed=12;const random=()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/2**32);
assert(storyItems.length>=80);for(const pool of Object.values(timePools)){assert.equal(pool.length,25);assert.equal(new Set(pool.map(p=>p.label)).size,pool.length);}
for(const item of sentencePools.action)assert(/^[a-z]+$/.test(item.label));for(const item of sentencePools.where)assert(/^(at|in|on|under|next to|behind|in front of|near|beside|between|by|inside) /.test(item.label));
for(const time of [...TIMES,'All'])for(const aspect of [...ASPECTS,'All']){const options=grammarOptions(time,aspect),expected=TIMES.flatMap(t=>ASPECTS.filter(a=>(time==='All'||t===time)&&(aspect==='All'||a===aspect)).map(a=>t+' '+a));assert.deepEqual(options.map(o=>o.id),expected);const table=new DiceTable('sentence',[],random);table.setGrammar(time,aspect);for(let cycle=0;cycle<8;cycle++){const drawn=[];for(let i=0;i<options.length;i++){const die=table.add('time');assert.equal(typeof die.id,'number');drawn.push(die.tense+' '+die.aspect);assert(timePools[drawn.at(-1)].some(p=>p.label===die.label));table.remove(die.id);}assert.deepEqual(drawn.sort(),[...expected].sort());}}
const table=new DiceTable('story',[],random);assert.equal(table.dice.length,0);for(let i=0;i<10;i++)assert(table.add());assert.equal(new Set(table.dice.map(d=>d.conceptId)).size,10);assert.equal(table.add(),null);const before=JSON.stringify(table.dice.slice(1));assert.equal(table.reroll(1),null);table.settle(1);assert(table.reroll(1));assert.equal(JSON.stringify(table.dice.slice(1)),before);table.remove(1);assert(table.canAdd());table.clear();assert.equal(table.dice.length,0);
const concepts=storyItems.slice(0,5).map(p=>({id:p.id,word:p.label,image:{type:'emoji',value:p.emoji}})),original=JSON.stringify(concepts),concept=new DiceTable('concept',concepts,random);for(let cycle=0;cycle<10;cycle++){const ids=[];for(let i=0;i<5;i++){const die=concept.add();ids.push(die.conceptId);assert.equal(die.label,concepts.find(p=>p.id===die.conceptId).word);concept.remove(die.id);}assert.equal(new Set(ids).size,5);}assert.equal(JSON.stringify(concepts),original);
const sentence=new DiceTable('sentence',[],random);for(const c of [...Object.keys(sentencePools),'time']){for(let i=0;i<3;i++)assert(sentence.add(c));assert.equal(sentence.add(c),null);}assert.equal(sentence.dice.length,18);const old=JSON.stringify(sentence.dice);sentence.setGrammar('Past','Continuous');assert.equal(JSON.stringify(sentence.dice),old);const timeDie=sentence.dice.find(d=>d.category==='time');sentence.settle(timeDie.id);sentence.reroll(timeDie.id);assert.equal(timeDie.tense,'Past');assert.equal(timeDie.aspect,'Continuous');sentence.remove(sentence.dice[0].id);assert(sentence.canAdd('subject'));sentence.clear();assert.equal(sentence.time,'Past');assert.equal(sentence.aspect,'Continuous');
const expressions=new DiceTable('sentence',[],random);const labels=[];for(let i=0;i<25;i++){const die=expressions.add('time');labels.push(die.label);expressions.remove(die.id);}assert.equal(new Set(labels).size,25);
console.log('PASS Story Dice: 16 grammar combinations, balanced grammar/expression bags, 225 prompts, story/concept limits, 18 sentence dice, isolated reroll/remove, current grammar, Clear preservation, immutable content.');
