import {setRepository,newId} from '../shared/sets.js';import {exportSet} from '../shared/transfer.js';
const f=document.querySelector('iframe'),out=document.querySelector('pre'),pause=ms=>new Promise(r=>setTimeout(r,ms)),owned=[];let d,audioCalls=0;const check=(v,m)=>{if(!v)throw Error(m);};const wait=async fn=>{for(let i=0;i<160;i++){if(fn())return;await pause(30);}throw Error('Timed out');};const pass=m=>out.textContent+='PASS '+m+'\n';
async function open(id,sound=false){f.src='../games/tic-tac-toe/?set='+id+'&sound='+sound;await new Promise(r=>f.onload=r);d=f.contentDocument;await wait(()=>d.querySelector('#setup').open||!d.querySelector('#missing').hidden);f.contentWindow.AudioContext=class{constructor(){audioCalls++;throw Error('Test audio spy');}};}
async function play(){d.querySelector('#play').click();await wait(()=>!d.querySelector('#playArea').hidden);}
const active=()=>d.querySelector('.player.active')?.dataset.player;const cells=()=>[...d.querySelectorAll('.cell')];async function choose(i){cells()[i].click();await wait(()=>d.querySelector('#task').open&&!d.querySelector('#correct').disabled);return d.querySelector('#task').dataset.concept;}
async function answer(yes){d.querySelector(yes?'#correct':'#incorrect').click();await pause(1750);}async function move(i){await choose(i);await answer(true);}async function upload(set){const dt=new f.contentWindow.DataTransfer();dt.items.add(new f.contentWindow.File([await exportSet(set)],'test.json',{type:'application/json'}));d.querySelector('#importFile').files=dt.files;d.querySelector('#importFile').dispatchEvent(new f.contentWindow.Event('change'));}
document.querySelector('#run').onclick=async()=>{out.textContent='';const saved=localStorage.getItem('sunny-stacy.tictactoe.settings.v1');try{const base=await setRepository.get('animals-1');await open('animals-1');await play();const start=active();for(const i of [3,0,4,1])await move(i);await choose(2);await answer(false);const thief=active();await answer(true);check(d.body.dataset.state==='WIN'&&d.querySelector('#resultText').textContent.includes(thief==='X'?(d.querySelector('#nameX').value||'Player X'):(d.querySelector('#nameO').value||'Player O')),'Steal did not win');check(audioCalls===0,'Sound OFF invoked audio');pass('Steal completes win; Sound OFF invokes no audio');
await open('animals-1',true);await play();await move(0);check(audioCalls>0,'Sound ON did not invoke shared audio');pass('Sound ON routes to existing feedback');
const canvas=document.createElement('canvas');canvas.width=80;canvas.height=50;canvas.getContext('2d').fillRect(0,0,80,50);const blob=await new Promise(r=>canvas.toBlob(r));const uploaded=await setRepository.create({name:'__TTT upload',items:base.items.slice(0,5).map(i=>({...i,id:newId(),image:{type:'upload',blob}}))});owned.push(uploaded.id);await open(uploaded.id);await play();await choose(0);await wait(()=>d.querySelector('#taskImage img')?.naturalWidth===80);pass('Uploaded image loads from shared Blob repository');
const exact='ttt-import-'+newId();await open(exact);await upload({...base,id:exact});owned.push(exact);await wait(()=>d.querySelector('#setup').open);check(new URL(f.contentWindow.location.href).searchParams.get('set')===exact,'Matching import changed ID');pass('Matching JSON preserves requested ID');
const missing='ttt-missing-'+newId(),different='ttt-other-'+newId();await open(missing);await upload({...base,id:different});owned.push(different);await wait(()=>!d.querySelector('#useImported').hidden);check(new URL(f.contentWindow.location.href).searchParams.get('set')===missing&&!d.querySelector('#setup').open,'Different import silently replaced set');d.querySelector('#useImported').click();await wait(()=>d.querySelector('#setup').open);check(new URL(f.contentWindow.location.href).searchParams.get('set')===different,'Explicit imported replacement');pass('Different JSON waits for explicit choice');
await open('animals-1');await play();const starter=active(),sequence=[];for(const i of [0,3,1,4,2]){sequence.push(await choose(i));await answer(true);}await pause(1100);d.querySelector('#again').click();sequence.push(await choose(0));check(new Set(sequence).size===6,'Bag restarted on Play Again');check(active()!==starter,'Starter did not alternate');pass('Content bag continues across rounds');
out.textContent+='ALL TICTACTOE INTEGRATION CHECKS PASSED';}catch(e){out.textContent+='FAIL: '+e.message;console.error(e);}finally{f.src='about:blank';for(const id of owned)await setRepository.delete(id);if(saved===null)localStorage.removeItem('sunny-stacy.tictactoe.settings.v1');else localStorage.setItem('sunny-stacy.tictactoe.settings.v1',saved);}};
