import assert from 'node:assert/strict';import {TicTacToe,ConceptBag,LINES,outcome} from '../games/tic-tac-toe/engine.js';import {MARKERS,marker} from '../games/tic-tac-toe/markers.js';
const items=Array.from({length:5},(_,i)=>({id:String(i),word:'Exact task '+i}));const create=()=>new TicTacToe(items,()=>.1);const answer=(g,yes)=>g.answer(yes,g.attempt);const move=(g,i)=>{assert(g.choose(i));answer(g,true);g.finish();};
let g=create();assert.equal(g.current,'X');assert(g.choose(0));const a=g.concept.id,token=g.attempt;assert(!g.choose(1));assert.equal(answer(g,false),'steal');assert.equal(g.pending,0);assert.equal(g.current,'O');assert.notEqual(g.concept.id,a);assert.equal(g.answer(false,token),false);answer(g,true);assert.equal(g.board[0],'O');assert.equal(answer(g,true),false);g.finish();assert.equal(g.current,'X');const used=g.bag.consumed;assert(!g.choose(0));assert.equal(g.bag.consumed,used);
g=create();g.choose(4);answer(g,false);answer(g,false);g.finish();assert.equal(g.board[4],null);assert.equal(g.current,'X');assert(g.choose(4));
for(const line of LINES)for(const p of ['X','O']){const board=Array(9).fill(null);line.forEach(i=>board[i]=p);assert.deepEqual(outcome(board),{winner:p,line});}
g=create();for(const i of [0,3,1,4,2])move(g,i);assert.equal(g.state,'WIN');assert.equal(g.result.winner,'X');const bag=g.bag,consumed=bag.consumed;assert(g.playAgain());assert.equal(g.starter,'O');assert.equal(g.bag,bag);assert.equal(g.bag.consumed,consumed);assert(g.board.every(x=>x===null));for(const i of [0,3,1,4,2])move(g,i);assert(g.playAgain());assert.equal(g.starter,'X');
g=create();for(const i of [3,0,4,1])move(g,i);g.choose(2);answer(g,false);answer(g,true);g.finish();assert.equal(g.state,'WIN');assert.equal(g.result.winner,'O');
g=create();for(const i of [0,1,2,4,3,5,7,6,8])move(g,i);assert.equal(g.state,'DRAW');assert.equal(g.result.draw,true);assert(!g.choose(8));
for(let seed=1;seed<=100;seed++){let state=seed;const random=()=>((state=Math.imul(state,1664525)+1013904223>>>0)/2**32);const b=new ConceptBag(items,random);let previous;for(let round=0;round<20;round++){const ids=Array.from({length:5},()=>b.next().id);assert.equal(new Set(ids).size,5);assert.notEqual(ids[0],previous);previous=ids[4];}}
assert.equal(new TicTacToe(items,()=>.9).starter,'O');assert.equal(Object.keys(MARKERS).length,8);for(const t of Object.keys(MARKERS)){assert(marker(t,'X'));assert.notEqual(marker(t,'X'),marker(t,'O'));}console.log('PASS: Tic-Tac-Toe normal/steal/failed steal/index 0/double answer/8 wins/steal win/draw/starter alternation and 10000 bag draws.');
