import {setRepository,newId} from '../shared/sets.js';import {THEME_IDS} from '../shared/themes.js';import {MARKERS} from '../games/tic-tac-toe/markers.js';import {exportSet} from '../shared/transfer.js';
const frame=document.querySelector('iframe'),out=document.querySelector('#result'),pause=ms=>new Promise(r=>setTimeout(r,ms));const wait=async(fn,label='condition')=>{for(let i=0;i<160;i++){if(fn())return;await pause(30);}throw Error('Timed out '+label);};const check=(v,m)=>{if(!v)throw Error(m);};const pass=m=>out.textContent+='PASS '+m+'\n';let doc;const cells=()=>[...doc.querySelectorAll('.cell')],active=()=>doc.querySelector('.player.active')?.dataset.player;
async function open(set,theme='notebook',w=1366,h=768){frame.style.width=w+'px';frame.style.height=h+'px';frame.src='../games/tic-tac-toe/?set='+set+'&theme='+theme+'&sound=false';await new Promise(r=>frame.onload=r);doc=frame.contentDocument;await wait(()=>doc.querySelector('#setup[open]')||!doc.querySelector('#missing').hidden);}
async function play(){doc.querySelector('#play').click();await wait(()=>!doc.querySelector('#playArea').hidden);await pause(80);}
async function choose(i){cells()[i].click();await wait(()=>doc.querySelector('#task').open&&!doc.querySelector('#correct').disabled);}
async function answer(correct){doc.querySelector(correct?'#correct':'#incorrect').click();await pause(700);}
async function move(i){await choose(i);await answer(true);}
function fits(w,h){check(doc.documentElement.scrollWidth<=w,'horizontal overflow');const b=doc.querySelector('#board').getBoundingClientRect();check(b.left>=0&&b.right<=w&&b.top>=0&&b.bottom<=h,'board clipped '+w+' '+h);check(Math.abs(b.width-b.height)<1,'board not square');for(const c of cells()){const r=c.getBoundingClientRect();check(Math.abs(r.width-r.height)<1,'cell not square');}if(doc.querySelector('#task').open){for(const id of ['task','correct','incorrect']){const r=doc.querySelector('#'+id).getBoundingClientRect();check(r.top>=0&&r.bottom<=h&&r.left>=0&&r.right<=w,'modal controls clipped '+id+' '+w+'x'+h);}check(doc.querySelector('#taskText').scrollWidth<=doc.querySelector('#taskText').clientWidth+1,'text overflow');}}
document.querySelector('#run').onclick=async()=>{out.textContent='';const saved=localStorage.getItem('sunny-stacy.tictactoe.settings.v1'),owned=[];try{const base=await setRepository.get('animals-1'),long='What can you see in this picture? Tell your partner a complete sentence and ask them a question about it.';const fixture=await setRepository.create({name:'__TTT acceptance',items:base.items.slice(0,5).map(i=>({...i,id:newId(),word:long}))});owned.push(fixture.id);
for(const [w,h] of [[390,844],[412,915],[844,390],[915,412],[820,1180],[1024,768],[1366,768],[1920,1080]]){await open(fixture.id,'notebook',w,h);await play();fits(w,h);await choose(4);fits(w,h);check(doc.querySelector('#taskText').textContent===long,'text not faithful');check(getComputedStyle(doc.querySelector('#task')).opacity==='1','transparent task');check(cells().every(c=>c.disabled),'background not locked');const first=doc.querySelector('#task').dataset.concept,player=active();doc.querySelector('#incorrect').click();doc.querySelector('#incorrect').click();await pause(700);check(doc.body.dataset.state==='STEAL_TASK','double incorrect resolved steal');check(active()!==player,'steal player');check(cells()[4].classList.contains('pending'),'pending lost');check(doc.querySelector('#task').dataset.concept!==first,'same steal task');const thief=active();doc.querySelector('#correct').click();doc.querySelector('#correct').click();await pause(400);check(cells()[4].dataset.player===thief&&active()===player,'steal turn rule');const concept=doc.querySelector('#task').dataset.concept;cells()[4].click();check(!doc.querySelector('#task').open&&doc.querySelector('#task').dataset.concept===concept,'occupied consumed');await choose(0);await answer(false);await answer(false);check(!cells()[0].dataset.player&&active()===player,'failed steal');pass(w+'×'+h+' board/modal/long text/double taps/steal/occupied');}
for(const theme of THEME_IDS){await open(fixture.id,theme);await play();check([...doc.querySelectorAll('.player-marker')].map(e=>e.textContent).join('|')===MARKERS[theme].join('|'),'theme markers '+theme);const start=active();await move(0);const before=cells().map(c=>c.dataset.player).join('|'),current=active();doc.querySelector('#name'+start).value='Renamed learner';doc.querySelector('#name'+start).dispatchEvent(new frame.contentWindow.Event('input',{bubbles:true}));check(cells().map(c=>c.dataset.player).join('|')===before&&active()===current,'name reset');for(const i of [3,1,4,2])await move(i);await wait(()=>doc.body.dataset.state==='WIN');check(doc.querySelector('#resultText').textContent.includes('Renamed learner'),'winner name');check(!doc.querySelector('#winLine').hasAttribute('hidden'),'line hidden');check(cells().filter(c=>c.classList.contains('winner')).length===3,'winning markers');await pause(500);doc.querySelector('#again').click();check(active()!==start&&cells().every(c=>!c.dataset.player),'starter alternation');check(doc.querySelector('#name'+start).value==='Renamed learner','name lost');pass(theme+' markers, winner, name edit, Play Again');}
for(const [sequence,label] of [[[0,1,3,2,6],'column'],[[0,1,4,2,8],'diagonal'],[[2,0,4,1,6],'anti-diagonal'],[[0,1,2,4,3,5,7,6,8],'draw']]){await open(fixture.id);await play();for(const i of sequence)await move(i);check(doc.body.dataset.state===(label==='draw'?'DRAW':'WIN'),label+' outcome');if(label==='draw')check(doc.querySelector('#winLine').hasAttribute('hidden'),'draw line');fits(1366,768);pass(label+' UI/end layout');}
await open('ttt-missing-'+newId());check(doc.querySelector('#missing').hidden===false&&!doc.querySelector('#setup').open,'missing silently replaced');doc.querySelector('#replacement').value=fixture.id;doc.querySelector('#useReplacement').click();await wait(()=>doc.querySelector('#setup').open);check(new URL(frame.contentWindow.location.href).searchParams.get('set')===fixture.id,'explicit replacement');pass('missing exact ID and explicit replacement');
await open(fixture.id);await play();const nodes=cells(),before=nodes.map(c=>c.getBoundingClientRect().toJSON());doc.querySelector('.drawer-handle').focus();await pause(300);check(cells().every((c,i)=>c===nodes[i]&&JSON.stringify(c.getBoundingClientRect().toJSON())===JSON.stringify(before[i])),'drawer reflow');pass('shared drawer preserves board');
out.textContent+='ALL TIC-TAC-TOE CHECKS PASSED';}catch(e){out.textContent+='FAIL: '+e.message;console.error(e);}finally{frame.src='about:blank';for(const id of owned)await setRepository.delete(id);if(saved===null)localStorage.removeItem('sunny-stacy.tictactoe.settings.v1');else localStorage.setItem('sunny-stacy.tictactoe.settings.v1',saved);}};
