import {setRepository,newId} from '../shared/sets.js';
const output=document.querySelector('#result'),frames=document.querySelector('#frames');
const matrix=[[1366,768],[1440,900],[1920,1080],[1366,620],[1024,768],[820,1180],[390,844],[412,915],[844,390],[915,412]];
const wait=async(test)=>{for(let i=0;i<120;i++){if(test())return;await new Promise(r=>setTimeout(r,25));}throw Error('Timed out waiting for game');};
function assert(test,label){if(!test)throw Error(label);}
function select(doc,name,value){const el=doc.querySelector('[name="'+name+'"]');el.value=String(value);el.dispatchEvent(new doc.defaultView.Event('change',{bubbles:true}));}
async function openFrame(id,width,height){const frame=document.createElement('iframe');frame.title='Game '+width+'×'+height;frame.width=width;frame.height=height;frame.style.border='0';frame.allowFullscreen=true;const loaded=new Promise(resolve=>frame.onload=resolve);frame.src='../games/dobble/?set='+id;frames.replaceChildren(frame);await loaded;await wait(()=>frame.contentDocument.querySelectorAll('.item').length>0);return frame;}
async function configure(doc,count,mode,per){doc.querySelector('#settingsOpen').click();select(doc,'mode',mode);select(doc,'count',count);select(doc,'per',per);select(doc,'movement','fast');doc.querySelector('[name=autoNext]').checked=false;doc.querySelector('#settingsForm').requestSubmit();await wait(()=>!doc.querySelector('#settingsDialog').open&&doc.querySelectorAll('.card').length===count&&doc.querySelector('.card')?.children.length===per);await new Promise(r=>setTimeout(r,70));}
function bounds(doc){for(const card of doc.querySelectorAll('.card')){const box=card.getBoundingClientRect(),border=parseFloat(getComputedStyle(card).borderLeftWidth),radius=card.clientWidth/2,cx=box.left+border+radius,cy=box.top+border+radius;const rects=[...card.querySelectorAll('.item')].map(el=>el.getBoundingClientRect());for(let i=0;i<rects.length;i++){const a=rects[i];assert(Math.hypot(Math.max(Math.abs(a.left-cx),Math.abs(a.right-cx)),Math.max(Math.abs(a.top-cy),Math.abs(a.bottom-cy)))<=radius+.1,'item outside circle');for(const b of rects.slice(i+1))assert(!(Math.min(a.right,b.right)-Math.max(a.left,b.left)>.1&&Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top)>.1),'overlap');}for(const el of card.querySelectorAll('.item')){assert(Math.max(el.clientWidth,el.clientHeight)<=card.clientWidth*.205+1,'size exceeds 20%');}const scales=[...card.children].map(el=>+el.dataset.scale);if(scales.length>1)assert(Math.max(...scales)-Math.min(...scales)>=.179,'uniform sizes');}}
document.querySelector('#run').onclick=async()=>{const created=[],saved=localStorage.getItem('sunny-stacy.dobble.settings.v1');output.textContent='';document.querySelector('#run').disabled=true;try{const demo=await setRepository.get('animals-1');const make=async(size)=>{const set=await setRepository.create({name:'__Stage22 viewport '+size,imageSource:'emoji',items:Array.from({length:size},(_,i)=>({...demo.items[i%13],id:newId()}))});created.push(set.id);return set;};const large=await make(40);
for(const [width,height] of matrix){const frame=await openFrame(large.id,width,height),doc=frame.contentDocument;for(const count of [1,2])for(const mode of ['images','words','mixed']){await configure(doc,count,mode,10);bounds(doc);assert(doc.documentElement.scrollWidth<=width,'horizontal overflow');const desktop=width>=1024&&height>=600;assert(!desktop||doc.documentElement.scrollHeight<=height,'desktop vertical overflow');if(count===1){const cue=doc.querySelector('#cue .cue-content'),target=[...doc.querySelectorAll('.item')].find(el=>el.getAttribute('aria-label')===(cue.querySelector('img')?.alt||cue.textContent))||null;assert(!doc.querySelector('#cue').hidden,'cue missing');}output.textContent+='PASS: '+width+'×'+height+' '+count+' card(s) '+mode+'; page '+doc.documentElement.scrollHeight+'px\n';}}
for(const size of [5,6,7,9,13,19]){const set=await make(size),frame=await openFrame(set.id,1366,768),doc=frame.contentDocument;doc.querySelector('#settingsOpen').click();select(doc,'mode','images');for(const count of [1,2,3,4]){select(doc,'count',count);const maximum=Math.min(10,Math.floor((size-1)/count)+1);const options=[...doc.querySelector('[name=per]').options];assert(options.every(o=>o.disabled===(+o.value>maximum)),'wrong disabled options');assert(+doc.querySelector('[name=per]').value<=maximum,'selection not clamped');}select(doc,'count',2);doc.querySelector('#settingsForm').requestSubmit();await wait(()=>doc.querySelectorAll('.card').length===2);assert(!doc.querySelector('#loadError').textContent,'small set launch error');output.textContent+='PASS: '+size+' concepts — adaptive options for 1–4 cards, playable\n';}
const frame=await openFrame(large.id,1440,900),doc=frame.contentDocument;await configure(doc,2,'mixed',10);const cards=[...doc.querySelectorAll('.card')];const target=[...cards[0].children].find(el=>[...cards[1].children].some(other=>el.dataset.id===other.dataset.id));target.click();await wait(()=>doc.querySelector('#score').textContent==='1');doc.querySelector('#newRound').click();const signature=()=>[...doc.querySelectorAll('.item')].map(el=>el.dataset.id+':'+el.dataset.scale).join('|');const before=signature();for(const [width,height] of [[390,844],[915,412],[1920,1080]]){frame.width=width;frame.height=height;await new Promise(r=>setTimeout(r,150));bounds(doc);assert(signature()===before,'resize changed cards or random scales');assert(doc.querySelector('#score').textContent==='1','resize reset score');}output.textContent+='PASS: resize keeps current cards, answer, score and sampled scales\nALL VIEWPORT CHECKS PASSED\n';}catch(error){output.textContent+='FAIL: '+error.message;console.error(error);}finally{for(const id of created)await setRepository.delete(id);if(saved===null)localStorage.removeItem('sunny-stacy.dobble.settings.v1');else localStorage.setItem('sunny-stacy.dobble.settings.v1',saved);document.querySelector('#run').disabled=false;}};
