import assert from 'node:assert/strict';
import {WordlyRound,evaluateLetters,medalFor,successCopy,createBag} from '../games/wordly/engine.js';
import {eligibleWord,eligiblePool} from '../games/wordly/eligibility.js';
const item=word=>({id:word,word,image:{type:'emoji',value:'🐱'}}),C='correct',Y='present',R='absent';
for(const word of ['cat','DOG','fish','rabbit','elephant'])assert(eligibleWord(word));for(const word of ['polar bear','ice-cream','I like cats','cat!','123',' cat','cat ','élephant','ab','abcdefghi'])assert(!eligibleWord(word));
const set={items:['cat','DOG','fish','rabbit','elephant','polar bear','cat!'].map(item)},before=JSON.stringify(set);assert.equal(eligiblePool(set).length,5);assert.equal(eligiblePool(set,3).length,2);assert.equal(eligiblePool(set,5).length,0);assert.equal(JSON.stringify(set),before);
assert.deepEqual(evaluateLetters('CAT','CTE'),[C,Y,R]);assert.deepEqual(evaluateLetters('APPLE','PAPAL'),[Y,Y,C,R,Y]);assert.deepEqual(evaluateLetters('LEVEL','LLEEE'),[C,Y,Y,C,R]);assert.deepEqual(evaluateLetters('APPLE','AAXXX',['A',null,null,null,null]),[C,R,R,R,R]);assert.deepEqual(evaluateLetters('EERIE','EEEEE'),[C,C,R,R,C]);
let seed=4;const random=()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/2**32);for(let n=0;n<10000;n++){const length=3+Math.floor(random()*6),answer=Array.from({length},()=> 'ABC'[Math.floor(random()*3)]).join(''),guess=Array.from({length},()=> 'ABC'[Math.floor(random()*3)]).join(''),feedback=evaluateLetters(answer,guess);for(const letter of 'ABC')assert(feedback.filter((v,i)=>v!==R&&guess[i]===letter).length<=answer.split(letter).length-1);}
let g=new WordlyRound(item('cat'));assert(g.submit().incomplete);assert.equal(g.submitted,0);for(const l of 'cte')assert(g.type(l));g.submit();assert.equal(g.submit(),false);assert.equal(g.type('A'),false);g.finishFeedback();assert.deepEqual(g.current,['C','','']);assert.equal(g.backspace(),false);for(const l of 'AR')g.type(l);g.submit();g.finishFeedback();assert.deepEqual(g.current,['C','A','']);assert.equal(g.backspace(),false);g.type('T');g.submit();g.finishFeedback();assert.equal(g.state,'SUCCESS');assert.equal(medalFor(g.submitted,3),'');assert.equal(g.hint(),false);
g=new WordlyRound(item('ELEPHANT'));g.type('Z');g.type('Z');g.type('Z');g.hint(()=>1/8+.001);assert.deepEqual(g.current.slice(0,3),['Z','L','Z']);assert.equal(g.submitted,0);g.backspace();assert.equal(g.current[1],'L');for(let i=0;i<2;i++)g.hint(()=>0);assert.equal(g.hinted.size,3);assert.equal(g.hint(),false);assert.equal(g.submitted,0);assert.equal(g.state,'INPUT');
g=new WordlyRound(item('cat'));for(let row=0;row<3;row++){for(const l of 'ZZZ')g.type(l);g.submit();g.finishFeedback();}assert.equal(g.state,'FAILURE');assert.equal(g.submitted,3);assert.equal(g.backspace(),false);
for(const max of [3,4,5,8])for(let n=1;n<=max;n++)assert.equal(medalFor(n,max),n===max?'':n===1?'🥇':n===2?'🥈':n===3?'🥉':'🏅');assert(successCopy(5).includes('5 tries'));assert(successCopy(1).includes('first try'));
const pool=['cat','dog','fish','bird','rabbit'].map(item),bag=createBag(pool,random);let last;for(let cycle=0;cycle<100;cycle++){const words=Array.from({length:5},()=>bag.next().id);assert.equal(new Set(words).size,5);assert.notEqual(words[0],last);last=words.at(-1);}const single=createBag([item('cat')]);assert.equal(single.next().word,'cat');assert.equal(single.next().word,'cat');assert.equal(single.consumed,2);assert.throws(()=>createBag([]));
const old=new WordlyRound(bag.next());old.hint();const next=new WordlyRound(bag.next());assert.equal(next.submitted,0);assert.equal(next.hinted.size,0);assert(next.locked.every(v=>!v));assert.equal(next.rows.length,0);assert.equal(next.state,'INPUT');
console.log('PASS Wordly eligibility, 10000 duplicate-count cases, locked-green exclusion/propagation/input/backspace, hints/current row/all-hints success, every medal boundary, failure, shuffled bag and clean round reset.');

for(const word of ['cat','lion','tiger','rabbit','dolphin','elephant']){const round=new WordlyRound(item(word));assert.equal(round.maxAttempts,Math.min(word.length,5));for(const c of word)round.type(c);assert.equal(round.current.join(''),word.toUpperCase());round.submit();round.finishFeedback();assert.equal(round.state,'SUCCESS');}for(const word of ['CAT','Cat','cat','cAt','CaT'])assert.deepEqual(evaluateLetters(word,'cAt'),[C,C,C]);

for(const [word,max] of [['cat',1],['lion',1],['tiger',2],['rabbit',2],['dolphin',3],['elephant',3]]){const r=new WordlyRound(item(word));assert.equal(r.maxHints,max);for(let i=0;i<max;i++)r.hint(()=>0);assert.equal(r.hint(),false);assert.equal(r.submitted,0);assert.equal(r.state,'INPUT');}
const assisted=new WordlyRound(item('cat'));for(const c of 'CAZ')assisted.type(c);assisted.submit();assisted.finishFeedback();assisted.hint();assert.equal(assisted.submitted,1);assert(assisted.solvedWithHint);assert.equal(assisted.rows.length,1);assert(successCopy(assisted.submitted,true).includes('1 submitted guess'));assert(!successCopy(assisted.submitted,true).includes('first'));

const later=new WordlyRound(item('cat'));for(const c of 'ZZZ')later.type(c);later.submit();later.finishFeedback();later.hint(()=>0);assert.equal(later.submitted,1);assert.equal(later.hint(),false);for(const c of 'AT')later.type(c);later.submit();later.finishFeedback();assert.equal(later.submitted,2);assert(successCopy(later.submitted).includes('second'));assert.equal(later.hinted.size,1);
