import {setRepository,newId} from '../shared/sets.js';import {THEME_IDS} from '../shared/themes.js';
const f=document.querySelector('iframe'),out=document.querySelector('pre'),pause=ms=>new Promise(r=>setTimeout(r,ms)),owned=[];let d,audio=0,bursts=0;const $=s=>d.querySelector(s),all=s=>[...d.querySelectorAll(s)],check=(v,m)=>{if(!v)throw Error(m)},wait=async(fn,m='state')=>{for(let i=0;i<250;i++){if(fn())return;await pause(20)}throw Error('Timeout '+m)},pass=m=>out.textContent+='PASS '+m+'\n';
const key=(value,extra={})=>$('#grid').dispatchEvent(new f.contentWindow.KeyboardEvent('keydown',{key:value,bubbles:true,cancelable:true,...extra}));const rowLetters=(r)=>[...all('.letter-row')[r].children].map(e=>e.firstChild?.nodeType===3?e.firstChild.textContent:'').join('');const active=()=>$('.letter-row.active');
async function open(id,length='any',w=1366,h=768,sound=false){f.style.width=w+'px';f.style.height=h+'px';f.src='../games/wordly/?set='+id+'&length='+length+'&theme=notebook&sound='+sound;await new Promise(r=>f.onload=r);d=f.contentDocument;await wait(()=>$('#setup')?.open);audio=0;bursts=0;f.contentWindow.Audio=class{currentTime=0;volume=1;constructor(src){this.src=src;}play(){audio++;return Promise.resolve();}pause(){}};f.contentWindow.AudioContext=class{currentTime=0;destination={};resume(){return Promise.resolve()}createOscillator(){return {frequency:{value:0,setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){},start(){audio++},stop(){},disconnect(){}}}createGain(){return {gain:{setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){},disconnect(){}}}};new f.contentWindow.MutationObserver(records=>{for(const r of records)for(const n of r.addedNodes)if(n.classList?.contains('victory-confetti'))bursts++}).observe(d.body,{childList:true});}
async function play(){check(!$('#play').disabled,'Play disabled');$('#play').click();await wait(()=>d.body.dataset.state==='INPUT');await pause(60);}
async function submit(word){for(const l of word)key(l);key('Enter');await wait(()=>d.body.dataset.state!=='EVALUATING');await pause(20);}
function fits(w,h){check(d.documentElement.scrollWidth<=w,'Horizontal overflow '+w);for(const id of ['clue','hint','submit','keyboardToggle']){const r=$('#'+id).getBoundingClientRect();check(r.x>=0&&r.y>=0&&r.right<=w+1&&r.bottom<=h+1,'Clipped '+id+' '+w+'x'+h);}const a=active();if(a){const r=a.getBoundingClientRect(),v=$('#gridViewport').getBoundingClientRect();check(r.left>=v.left-1&&r.right<=v.right+1&&r.top>=v.top-1&&r.bottom<=v.bottom+1,'Active row hidden '+w+'x'+h);}if(!$('#keyboard').hidden){const r=$('#keyboard').getBoundingClientRect();check(r.bottom<=h+1,'Keyboard clipped');if(a)check(a.getBoundingClientRect().bottom<=r.top,'Keyboard covers row');}if($('#result').open){const r=$('#result').getBoundingClientRect();check(r.left>=0&&r.right<=w+1&&r.top>=0&&r.bottom<=h+1,'Result clipped');}}
async function fixture(name,words,image={type:'emoji',value:'🐱'}){const set=await setRepository.create({name,items:words.map(word=>({id:newId(),word,image}))});owned.push(set.id);return set;}
document.querySelector('#run').onclick=async()=>{out.textContent='';const pref='sunny-stacy.wordly.settings.v1',saved=localStorage.getItem(pref);try{const tail=['polar bear','ice-cream','I see a cat','abcdefghi'],cat=await fixture('__Wordly cat',['cat',...tail]),long=await fixture('__Wordly elephant',['elephant',...tail]),none=await fixture('__Wordly incompatible',[...tail,'two words']);
await open(cat.id);check(all('#lengthOptions button').length===7,'Length controls hidden');check(all('#lengthOptions button').filter(b=>!b.disabled).length===2,'Disabled lengths');await play();check($('#keyboard').hidden,'Keyboard initially visible');check(!d.body.innerText.includes('CAT')&&!$('#clue').getAttribute('aria-label').includes('cat'),'Answer leak');key('Enter');check(d.body.dataset.state==='INPUT'&&all('.correct').length===0,'Incomplete consumed');key('C');key('X',{repeat:true});key('X',{ctrlKey:true});check(rowLetters(0)==='C','Repeated/shortcut key inserted');$('#keyboardToggle').click();check(rowLetters(0)==='C','Keyboard reset');$('[data-key=T]').click();$('[data-key=E]').click();check(rowLetters(0)==='CTE','Shared input buffer');key('Enter');key('Enter');key('A');check(d.body.dataset.state==='EVALUATING'&&rowLetters(1)==='','Early next row/double Enter');await wait(()=>$('.carry-letter'));check(d.body.dataset.state==='EVALUATING','Carry accepts input too early');check($('.carry-letter').getAnimations()[0].effect.getTiming().duration>=250,'Carry too fast');await wait(()=>d.body.dataset.state==='INPUT');check(rowLetters(1)==='C','Green did not propagate');check(all('.letter-row')[0].children[1].classList.contains('present'),'Yellow absent');key('Backspace');check(rowLetters(1)==='C','Deleted locked green');await pause(70);key('A');key('R');$('#keyboardToggle').click();check(rowLetters(1)==='CAR','Toggle lost input');key('Enter');await wait(()=>d.body.dataset.state==='INPUT');check(rowLetters(2)==='CA','Accumulated greens lost');await submit('T');check($('#result').open&&$('#medal').hidden,'Final-attempt medal');check(audio===0,'Sound OFF');$('#nextWord').click();$('#nextWord').click();check(d.body.dataset.state==='INPUT'&&rowLetters(0)===''&&all('.correct').length===0,'Next/reset guard');pass('Physical + QWERTY share input, shortcut/repeat/double-submit safety, CAT locks, yellow, backspace, toggles, final medal, reset');
await open(cat.id,'any',1366,768,true);await play();await submit('cat');check($('#result').open&&$('#medal').textContent==='🥇','First medal');check(audio===1&&bursts===1,'Shared victory not exactly once');await pause(3300);check(!$('.victory-confetti'),'Confetti remains');pass('First-try success, shared asset victory once, twin-cannon cleanup');
await open(cat.id,'any',1366,768,true);await play();for(let i=0;i<3;i++)await submit('ZZZ');check(d.body.dataset.state==='FAILURE'&&$('#answer').textContent==='CAT','Failure answer');check(audio===3&&bursts===0,'Failure celebrated');pass('Calm failure, correct answer, no victory sound/confetti');
await open(cat.id);await play();key('Z');$('#hint').click();$('#hint').click();check(all('.letter-row')[0].querySelectorAll('.correct').length===1,'Double Hint');key('Backspace');check(all('.letter-row')[0].querySelectorAll('.correct').length===1,'Hint removed');await pause(320);check($('#hint').disabled,'Hint limit');const remaining=[...all('.letter-row')[0].children].map((cell,i)=>cell.classList.contains('correct')?'':'CAT'[i]).join('');await submit(remaining);check($('#result').open&&$('#medal').textContent==='🥇','Hint penalty');pass('Hint limit, protected position, no attempt or medal penalty');
for(const [w,h] of [[390,844],[412,915],[844,390],[915,412],[820,1180],[1024,768],[1366,768],[1920,1080]]){await open(long.id,8,w,h);await play();fits(w,h);$('#keyboardToggle').click();await pause(60);fits(w,h);for(let attempt=0;attempt<4;attempt++){await submit(attempt===0?'ELEPZZZZ':'ZZZZ');await pause(40);fits(w,h);}await submit('HANT');check($('#medal').hidden,'Fifth attempt medal');fits(w,h);pass(w+'x'+h+' 8x5 grid, keyboard open/closed, every active row, final result')}
await open(cat.id);await play();key('C');const signature=$('#grid').innerHTML;$('#settingsOpen').click();for(const theme of THEME_IDS){$('#liveTheme').value=theme;$('#liveTheme').dispatchEvent(new f.contentWindow.Event('change'));check(d.body.dataset.theme===theme&&$('#grid').innerHTML===signature,'Theme reset word');}$('#prefCancel').click();await pause(30);check(d.body.dataset.theme==='notebook'&&rowLetters(0)==='C','Theme Cancel');$('#settingsOpen').click();$('#liveTheme').value='ocean';$('#prefForm').requestSubmit();await pause(30);check(d.body.dataset.theme==='ocean'&&rowLetters(0)==='C','Theme commit');pass('All eight themes preview, Cancel/Done preserve grid');
await open(none.id);check($('#play').disabled&&$('#compatibility').textContent.includes("doesn't have any words"),'Empty compatibility');check(new URL(f.contentWindow.location.href).searchParams.get('set')===none.id,'Silent fallback');await open('wordly-missing-id');check($('#play').disabled&&$('#setSelect').value==='','Missing fallback');pass('No eligible pool / missing set: explicit selection, no fallback');
f.src='../sets/';await new Promise(r=>f.onload=r);d=f.contentDocument;await wait(()=>d.querySelector('article[aria-label="__Wordly incompatible"]'));const card=d.querySelector('article[aria-label="__Wordly incompatible"]');[...card.querySelectorAll('button')].find(b=>b.textContent==='Play').click();check($('[data-game=wordly]').disabled&&$('.game-chooser').textContent.includes('no compatible words'),'Chooser incompatibility');$('.game-chooser').close();await pause(30);const good=d.querySelector('article[aria-label="__Wordly cat"]');[...good.querySelectorAll('button')].find(b=>b.textContent==='Play').click();$('[data-game=wordly]').click();await wait(()=>f.contentWindow.location.pathname.includes('/wordly/'));d=f.contentDocument;await wait(()=>$('#setup')?.open);check($('#setSelect').value===cat.id,'Chooser wrong set');pass('Chooser Wordly enabled/disabled and exact set ID');
const canvas=document.createElement('canvas');canvas.width=80;canvas.height=60;const blob=await new Promise(r=>canvas.toBlob(r));const uploaded=await fixture('__Wordly upload',['cat',...tail],{type:'upload',blob});await open(uploaded.id);await play();await wait(()=>$('#clue img')?.naturalWidth===80);check($('#clue img').alt==='Picture clue','Uploaded alt leak');pass('Uploaded image from shared repository, neutral clue alt');
out.textContent+='ALL WORDLY CHECKS PASSED';}catch(e){out.textContent+='FAIL: '+e.message;console.error(e);}finally{f.src='about:blank';for(const id of owned.splice(0))await setRepository.delete(id);saved===null?localStorage.removeItem(pref):localStorage.setItem(pref,saved);}};
