import {WordlyRound,createBag,medalFor,successCopy} from './engine.js';
import {eligiblePool,LENGTHS,normalizeLength} from './eligibility.js';
import {loadPreferences,savePreferences,gameURL} from './settings.js';
import {setRepository} from '../../shared/sets.js';
import {canPlaySet} from '../../shared/content-rules.js';
import {showImage} from '../../shared/images.js';
import {importSet} from '../../shared/transfer.js';
import {THEME_OPTIONS} from '../../shared/themes.js';
import {createSettingsPreview} from '../../shared/settings-preview.js';
import {celebrate,clearCelebration} from '../../shared/celebration.js';
import {applyTheme} from '../dobble/theme-view.js';
import {resolveSetReference} from '../dobble/resolution.js';
const $=id=>document.getElementById(id),settings=loadPreferences(),pause=ms=>new Promise(r=>setTimeout(r,ms));
let sets=[],selected=null,bag=null,round=null,draftLength=settings.length,revealed=0,hintUntil=0,lastInput=null,resultShown=false,requested;
const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
function fail(error){$('error').textContent=error.message||String(error);$('error').hidden=false;}
function persist(){savePreferences(settings);history.replaceState(null,'',gameURL(settings));}
function selectOptions(){const select=$('setSelect');select.replaceChildren();select.append(new Option('Choose a content set',''));for(const set of sets)select.append(new Option(set.name,set.id));select.value=selected?.id||'';}
function syncSetup(){const pool=eligiblePool(selected);if(draftLength!=='any'&&!eligiblePool(selected,draftLength).length)draftLength='any';for(const b of $('lengthOptions').children){const length=normalizeLength(b.dataset.length);b.disabled=!eligiblePool(selected,length).length;b.setAttribute('aria-pressed',String(length===draftLength));}
 $('setSummary').textContent=selected?selected.name+' · '+pool.length+' compatible '+(pool.length===1?'word':'words')+' · This set will be used.':'';
 const valid=canPlaySet(selected);$('play').disabled=!valid||!eligiblePool(selected,draftLength).length;
 $('compatibility').textContent=!selected?'This set is not available on this device. Choose another set, or import its JSON.':!valid?'Minimum: 5 valid items in the Content Set. Edit this set to add words and images.':!pool.length?"This set doesn't have any words that work with Wordly Spelling yet. Wordly currently uses single words with 3–8 English letters.":eligiblePool(selected,draftLength).length+' '+(eligiblePool(selected,draftLength).length===1?'word':'words')+' ready. Spaces, punctuation and phrases are excluded.';
}
function setup(){draftLength=settings.length;$('themeSelect').value=settings.theme;$('sound').checked=settings.sound;selectOptions();syncSetup();$('setup').showModal();}
for(const value of LENGTHS){const b=document.createElement('button');b.type='button';b.dataset.length=value;b.textContent=value==='any'?'Any':value;b.onclick=()=>{draftLength=value;syncSetup();};$('lengthOptions').append(b);}
$('setSelect').onchange=()=>{selected=sets.find(s=>s.id===$('setSelect').value)||null;syncSetup();};
$('setupForm').onsubmit=e=>{e.preventDefault();if($('play').disabled)return;const pool=eligiblePool(selected,draftLength);if(!pool.length)return;Object.assign(settings,{set:selected.id,length:draftLength,theme:$('themeSelect').value,sound:$('sound').checked});persist();applyTheme(settings.theme);bag=createBag(pool);$('setName').textContent=selected.name;$('welcome').hidden=true;$('playArea').hidden=false;$('keyboard').hidden=true;document.body.classList.remove('keyboard-open');$('keyboardToggle').setAttribute('aria-expanded','false');$('keyboardToggle').setAttribute('aria-label','Show on-screen keyboard');$('setup').close();nextRound();};
$('setupCancel').onclick=()=>$('setup').close();$('setupOpen').onclick=setup;
function nextRound(){clearCelebration();$('result').close();$('resultCopy').textContent='';$('answer').textContent='';$('resultImage').replaceChildren();$('medal').textContent='';round=new WordlyRound(bag.next());revealed=0;hintUntil=0;lastInput=null;resultShown=false;showImage($('clue'),round.concept.image,'Picture clue');$('status').textContent='Type the word, then press Enter.';render();$('grid').focus();}
function render(){if(!round)return;document.body.dataset.state=round.state;$('grid').style.setProperty('--length',round.length);$('grid').replaceChildren();const evaluating=round.state==='EVALUATING',last=round.rows.at(-1),visibleLocks=evaluating?round.locked.map((v,i)=>last.prelocked[i]?v:null):round.locked;
 for(let r=0;r<round.maxAttempts;r++){const row=document.createElement('div');row.className='letter-row';row.setAttribute('role','row');row.dataset.row=r;const evaluated=round.rows[r],active=round.state==='INPUT'&&r===round.rows.length;if(active)row.classList.add('active');if(evaluating&&r===round.rows.length-1)row.classList.add('evaluating');const letters=evaluated?evaluated.letters:!evaluating&&r===round.rows.length?round.current:visibleLocks.map(v=>v||'');const cursor=active?round.current.findIndex((v,i)=>!round.locked[i]&&!v):-1;
 for(let i=0;i<round.length;i++){const cell=document.createElement('div');cell.className='tile';cell.setAttribute('role','gridcell');cell.dataset.position=i;const shown=!evaluating||r!==round.rows.length-1||i<revealed||evaluated?.prelocked[i];const state=evaluated?(shown?evaluated.feedback[i]:''):visibleLocks[i]?'correct':'';cell.textContent=letters[i]||'';if(state){cell.classList.add(state);const mark=document.createElement('span');mark.className='state-icon';mark.textContent={correct:'✓',present:'↔',absent:'×'}[state];mark.setAttribute('aria-hidden','true');cell.append(mark);}if(active&&i===cursor)cell.classList.add('cursor');if(evaluating&&r===round.rows.length-1&&i===revealed-1)cell.classList.add('revealing');const label=state?{correct:'correct position',present:'present, wrong position',absent:'not available'}[state]:'empty';cell.setAttribute('aria-label','Position '+(i+1)+': '+(letters[i]?letters[i]+(state?', '+label:''):label));row.append(cell);} $('grid').append(row);}
 $('attemptLabel').textContent='Try '+Math.max(1,Math.min(round.submitted+(round.state==='INPUT'?1:0),round.maxAttempts))+' of '+round.maxAttempts+' · '+round.length+' letters';$('hint').disabled=round.state!=='INPUT'||performance.now()<hintUntil;$('submit').disabled=round.state!=='INPUT';for(const key of $('keyboard').querySelectorAll('button'))key.disabled=round.state!=='INPUT';requestAnimationFrame(fit);
}
function fit(){if(!round||$('playArea').hidden)return;const viewport=$('gridViewport'),n=round.length,rows=round.maxAttempts,gap=Math.max(4,Math.min(9,Math.floor(viewport.clientWidth/90))),cap=[0,0,0,112,102,92,84,78,72][n];const byWidth=Math.floor((viewport.clientWidth-12-(n-1)*gap)/n),byHeight=Math.floor((viewport.clientHeight-10-(rows-1)*gap)/rows);$('grid').style.setProperty('--gap',gap+'px');$('grid').style.setProperty('--tile',Math.max(20,Math.min(cap,byWidth,Math.max(32,byHeight)))+'px');const active=$('grid').querySelector('.active,.evaluating');active?.scrollIntoView({block:'nearest',inline:'nearest',behavior:'instant'});}
async function submit(){if(round?.state!=='INPUT')return;const row=round.submit();if(!row)return;if(row.incomplete){$('status').textContent='Fill the empty spaces before pressing Enter.';return;}const current=round;revealed=0;render();for(let i=0;i<round.length;i++){if(!reduced())await pause(90);if(round!==current)return;revealed=i+1;render();}if(!reduced())await pause(110);if(round!==current)return;round.finishFeedback();render();if(round.state==='INPUT'){$('status').textContent='Green letters stay locked. Try the empty spaces.';$('grid').focus();}else endRound();}
function input(value,source){if(round?.state!=='INPUT'||document.querySelector('dialog[open]'))return;const now=performance.now();if(lastInput&&lastInput.value===value&&lastInput.source!==source&&now-lastInput.time<60)return;lastInput={value,source,time:now};if(value==='Enter'){submit();return;}const changed=value==='Backspace'?round.backspace():round.type(value);if(changed){$('status').textContent='Type the word, then press Enter.';render();}}
$('submit').onclick=()=>{input('Enter','screen');$('grid').focus();};
$('hint').onclick=()=>{if(round?.state!=='INPUT'||performance.now()<hintUntil)return;hintUntil=performance.now()+300;const current=round,index=round.hint();if(index===false)return;$('status').textContent='One letter is now locked in place.';render();if(round.state==='SUCCESS')endRound();else $('grid').focus();setTimeout(()=>{if(round===current)render();},310);};
for(const [r,letters] of ['QWERTYUIOP','ASDFGHJKL','ZXCVBNM'].entries()){const row=document.createElement('div');row.className='keyboard-row';const values=r===2?['Backspace',...letters,'Enter']:[...letters];for(const value of values){const b=document.createElement('button');b.type='button';b.textContent=value==='Backspace'?'⌫':value;b.setAttribute('aria-label',value);b.dataset.key=value;if(value.length>1)b.className='wide';b.onpointerdown=e=>e.preventDefault();b.onclick=()=>{input(value,'screen');$('grid').focus();};row.append(b);} $('keyboard').append(row);}
$('keyboardToggle').onclick=()=>{const open=$('keyboard').hidden;$('keyboard').hidden=!open;document.body.classList.toggle('keyboard-open',open);$('keyboardToggle').setAttribute('aria-expanded',String(open));$('keyboardToggle').setAttribute('aria-label',open?'Hide on-screen keyboard':'Show on-screen keyboard');requestAnimationFrame(fit);$('grid').focus();};
document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.isComposing||document.querySelector('dialog[open]')||e.target.closest('input,select,textarea,[contenteditable=true],[data-game-shell]'))return;if(!/^[a-z]$/i.test(e.key)&&!['Enter','Backspace'].includes(e.key))return;if(e.key==='Enter'&&e.target.closest('button,a'))return;if(!round)return;e.preventDefault();if(!e.repeat)input(e.key.length===1?e.key.toUpperCase():e.key,'physical');});
function endRound(){if(resultShown||!['SUCCESS','FAILURE'].includes(round.state))return;resultShown=true;const won=round.state==='SUCCESS';$('resultTitle').textContent=won?'Great job!':'The word was:';$('resultCopy').textContent=won?successCopy(round.submitted):'Let’s try another word.';const medal=won?medalFor(round.submitted,round.maxAttempts):'';$('medal').textContent=medal;$('medal').hidden=!medal;$('answer').textContent=round.answer;$('resultImage').hidden=won;if(!won)showImage($('resultImage'),round.concept.image,'Answer picture');$('nextWord').textContent=won?'Play Another Word':'Try Another Word';if(won)celebrate(settings.sound);$('result').showModal();$('nextWord').focus();}
$('nextWord').onclick=()=>{if(!['SUCCESS','FAILURE'].includes(round?.state))return;nextRound();};$('result').addEventListener('cancel',e=>e.preventDefault());
for(const id of ['themeSelect','liveTheme'])for(const [value,label] of THEME_OPTIONS)$(id).append(new Option(label,value));
const preview=createSettingsPreview(settings,['theme','sound'],()=>applyTheme(settings.theme));$('settingsOpen').onclick=()=>{if(!round){setup();return;}if(round.state!=='INPUT')return;preview.begin();$('liveTheme').value=settings.theme;$('liveSound').checked=settings.sound;$('preferences').showModal();};$('liveTheme').onchange=()=>preview.update({theme:$('liveTheme').value});$('liveSound').onchange=()=>preview.update({sound:$('liveSound').checked});$('prefCancel').onclick=()=>$('preferences').close();$('preferences').addEventListener('close',()=>{preview.cancel();$('grid').focus();});$('prefForm').onsubmit=e=>{e.preventDefault();preview.update({theme:$('liveTheme').value,sound:$('liveSound').checked});preview.commit();persist();$('preferences').close();};
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{fail(Error('Fullscreen is not available in this browser.'));}};$('copyLink').onclick=async()=>{try{await navigator.clipboard.writeText(gameURL(settings));$('status').textContent='Game link copied. Import this set on other devices first.';}catch{fail(Error('Copy this game link: '+gameURL(settings)));}};
$('importFile').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>40*1024*1024)throw Error('Maximum JSON file size is 40 MB.');const imported=await importSet(await file.text(),{requestedId:requested});sets=await setRepository.list();if(imported.id===requested){selected=imported;$('missingTools').hidden=true;}else $('importStatus').textContent='This file contains a different set. Choose it explicitly from Content Set to use it.';selectOptions();syncSetup();}catch(error){$('importStatus').textContent=error.message;}};
addEventListener('resize',fit);visualViewport?.addEventListener('resize',fit);addEventListener('pagehide',()=>{round=null;clearCelebration();});new ResizeObserver(fit).observe($('gridViewport'));
applyTheme(settings.theme);try{sets=await setRepository.list();const params=new URLSearchParams(location.search);requested=params.has('set')?params.get('set'):undefined;selected=resolveSetReference(sets,requested,settings.set);$('missingTools').hidden=!!selected;setup();if(setRepository.warnings.length)fail(Error(setRepository.warnings.join('\n')));}catch(error){fail(error);}
