import {DiceTable} from './engine.js';
import {rollSound,removeSound} from './sound.js';
import {layoutDice} from './layout.js';
import {setRepository} from '../../shared/sets.js';
import {canPlaySet} from '../../shared/content-rules.js';
import {showImage} from '../../shared/images.js';
import {THEME_OPTIONS,normalizeTheme} from '../../shared/themes.js';
import {applyTheme} from '../dobble/theme-view.js';
import {resolveSetReference} from '../dobble/resolution.js';
import {createSettingsPreview} from '../../shared/settings-preview.js';
const $=id=>document.getElementById(id),key='sunny-stacy.story-dice.settings.v1',params=new URLSearchParams(location.search);
let stored={};try{stored=JSON.parse(localStorage.getItem(key)||'{}')||{};}catch{}
const mode=value=>['story','concept','sentence'].includes(value)?value:'story';
const settings={mode:mode(params.get('mode')||(params.has('set')?'concept':stored.mode)),set:stored.set||'animals-1',theme:normalizeTheme(params.get('theme')||stored.theme||'notebook'),sound:params.has('sound')?!['false','off'].includes(params.get('sound')):stored.sound!==false};
let sets=[],selected=null,table=null;const timers=new Map(),cooldowns=new Map();
function fail(error){$('error').textContent=error.message||String(error);$('error').hidden=false;}
function url(){const u=new URL('./',import.meta.url);u.search=new URLSearchParams({mode:settings.mode,theme:settings.theme,sound:settings.sound});if(settings.mode==='concept')u.searchParams.set('set',settings.set);return u.href;}
function save(){try{localStorage.setItem(key,JSON.stringify(settings));}catch{}history.replaceState(null,'',url());}
function syncSetup(){const concept=$('mode').value==='concept';$('setLabel').hidden=!concept;$('compatibility').textContent=concept?selected?selected.name+' · '+selected.items.length+' items'+(canPlaySet(selected)?' · This set will be used.':' · Minimum: 5 valid items.'):'This set is unavailable on this device. Choose a set from My Sets.':'';$('play').disabled=concept&&!canPlaySet(selected);$('modeHelp').textContent={story:'Add one picture at a time and tell a story.',concept:'Roll pictures and words from your vocabulary set.',sentence:'Add prompts, then build your own sentences. Time and Aspect can be changed on the table.'}[$('mode').value];}
function setup(){ $('mode').value=settings.mode;$('theme').value=settings.theme;$('sound').checked=settings.sound;$('setSelect').replaceChildren(new Option('Choose a content set',''));for(const set of sets)$('setSelect').append(new Option(set.name,set.id));$('setSelect').value=selected?.id||'';syncSetup();$('setup').showModal();}
for(const id of ['theme','liveTheme'])for(const [value,label] of THEME_OPTIONS)$(id).append(new Option(label,value));
$('mode').onchange=syncSetup;$('setSelect').onchange=()=>{selected=sets.find(s=>s.id===$('setSelect').value)||null;syncSetup();};$('modeOpen').onclick=setup;$('cancel').onclick=()=>$('setup').close();
function cancelTimers(){for(const timer of timers.values())clearTimeout(timer);timers.clear();}
$('setupForm').onsubmit=e=>{e.preventDefault();if($('play').disabled)return;cancelTimers();cooldowns.clear();Object.assign(settings,{mode:$('mode').value,set:selected?.id||settings.set,theme:$('theme').value,sound:$('sound').checked});table=new DiceTable(settings.mode,settings.mode==='concept'?selected.items:[]);save();applyTheme(settings.theme);$('modeName').textContent=settings.mode==='concept'?'Concept · '+selected.name:settings.mode==='sentence'?'Sentence · Roll prompts. Build your own sentence.':'Story · One picture, one new idea.';$('grammar').hidden=settings.mode!=='sentence';$('time').value=table.time;$('aspect').value=table.aspect;buildControls();$('setup').close();renderAll();};
function button(label,action,aria){const b=document.createElement('button');b.type='button';b.textContent=label;if(aria)b.setAttribute('aria-label',aria);b.onclick=action;return b;}
function buildControls(){ $('addControls').replaceChildren();for(const category of settings.mode==='sentence'?['subject','action','object','where','how','time']:['main']){const title=category[0].toUpperCase()+category.slice(1);const b=button(category==='main'?'🎲 +1':'+ '+title,()=>add(category));b.dataset.category=category;b.className='primary';$('addControls').append(b);}}
function sync(){if(!table)return;for(const b of $('addControls').children)b.disabled=!table.canAdd(b.dataset.category)||cooldowns.has(b.dataset.category);$('clear').disabled=!table.dice.length;$('status').textContent=table.dice.length+' / '+(table.mode==='sentence'?18:10)+' dice';$('empty').hidden=!!table.dice.length;$('empty').innerHTML=table.mode==='sentence'?'Choose a category below.<br>Combine the prompts in your own sentence.':'An empty table. A thousand possible stories.<br>Press +1 to begin.';scheduleLayout();}
function dieNode(die){const host=document.createElement('article');host.className='die '+(die.rollState==='rolling'?'rolling':'');host.dataset.id=die.id;host.style.setProperty('--rotation',die.rotation+'deg');const category=document.createElement('div');category.className='die-category';category.textContent=die.category==='time'?die.tense+' '+die.aspect:die.category==='main'?'':die.category;const face=document.createElement('div');face.className='die-face';showImage(face,die.image,die.label);const label=document.createElement('div');label.className='die-label';label.textContent=die.label;const controls=document.createElement('div');controls.className='die-tools';const reroll=button('↻',()=>{const updated=table.reroll(die.id);if(updated)animate(updated);},'Reroll '+die.label);reroll.disabled=die.rollState==='rolling';const remove=button('×',()=>removeDie(die,host),'Remove '+die.label);controls.append(reroll,remove);const visual=document.createElement('div');visual.className='die-visual';visual.append(face,controls);host.append(category,visual,label);return host;}
function replaceDie(die){const old=$('table').querySelector('[data-id="'+die.id+'"]'),node=dieNode(die);if(old){node.style.cssText=old.style.cssText;node.style.setProperty('--rotation',die.rotation+'deg');old.replaceWith(node);}else{node.classList.add('entering');$('table').append(node);}return node;}
function animate(die){const current=table,node=replaceDie(die);rollSound(settings.sound);sync();const timer=setTimeout(()=>{timers.delete(die.id);if(table!==current||!table.dice.some(d=>d.id===die.id))return;table.settle(die.id);node.classList.remove('rolling','entering');node.querySelector('button').disabled=false;sync();},matchMedia('(prefers-reduced-motion: reduce)').matches?0:660);timers.set(die.id,timer);}
function add(category){if(!table||cooldowns.has(category))return;const die=table.add(category);if(!die)return;cooldowns.set(category,true);animate(die);setTimeout(()=>{cooldowns.delete(category);sync();},350);}
function renderAll(){ $('table').querySelectorAll('.die').forEach(n=>n.remove());for(const die of table.dice)replaceDie(die);sync();}
let layoutFrame;function scheduleLayout(){cancelAnimationFrame(layoutFrame);layoutFrame=requestAnimationFrame(()=>layoutDice($('table')));}new ResizeObserver(scheduleLayout).observe($('table'));addEventListener('resize',scheduleLayout);document.fonts.ready.then(scheduleLayout);
function removeDie(die,host){if(host.classList.contains('removing'))return;clearTimeout(timers.get(die.id));host.classList.remove('rolling','entering');host.classList.add('removing');for(const b of host.querySelectorAll('button'))b.disabled=true;removeSound(settings.sound);const current=table;timers.set(die.id,setTimeout(()=>{timers.delete(die.id);if(table!==current)return;const focused=host.contains(document.activeElement);table.remove(die.id);host.remove();sync();if(focused)$('table').focus();},matchMedia('(prefers-reduced-motion: reduce)').matches?0:320));}

$('clear').onclick=()=>{if(!table)return;cancelTimers();table.clear();renderAll();};for(const id of ['time','aspect'])$(id).onchange=()=>{table?.setGrammar($('time').value,$('aspect').value);};
const preview=createSettingsPreview(settings,['theme','sound'],()=>applyTheme(settings.theme));$('settingsOpen').onclick=()=>{if(!table){setup();return;}preview.begin();$('liveTheme').value=settings.theme;$('liveSound').checked=settings.sound;$('preferences').showModal();};$('liveTheme').onchange=()=>preview.update({theme:$('liveTheme').value});$('liveSound').onchange=()=>preview.update({sound:$('liveSound').checked});$('prefCancel').onclick=()=>$('preferences').close();$('preferences').addEventListener('close',()=>preview.cancel());$('prefForm').onsubmit=e=>{e.preventDefault();preview.commit();save();$('preferences').close();};
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{fail(Error('Fullscreen is unavailable in this browser.'));}};$('copyLink').onclick=async()=>{try{await navigator.clipboard.writeText(url());$('status').textContent='Link copied. Custom sets must be imported on other devices.';}catch{fail(Error('Copy this game link: '+url()));}};addEventListener('pagehide',cancelTimers);
applyTheme(settings.theme);try{sets=await setRepository.list();selected=resolveSetReference(sets,params.has('set')?params.get('set'):undefined,settings.set);setup();if(setRepository.warnings.length)fail(Error(setRepository.warnings.join('\n')));}catch(error){fail(error);setup();}
