import {trackGameViewport} from '../../shared/visual-viewport.js';
import {mountSetupMenu} from '../../shared/setup-menu.js';
import {setupThemePreview} from '../../shared/setup-preview.js';
import {DiceTable} from './engine.js';
import {rollSound,removeSound} from './sound.js';
import {layoutDice} from './layout.js';
import {setRepository} from '../../shared/sets.js';
import {canPlaySet} from '../../shared/content-rules.js';
import {showImage} from '../../shared/images.js';
import {THEME_OPTIONS,normalizeTheme} from '../../shared/themes.js';
import {applyTheme} from '../dobble/theme-view.js';
import {resolveSetReference} from '../dobble/resolution.js';
import {createSettingsPreview} from '../../shared/settings-preview.js';
const $=id=>document.getElementById(id),key='sunny-stacy.story-dice.settings.v1',params=new URLSearchParams(location.search);
let stored={};try{stored=JSON.parse(localStorage.getItem(key)||'{}')||{};}catch{}
const mode=value=>['story','concept','sentence'].includes(value)?value:'story';
const settings={mode:mode(params.get('mode')||(params.has('set')?'concept':stored.mode)),set:stored.set||'animals-1',theme:normalizeTheme(params.get('theme')||stored.theme||'notebook'),sound:params.has('sound')?!['false','off'].includes(params.get('sound')):stored.sound!==false};
let sets=[],selected=null,table=null;const timers=new Map(),cooldowns=new Map();
let setupMenu,activeSetupKey=null;
function fail(error){$('error').textContent=error.message||String(error);$('error').hidden=false;}
function url(){const u=new URL('./',import.meta.url);u.search=new URLSearchParams({mode:settings.mode,theme:settings.theme,sound:settings.sound});if(settings.mode==='concept')u.searchParams.set('set',settings.set);return u.href;}
function save(){try{localStorage.setItem(key,JSON.stringify(settings));}catch{}history.replaceState(null,'',url());}
function syncSetup(){const concept=$('mode').value==='concept',content=setupMenu?.sessionSet(selected)||selected;$('setLabel').hidden=true;$('compatibility').textContent=concept?selected?selected.name+' · '+content.items.length+' included'+(canPlaySet(content)?'':' · Include at least 5 valid concepts.'):'This set is unavailable on this device. Choose a set from My Sets.':'Sets are used in Concept mode. Story and Sentence use the built-in prompts.';$('play').disabled=concept&&!canPlaySet(content);$('modeHelp').textContent={story:'Add one picture at a time and tell a story.',concept:'Roll pictures and words from your vocabulary set.',sentence:'Add prompts, then build your own sentences. Time and Aspect can be changed on the table.'}[$('mode').value];setupMenu?.sync();}
function setup(){if(table)selected=sets.find(s=>s.id===settings.set)||selected;$('mode').value=settings.mode;$('theme').value=settings.theme;$('sound').checked=settings.sound;$('setSelect').replaceChildren(new Option('Choose a content set',''));for(const set of sets)$('setSelect').append(new Option(set.name,set.id));$('setSelect').value=selected?.id||'';setupMenu?.begin();syncSetup();$('setup').showModal();}
for(const id of ['theme','liveTheme'])for(const [value,label] of THEME_OPTIONS)$(id).append(new Option(label,value));
$('mode').onchange=syncSetup;$('setSelect').onchange=()=>{selected=sets.find(s=>s.id===$('setSelect').value)||null;syncSetup();};$('modeOpen').onclick=setup;$('cancel').onclick=()=>$('setup').close();
function cancelTimers(){closeMenu();for(const timer of timers.values())clearTimeout(timer);timers.clear();}
$('setupForm').onsubmit=e=>{e.preventDefault();if($('play').disabled)return;const nextKey=JSON.stringify([$('mode').value,$('mode').value==='concept'?setupMenu.contentKey(selected):null]),restart=!table||nextKey!==activeSetupKey;Object.assign(settings,{mode:$('mode').value,set:selected?.id||settings.set,theme:$('theme').value,sound:$('sound').checked});save();applyTheme(settings.theme);setupMenu.commit();activeSetupKey=nextKey;if(!restart){$('setup').close();return;}cancelTimers();cooldowns.clear();table=new DiceTable(settings.mode,settings.mode==='concept'?setupMenu.sessionSet(selected).items:[]);$('modeName').textContent=settings.mode==='concept'?'Concept · '+selected.name:settings.mode==='sentence'?'Sentence':'Story';$('grammar').hidden=settings.mode!=='sentence';$('time').value=table.time;$('aspect').value=table.aspect;buildControls();$('setup').close();renderAll();};
function button(label,action,aria){const b=document.createElement('button');b.type='button';b.textContent=label;if(aria)b.setAttribute('aria-label',aria);b.onclick=action;return b;}
function buildControls(){ $('addControls').replaceChildren();for(const category of settings.mode==='sentence'?['subject','action','object','where','how','time']:['main']){const title=category[0].toUpperCase()+category.slice(1);const b=button(category==='main'?'🎲 +1':'+ '+title,()=>add(category));b.dataset.category=category;b.className='primary';$('addControls').append(b);}}
function sync(){if(!table)return;for(const b of $('addControls').children)b.disabled=!table.canAdd(b.dataset.category)||cooldowns.has(b.dataset.category);$('clear').disabled=!table.dice.length;$('status').textContent=table.dice.length+' / '+(table.mode==='sentence'?18:10)+' dice';$('empty').hidden=!!table.dice.length;$('empty').innerHTML=table.mode==='sentence'?'Choose a category below.<br>Combine the prompts in your own sentence.<br>Click a die to reroll or remove it.':'An empty table. A thousand possible stories.<br>Press +1 to begin.<br>Click a die to reroll or remove it.';scheduleLayout();}
function dieNode(die){
 const host=document.createElement('article');host.className='die '+(die.rollState==='rolling'?'rolling':'');host.dataset.id=die.id;host.style.setProperty('--rotation',die.rotation+'deg');host.tabIndex=0;host.setAttribute('role','button');host.setAttribute('aria-label',die.label+' — actions');host.setAttribute('aria-haspopup','menu');host.setAttribute('aria-expanded','false');
 const category=document.createElement('div');category.className='die-category';const kind=document.createElement('span');kind.className='die-kind';kind.textContent=die.category==='main'?'':die.category;category.append(kind);if(die.category==='time'){const grammar=document.createElement('span');grammar.className='die-grammar';grammar.textContent=die.tense+' '+die.aspect;category.append(grammar);}
 const face=document.createElement('div');face.className='die-face';const image=document.createElement('div');image.className='die-image';showImage(image,die.image,die.label);const label=document.createElement('div');label.className='die-label';label.textContent=die.label;const content=document.createElement('div');content.className='die-content';content.append(image,label);face.append(category,content);host.append(face);
 host.onclick=()=>toggleMenu(die,host);host.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggleMenu(die,host);}};return host;
}
const actionMenu=document.createElement('div');actionMenu.id='dieActions';actionMenu.className='die-action-menu';actionMenu.hidden=true;actionMenu.setAttribute('role','menu');actionMenu.setAttribute('aria-label','Die actions');document.body.append(actionMenu);let menuHost=null;
function closeMenu(focus=false){const host=menuHost;host?.setAttribute('aria-expanded','false');menuHost=null;actionMenu.hidden=true;if(focus&&host?.isConnected)host.focus();}
function positionMenu(){if(!menuHost)return;const box=menuHost.getBoundingClientRect(),view=globalThis.visualViewport,ox=view?.offsetLeft||0,oy=view?.offsetTop||0,w=view?.width||innerWidth,h=view?.height||innerHeight,m=actionMenu.getBoundingClientRect();actionMenu.style.left=Math.max(ox+8,Math.min(box.right-m.width,ox+w-m.width-8))+'px';actionMenu.style.top=Math.max(oy+8,Math.min(box.bottom+6+m.height<=oy+h-8?box.bottom+6:box.top-m.height-6,oy+h-m.height-8))+'px';}
function toggleMenu(die,host){if(host.classList.contains('removing'))return;if(menuHost===host){closeMenu(true);return;}closeMenu();menuHost=host;host.setAttribute('aria-expanded','true');const reroll=button('↻ Reroll',()=>{closeMenu();const updated=table.reroll(die.id);if(updated){animate(updated);$('table').querySelector('[data-id="'+die.id+'"]').focus();}});reroll.disabled=die.rollState==='rolling';const remove=button('× Remove',()=>{closeMenu();removeDie(die,host);$('table').focus();});for(const b of [reroll,remove])b.setAttribute('role','menuitem');actionMenu.replaceChildren(reroll,remove);actionMenu.hidden=false;positionMenu();(reroll.disabled?remove:reroll).focus();}
addEventListener('pointerdown',e=>{if(menuHost&&!actionMenu.contains(e.target)&&!e.target.closest('.die'))closeMenu();});
actionMenu.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();closeMenu(true);}else if(e.key==='Tab')closeMenu();else if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const choices=[...actionMenu.querySelectorAll('button:not(:disabled)')],i=choices.indexOf(document.activeElement);choices[e.key==='Home'?0:e.key==='End'?choices.length-1:(i+(e.key==='ArrowDown'?1:-1)+choices.length)%choices.length].focus();}};
addEventListener('resize',()=>closeMenu());globalThis.visualViewport?.addEventListener('resize',()=>closeMenu());
function replaceDie(die){const old=$('table').querySelector('[data-id="'+die.id+'"]'),node=dieNode(die);if(old){node.style.cssText=old.style.cssText;node.style.setProperty('--rotation',die.rotation+'deg');old.replaceWith(node);}else{node.classList.add('entering');$('table').append(node);}return node;}
function animate(die){const current=table,node=replaceDie(die);rollSound(settings.sound);sync();const timer=setTimeout(()=>{timers.delete(die.id);if(table!==current||!table.dice.some(d=>d.id===die.id))return;table.settle(die.id);node.classList.remove('rolling','entering');sync();},matchMedia('(prefers-reduced-motion: reduce)').matches?0:660);timers.set(die.id,timer);}
function add(category){if(!table||cooldowns.has(category))return;const die=table.add(category);if(!die)return;cooldowns.set(category,true);animate(die);setTimeout(()=>{cooldowns.delete(category);sync();},350);}
function renderAll(){closeMenu(); $('table').querySelectorAll('.die').forEach(n=>n.remove());for(const die of table.dice)replaceDie(die);sync();}
let layoutFrame;function scheduleLayout(){cancelAnimationFrame(layoutFrame);layoutFrame=requestAnimationFrame(()=>layoutDice($('table')));}new ResizeObserver(scheduleLayout).observe($('table'));trackGameViewport(scheduleLayout);document.fonts.ready.then(scheduleLayout);
function removeDie(die,host){if(host.classList.contains('removing'))return;clearTimeout(timers.get(die.id));host.classList.remove('rolling','entering');host.classList.add('removing');for(const b of host.querySelectorAll('button'))b.disabled=true;removeSound(settings.sound);const current=table;timers.set(die.id,setTimeout(()=>{timers.delete(die.id);if(table!==current)return;const focused=host.contains(document.activeElement);table.remove(die.id);host.remove();sync();if(focused)$('table').focus();},matchMedia('(prefers-reduced-motion: reduce)').matches?0:320));}

$('clear').onclick=()=>{if(!table)return;cancelTimers();table.clear();renderAll();};for(const id of ['time','aspect'])$(id).onchange=()=>{table?.setGrammar($('time').value,$('aspect').value);};
const preview=createSettingsPreview(settings,['theme','sound'],()=>applyTheme(settings.theme));$('settingsOpen').onclick=()=>{if(!table){setup();return;}preview.begin();$('liveTheme').value=settings.theme;$('liveSound').checked=settings.sound;$('preferences').showModal();};$('liveTheme').onchange=()=>preview.update({theme:$('liveTheme').value});$('liveSound').onchange=()=>preview.update({sound:$('liveSound').checked});$('prefCancel').onclick=()=>{preview.cancel();$('preferences').close();};$('preferences').addEventListener('cancel',()=>preview.cancel());$('preferences').addEventListener('close',()=>{if(!$('preferences').open)preview.cancel();});$('prefForm').onsubmit=e=>{e.preventDefault();preview.commit();save();$('preferences').close();};
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{fail(Error('Fullscreen is unavailable in this browser.'));}};$('copyLink').onclick=async()=>{try{await navigator.clipboard.writeText(url());$('status').textContent='Link copied. Custom sets must be imported on other devices.';}catch{fail(Error('Copy this game link: '+url()));}};addEventListener('pagehide',cancelTimers);
setupMenu=mountSetupMenu({gameType:'story-dice',dialog:$('setup'),form:$('setupForm'),title:$('setupTitle'),setSelect:$('setSelect'),themeSelect:$('theme'),sound:$('sound'),getSets:()=>sets,setSets:next=>{sets=next;},onContentChange:syncSetup,gameplay:[$('mode').closest('label'),$('modeHelp')],status:[$('compatibility')],footer:$('setupForm').querySelector('.dialog-actions'),committedTheme:()=>settings.theme});
$('settingsOpen').onclick=setup;
applyTheme(settings.theme);try{sets=await setRepository.list();selected=resolveSetReference(sets,params.has('set')?params.get('set'):undefined,settings.set);setup();if(setRepository.warnings.length)fail(Error(setRepository.warnings.join('\n')));}catch(error){fail(error);setup();}

setupThemePreview($('setup'),$('theme'),()=>settings.theme);
