const pool=(prefix,text)=>text.split('|').map((entry,i)=>{const [emoji,...label]=entry.split(' ');return {id:prefix+i,emoji,label:label.join(' ')};});
export const sentencePools={
 subject:pool('s','👧 girl|👦 boy|🧑‍🏫 teacher|🧛 vampire|🐶 dog|🐸 frog|🧑 my friend|👾 the monster|🙋 I|🫵 you|👨 he|👩 she|👫 we|👥 they|🧙 wizard|👸 princess|🧑‍🚀 astronaut|🐱 cat|🐰 rabbit|🐻 bear|🦊 fox|🤖 robot|🧑‍🍳 chef|🦸 superhero'),
 action:pool('a','🪑 sit|💃 dance|🍽️ eat|🏃 run|🥤 drink|😴 sleep|📖 read|✍️ write|⚽ play|🦘 jump|🚶 walk|🏊 swim|🎤 sing|🖌️ paint|🎨 draw|👨‍🍳 cook|🧹 clean|🛒 buy|🎁 give|🔎 find|🛠️ build|🚪 open|👀 watch|👂 listen|🧗 climb|🚲 ride|🗣️ talk|🤝 help|📞 call|🧼 wash'),
 object:pool('o','🍕 pizza|📕 a book|🎁 a present|⚽ a ball|🥪 a sandwich|🚗 a car|🍎 an apple|🧸 a teddy bear|🎂 a cake|🪁 a kite|📝 a letter|🏠 a house|🌸 a flower|🧢 a hat|🖼️ a picture|🥛 some milk|💧 some water|🎵 a song|🛶 a boat|🤖 a robot'),
 where:pool('w','🏫 at school|🏠 at home|🌳 in the park|🍳 in the kitchen|🏖️ on the beach|🪑 under the table|🏪 next to the shop|🛋️ behind the sofa|🏡 in front of the house|🏞️ near the river|🛏️ in the bedroom|📚 at the library|🚌 on the bus|🌉 under the bridge|🌲 between the trees|🚪 beside the door|⛰️ on a mountain|🛝 at the playground|🌊 by the sea|🧺 inside the basket'),
 how:pool('h','⚡ quickly|🐢 slowly|🤫 quietly|📣 loudly|🧐 carefully|😊 happily|😢 sadly|😠 angrily|👎 badly|👍 well|🪶 gently|🦁 bravely|🤪 playfully|🤝 together|🙂 politely|💪 confidently|😴 sleepily|🤗 kindly|😃 excitedly|🧘 calmly')
};
export const storyItems=pool('story','🐶 dog|🐱 cat|🐭 mouse|🐰 rabbit|🦊 fox|🐻 bear|🐼 panda|🐸 frog|🦁 lion|🐯 tiger|🐘 elephant|🦒 giraffe|🐊 crocodile|🐬 dolphin|🐳 whale|🐙 octopus|🦋 butterfly|🐝 bee|🐞 ladybird|🦉 owl|🐧 penguin|🐢 turtle|🦄 unicorn|🐉 dragon|🧙 wizard|👸 princess|🤴 prince|🧑‍🚀 astronaut|🧑‍🍳 chef|🧑‍🏫 teacher|🦸 superhero|🤖 robot|👻 ghost|🧜‍♀️ mermaid|🍎 apple|🍌 banana|🍉 watermelon|🍓 strawberry|🥕 carrot|🍕 pizza|🥪 sandwich|🎂 cake|🍦 ice cream|🍪 cookie|🥛 milk|🏠 house|🏰 castle|🏫 school|🏥 hospital|🏪 shop|🏖️ beach|🏝️ island|⛰️ mountain|🌋 volcano|🌲 tree|🌸 flower|🌈 rainbow|☀️ sun|🌙 moon|⭐ star|☁️ cloud|❄️ snowflake|🔥 fire|🚗 car|🚌 bus|🚂 train|✈️ plane|🚀 rocket|🚲 bicycle|⛵ boat|🎈 balloon|🎁 present|🧸 teddy bear|⚽ ball|🪁 kite|📚 books|🔑 key|🗺️ map|🧳 suitcase|📷 camera|🔦 torch|☂️ umbrella|👑 crown|💎 diamond|🎸 guitar|🥁 drum|🛏️ bed|🚪 door|🕰️ clock|🪄 magic wand|🧹 broom|🧦 socks|👟 shoes|🎩 hat|🛝 slide|🎪 circus|🎡 big wheel|💌 letter|🧩 puzzle|🏆 trophy');
const expressions={
 'Present Simple':'every day|every morning|every evening|on Mondays|on Sundays|at weekends|once a week|twice a month|three times a year|usually|often|sometimes|always|never|rarely|after school every day|before breakfast every day|in winter|in summer|every Friday afternoon|on school days|at lunchtime every day|every night|whenever it rains|every birthday',
 'Present Continuous':'right now|at the moment|just now — look!|look, over there!|listen, right now!|today — a temporary activity|this week — a temporary activity|this month — a temporary activity|these days — a temporary change|currently|while we are speaking|at this very moment|right now in the kitchen|right now outside|right now at school|right now in the garden|right now upstairs|right now on the bus|right now at the beach|right now in the park|during this lesson, right now|look through the window now|listen behind the door now|in the picture — describe the action|on the screen — describe the action',
 'Present Perfect':'already|just|not yet|ever — ask a question|never before|since Monday|since breakfast|since last week|since January|since 2020|for two hours — up to now|for three days — up to now|for a week — up to now|so far today|so far this week|up to now|until now|recently|lately|twice this week — so far|three times today — so far|in my life — up to now|this year — so far|since the lesson began|before — at any time in your life',
 'Past Simple':'yesterday|yesterday morning|yesterday afternoon|yesterday evening|last night|last Monday|last week|last month|last year|last summer|two days ago|three weeks ago|an hour ago|five minutes ago|in 2024|in 2020|on my last birthday|during the last school holiday|the day before yesterday|last weekend|after school yesterday|before breakfast yesterday|in January last year|once, a long time ago|when I was five',
 'Past Continuous':'at 5 p.m. yesterday|at noon yesterday|at midnight last night|at 8 a.m. yesterday|this time yesterday|this time last week|when I called — action in progress|when the phone rang — action in progress|when the teacher arrived — action in progress|when the lights went out — action in progress|when it started raining — action in progress|when the door opened — action in progress|when I saw you — action in progress|at that moment yesterday|while I was reading|while Mum was cooking|while Dad was working|while we were waiting|all morning yesterday — ongoing activity|all evening yesterday — ongoing activity|at 3 p.m. last Sunday|at breakfast time yesterday|at 7 p.m. last Friday|as the bus arrived — action in progress|when the music stopped — action in progress',
 'Past Perfect':'before the lesson started|by the time I arrived|before dinner yesterday|before the bus left|by 5 p.m. yesterday|before the rain began|before Mum came home|by the time the film started|before the shop closed|before we went to bed|before the guests arrived|by the end of last week|by the end of last year|before my last birthday|before we moved house|before I met my friend|before the teacher asked|by the time the bell rang|before we left the park|before the party began|already — before I arrived|never — before that day|just — before the phone rang|twice — before last Monday|for an hour — before the bus arrived',
 'Future Simple':'tomorrow|tomorrow morning|tomorrow afternoon|tomorrow evening|next Monday|next week|next month|next year|next summer|in two days|in an hour|in five minutes|one day|someday|soon|later today|tonight — make a prediction|this weekend — make a prediction|in the future|in ten years|on my next birthday|after the lesson — make a promise|when I grow up — make a prediction|next winter|in 2035',
 'Future Continuous':'at 5 p.m. tomorrow|at noon tomorrow|at midnight tomorrow|this time tomorrow|this time next week|this time next month|at 8 a.m. next Monday|at 7 p.m. next Friday|at breakfast time tomorrow|at lunchtime tomorrow|at sunset tomorrow|when you arrive tomorrow — action in progress|when you call tonight — action in progress|while you are travelling tomorrow|while Mum is working tomorrow|all morning tomorrow — ongoing activity|all afternoon tomorrow — ongoing activity|all evening tomorrow — ongoing activity|between 2 and 3 tomorrow|during the journey tomorrow|at 10 a.m. next Saturday|at 6 p.m. next Sunday|this time next year|when the lesson starts tomorrow — action in progress|at this time on my next birthday',
 'Future Perfect':'by tomorrow|by tomorrow morning|by tomorrow evening|by next Friday|by next week|by next month|by next year|by 2030|by noon tomorrow|by 5 p.m. tomorrow|before the lesson starts tomorrow|before the guests arrive tomorrow|by the time you get home tonight|by the time the bus arrives tomorrow|by the end of today|by the end of this week|by the end of this month|by the end of this year|before my next birthday|before the holiday begins|by this time tomorrow|by this time next week|before the shop closes tonight|by the time the film starts tonight|before we leave tomorrow'
};
export const timePools=Object.fromEntries(Object.entries(expressions).map(([key,text])=>[key,text.split('|').map((label,i)=>({id:key+i,label,image:{type:'emoji',value:key.startsWith('Past')?'🕰️':key.startsWith('Future')?'📅':'⏳'}}))]));
