import {contentRepository,contentTypes} from '../shared/content-library.js';
import {activityRegistry} from '../shared/activity/catalog.js';
const host=document.getElementById('authoredContent'),dialog=document.getElementById('createContent');
document.getElementById('create').onclick=()=>dialog.showModal();document.getElementById('cancelCreate').onclick=()=>dialog.close();
for(const [type,name,description] of contentTypes){const a=document.createElement('a');a.className='button';a.href=type==='conceptSet'?'editor.html':'../content/editor.html?type='+type;const strong=document.createElement('strong'),small=document.createElement('span');strong.textContent=name;small.textContent=description;a.append(strong,small);dialog.querySelector('.content-types').append(a);}
export async function refreshContent(){host.replaceChildren();try{for(const item of await contentRepository.list()){const card=document.createElement('article');card.className='set-card';const title=document.createElement('h3'),type=document.createElement('p'),edit=document.createElement('a'),exportButton=document.createElement('button');title.textContent=item.name;type.textContent=contentTypes.find(t=>t[0]===item.content?.type)?.[1]||'Content';edit.textContent='Edit';edit.className='button';edit.href='../content/editor.html?id='+encodeURIComponent(item.id);exportButton.textContent='Export JSON';exportButton.onclick=async()=>{try{const text=await contentRepository.export(item),url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='content.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){document.getElementById('contentNotice').textContent=e.message;}};card.append(title,type,edit,exportButton);for(const game of activityRegistry.games().filter(g=>g.runtime&&g.supportedContentTypes.includes(item.content?.type))){const a=document.createElement('a');a.className='button primary';a.textContent='Play '+game.name;a.href='../'+game.runtime+'?activity='+encodeURIComponent(item.id);card.append(a);}host.append(card);}}catch(e){document.getElementById('contentNotice').textContent=e.message;}}
refreshContent();

if(new URLSearchParams(location.search).has("create"))dialog.showModal();
