// Replace the short synthesized victory sting here after classroom testing.
export const VICTORY_NOTES=[{frequency:523.25,at:0,duration:.22},{frequency:659.25,at:.16,duration:.22},{frequency:783.99,at:.32,duration:.24},{frequency:1046.5,at:.52,duration:.8},{frequency:659.25,at:.52,duration:.8},{frequency:783.99,at:.52,duration:.8}];
let layer,frame,context;
export function clearCelebration(){if(frame!==undefined)cancelAnimationFrame(frame);frame=undefined;layer?.remove();layer=null;}
// Ballistic trajectories in viewport pixels; each cannon has independent variation.
export function cannonParticles(width,height,random=Math.random){return Array.from({length:64},(_,i)=>{const side=i<32?'left':'right',direction=side==='left'?1:-1;return {side,x:side==='left'?width*.02:width*.98,y:height+12,vx:direction*width*(.10+random()*.32),vy:-height*(1.32+random()*.18),gravity:height*1.2,angle:random()*360,spin:(random()-.5)*900,width:5+random()*6,height:8+random()*8};});}
export function particlePosition(p,seconds){return {x:p.x+p.vx*seconds,y:p.y+p.vy*seconds+.5*p.gravity*seconds*seconds,angle:p.angle+p.spin*seconds};}
export function playVictory(){try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;context ||= new Audio();context.resume().catch(()=>{});for(const note of VICTORY_NOTES){const oscillator=context.createOscillator(),gain=context.createGain(),start=context.currentTime+note.at;oscillator.type='sine';oscillator.frequency.value=note.frequency;gain.gain.setValueAtTime(0,start);gain.gain.linearRampToValueAtTime(.035,start+.02);gain.gain.exponentialRampToValueAtTime(.001,start+note.duration);oscillator.connect(gain);gain.connect(context.destination);oscillator.start(start);oscillator.stop(start+note.duration);oscillator.onended=()=>{oscillator.disconnect();gain.disconnect();};}}catch{/* Embedded browsers may disable audio. */}}
export function celebrate(sound){clearCelebration();if(sound)playVictory();if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const width=innerWidth,height=innerHeight,particles=cannonParticles(width,height);layer=document.createElement('div');layer.className='victory-confetti';layer.setAttribute('aria-hidden','true');const colors=['#ef9273','#f7cb58','#73c9cb','#ad91d9','#91ba78'];for(const [i,p] of particles.entries()){const node=document.createElement('i');node.dataset.cannon=p.side;node.style.setProperty('--color',colors[i%colors.length]);node.style.width=p.width+'px';node.style.height=p.height+'px';node.style.transform='translate3d('+p.x+'px,'+p.y+'px,0) rotate('+p.angle+'deg)';p.node=node;layer.append(node);}document.body.append(layer);let start;function tick(now){if(!layer)return;start??=now;const seconds=(now-start)/1000;let active=0;for(const p of particles){const at=particlePosition(p,seconds);if(seconds>.3&&at.y>height+30){p.node.hidden=true;continue;}active++;p.node.style.transform='translate3d('+at.x+'px,'+at.y+'px,0) rotate('+at.angle+'deg)';}if(!active||seconds>3.2){clearCelebration();return;}frame=requestAnimationFrame(tick);}frame=requestAnimationFrame(tick);}
