import {loadDevelopmentFeed,publishedUpdates,activeIssues,roadmapItems,validDate} from './development-data.js';
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;};
function list(records,empty,updates=false){const ul=el('ul',null,'development-list');if(!records.length){const p=el('p',empty,'muted');return p;}for(const item of records){const li=el('li'),meta=el('div',null,'development-meta');if(item.area)meta.append(el('span',item.area));const status=updates?item.type:item.status;if(status)meta.append(el('span',status,'development-status'));if(updates&&validDate(item.date)){const time=el('time',new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(item.date)));time.dateTime=item.date;meta.append(time);}if(updates&&item.version)meta.append(el('span','v'+item.version));li.append(meta,el('h3',item.title||'Update'));if(item.description)li.append(el('p',item.description));ul.append(li);}return ul;}
export function renderDevelopment(host,{data={},full=false,historyURL='updates/'}={}){
 host.replaceChildren();host.classList.add('development-grid');
 const block=(title,id)=>{const section=el('section',null,'development-block');section.id=id;const h=el('h2',title);h.id=id+'Title';section.setAttribute('aria-labelledby',h.id);section.append(h);host.append(section);return section;};
 const updates=publishedUpdates(data),issues=activeIssues(data),news=block(full?'Updates history':"What’s New",'updates');news.append(list(full?updates:updates.slice(0,3),'No updates published yet.',true));if(!full){const a=el('a','View all updates');a.href=historyURL;news.append(a);}
 const known=block('Known Issues','known-issues');known.append(list(full?issues:issues.slice(0,3),'No known issues reported right now.'));if(!full&&issues.length>3){const a=el('a','View all known issues');a.href=historyURL+'#known-issues';known.append(a);}
 const roadmap=block('In Progress / Coming Next','roadmap');for(const status of ['In Progress','Coming Next']){roadmap.append(el('h3',status),list(roadmapItems(data,status),status==='In Progress'?'No development updates announced right now.':'No upcoming updates announced yet.'));}
 const feedback=block('Found a bug? 🐛','feedback');feedback.append(el('p','Something not working? Found a bug or have an idea? Let me know!'));const a=el('a','Message me on Telegram');a.href='https://t.me/moreva_anastasia';feedback.append(a);
}
const host=document.querySelector('[data-development]');if(host){host.textContent='Loading updates…';loadDevelopmentFeed().then(data=>renderDevelopment(host,{data,full:host.dataset.development==='history'})).catch(()=>{host.replaceChildren(el('p','Updates could not be loaded. Please try again later.'));const feedback=el('a','Message me on Telegram');feedback.href='https://t.me/moreva_anastasia';host.append(feedback);});}
