import {createEntityId} from '../activity/contracts.js';
export const id=()=>createEntityId();
export function el(tag,cls='',text){const n=document.createElement(tag);n.className=cls;if(text!==undefined)n.textContent=text;return n;}
export function action(text,fn,disabled=false){const b=el('button','',text);b.type='button';b.disabled=disabled;b.onclick=fn;return b;}
export function input(label,value,onInput,{area=false,type='text'}={}){const wrap=el('label','editor-field',label),field=el(area?'textarea':'input');if(!area)field.type=type;field.value=value??'';if(type==='text'||area)field.maxLength=2000;field.oninput=()=>onInput(field.value);wrap.append(field);return wrap;}
export function capacity(host,title,count,max,label=title){const heading=el('div','editor-capacity-header');host.append(heading);heading.append(el('h3','',title),el('p','editor-capacity',`Max. ${max} ${label.toLowerCase()}`),el('output','editor-count',`${count} / ${max}`));if(count>=max)heading.append(el('p','editor-limit',`You've reached the limit of ${max} ${label.toLowerCase()}.`));}
export function move(array,entity,delta){const i=array.indexOf(entity),next=i+delta;if(next<0||next>=array.length)return;array.splice(i,1);array.splice(next,0,entity);}
export function uploadButton(label,onFile){const file=el('input');file.type='file';file.accept='image/png,image/jpeg,image/webp';file.hidden=true;const b=action(label,()=>file.click());file.onchange=()=>{if(file.files[0])onFile(file.files[0]);file.value='';};const wrap=el('span');wrap.append(b,file);return wrap;}
export function preview(ref,services,alt='Image'){const image=el('img','editor-image');image.alt=alt;if(ref)Promise.resolve(services.mediaURL(ref)).then(url=>{image.src=url;}).catch(()=>{image.alt='Image unavailable';});return image;}
export function baseEditor({host,activity,onChange,services={}},render){let data=structuredClone(activity.content.data),baseline=structuredClone(data),alive=true;const error=el('p','editor-error');error.setAttribute('role','status');const space=el('div','structured-editor');host.append(error,space);const ctx={get data(){return data;},space,services,changed(){onChange?.();},draw(){if(alive){const positions=new Map([...space.querySelectorAll('[data-scroll-key]')].map(n=>[n.dataset.scrollKey,n.scrollTop]));space.replaceChildren();render(ctx);for(const n of space.querySelectorAll('[data-scroll-key]'))if(positions.has(n.dataset.scrollKey))n.scrollTop=positions.get(n.dataset.scrollKey);}},async work(fn,rethrow=false){try{error.textContent='';await fn();if(alive){ctx.changed();ctx.draw();}}catch(e){error.textContent=e.message;if(rethrow)throw e;}},error(message){error.textContent=message;}};ctx.draw();return {read:()=>structuredClone(data),begin(){baseline=structuredClone(data);},commit(){baseline=structuredClone(data);},cancel(){data=structuredClone(baseline);ctx.draw();},destroy(){alive=false;space.replaceChildren();}};}
