import {el,action} from './common.js';
export async function imageFromURL(value){
 let url;try{url=new URL(value);}catch{throw Error('Enter a valid direct image URL.');}
 if(url.protocol!=='https:'&&!(url.protocol==='http:'&&url.origin===location.origin))throw Error('Use an HTTPS image URL.');
 const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),15000);
 try{const response=await fetch(url,{signal:abort.signal,credentials:'omit',referrerPolicy:'no-referrer'});if(!response.ok)throw Error();const blob=await response.blob();if(!['image/png','image/jpeg','image/webp'].includes(blob.type))throw Error();if(blob.size>10*1024*1024)throw Error('Choose an image up to 10 MB.');return new File([blob],'imported-image.'+(blob.type.split('/')[1]),{type:blob.type});}catch(e){if(e.message.includes('10 MB'))throw e;throw Error('Could not import this image. The website may block downloads (CORS). Download it and use Upload file instead.');}finally{clearTimeout(timer);}
}
export function imageInput(label,onFile){return action(label,()=>{
 const dialog=el('dialog','app-dialog image-input-dialog'),title=el('h2','','Add image'),tabs=el('div','editor-row'),body=el('div','image-input-body'),status=el('p','editor-error'),close=action('Cancel',()=>dialog.close());status.setAttribute('role','status');let busy=false,downloading=false;
 async function accept(file){if(busy)return;busy=true;close.disabled=true;status.textContent='Importing…';try{if(!['image/png','image/jpeg','image/webp'].includes(file?.type))throw Error('Choose a PNG, JPEG or WEBP image.');await onFile(file);dialog.close();}catch(e){status.textContent=e.message;}finally{busy=false;close.disabled=false;}}
 const file=el('input');file.type='file';file.accept='image/png,image/jpeg,image/webp';file.setAttribute('aria-label','Upload image file');file.onchange=()=>{if(file.files[0])accept(file.files[0]);};
 function show(mode){body.replaceChildren();status.textContent='';if(mode==='file'){body.append(el('p','','PNG, JPEG or WEBP · up to 10 MB'),file);}else if(mode==='paste'){const zone=el('div','image-paste-zone','Click here, then press Ctrl+V (⌘V on Mac) to paste an image.');zone.tabIndex=0;zone.setAttribute('role','group');zone.setAttribute('aria-label','Paste image here');zone.onpaste=e=>{const image=[...e.clipboardData.items].find(i=>i.kind==='file'&&i.type.startsWith('image/'));if(!image){status.textContent='The clipboard has no image. Copy an image, then paste here.';return;}e.preventDefault();accept(image.getAsFile());};body.append(zone);zone.focus();}else{const label=el('label','editor-field','Image URL'),url=el('input');url.type='url';url.placeholder='https://…';label.append(url);body.append(label,action('Import image',async()=>{if(busy||downloading)return;downloading=true;status.textContent='Downloading image…';try{const file=await imageFromURL(url.value);if(dialog.isConnected)await accept(file);}catch(e){status.textContent=e.message;}finally{downloading=false;}}),el('p','editor-capacity','The image is copied into your local library. Some websites block imports.'));}}
 tabs.append(action('Upload file',()=>show('file')),action('Paste from clipboard',()=>show('paste')),action('From URL',()=>show('url')));dialog.append(title,tabs,body,status,close);document.body.append(dialog);dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});dialog.addEventListener('close',()=>dialog.remove(),{once:true});show('file');dialog.showModal();
 });}

