import {upgradeScene,objectRect} from '../activity/scene.js';
import {CONTENT_LIMITS as L,enforceLimit} from '../activity/limits.js';
import {entityIndex,validateReferences,normalizedRect} from '../activity/contracts.js';
import {validateMediaRef} from '../activity/media.js';
const array=(v,label)=>{if(!Array.isArray(v))throw Error(label+' must be a list.');entityIndex(v);return v;};
const text=(v,label)=>{if(typeof v!=='string'||!v.trim())throw Error('Enter '+label+'.');};
export const emptyContent={bridge:()=>({bridges:[]}),scene:()=>({background:null,assets:[],objects:[],hotspots:[],targets:[]}),sentenceCorrection:()=>({sentences:[]}),cardDecks:()=>({decks:[]})};
export function validateBridge(data){const bridges=array(data.bridges,'Bridges');enforceLimit(bridges.length,L.bridge.bridges,'Bridges');if(!bridges.length)throw Error('Add a bridge.');for(const b of bridges){const bricks=entityIndex(array(b.bricks,'Bricks'));if(!bricks.size)throw Error('Add a brick.');b.bricks.forEach(x=>text(x.text,'brick text'));const groups=entityIndex(array(b.groups,'Groups'));groups.forEach(g=>array(g.distractors,'Distractors').forEach(d=>text(d.text,'distractor')));const gaps=array(b.gaps,'Gaps');enforceLimit(gaps.length,L.bridge.gapsPerBridge,'Gaps per bridge');if(!gaps.length)throw Error('Select at least one gap in each bridge.');const seen=new Set();for(const g of gaps){validateReferences([g.brickId],bricks);validateReferences([g.groupId],groups);if(seen.has(g.brickId))throw Error('A brick can have only one gap.');seen.add(g.brickId);}}return data;}
export function validateScene(source){const data=upgradeScene(source);if(!data.background)throw Error('Upload a background.');validateMediaRef(data.background);const assets=entityIndex(array(data.assets,'Assets')),objects=entityIndex(array(data.objects,'Scene objects')),hotspots=entityIndex(array(data.hotspots,'Hotspots'));enforceLimit(assets.size,L.scene.assets,'Elements');enforceLimit(objects.size,L.scene.instances,'Placed objects');enforceLimit(hotspots.size,L.scene.hotspots,'Hotspots');assets.forEach(a=>validateMediaRef(a.media));objects.forEach(o=>{validateReferences([o.assetId],assets);objectRect(o);});hotspots.forEach(h=>{normalizedRect(h);if(!h.width||!h.height)throw Error('Hotspots need a visible size.');});const targets=array(data.targets,'Targets');enforceLimit(targets.length,L.scene.targets,'Targets');for(const t of targets){text(t.prompt,'target prompt');const answers=array(t.answers,'Answers');if(!answers.length)throw Error('Select an answer for each target.');const seen=new Set();for(const a of answers){if(!['object','hotspot'].includes(a.type))throw Error('Unsupported answer type.');const ref=a.type==='object'?a.sceneObjectId:a.hotspotId;validateReferences([ref],a.type==='object'?objects:hotspots);const key=a.type+':'+ref;if(seen.has(key))throw Error('Duplicate target answer.');seen.add(key);}}return data;}
export function validateSentences(data){const sentences=array(data.sentences,'Sentences');enforceLimit(sentences.length,L.sentenceCorrection.sentences,'Sentences');if(!sentences.length)throw Error('Add a sentence.');for(const s of sentences){text(s.incorrect,'incorrect sentence');text(s.correct,'correct sentence');if(s.incorrect.trim()===s.correct.trim())throw Error('Incorrect and Correct sentences must differ.');}return data;}
export function validateDecks(data,{previousDeckCount=0}={}){const decks=array(data.decks,'Decks');enforceLimit(decks.length,Math.max(L.cardDecks.decks,previousDeckCount),'Decks');if(!decks.length)throw Error('Add a deck.');let total=0;const ids=new Set();for(const d of decks){text(d.name,'deck name');if(!/^#[0-9a-f]{6}$/i.test(d.color))throw Error('Choose a deck color.');const cards=array(d.cards,'Cards');enforceLimit(cards.length,L.cardDecks.cardsPerDeck,'Cards per deck');total+=cards.length;for(const c of cards){if(ids.has(c.id))throw Error('Duplicate card ID.');ids.add(c.id);if(typeof c.text!=='string'||(!c.text.trim()&&!c.image))throw Error('Add card text or an image.');if(c.image)validateMediaRef(c.image);}}enforceLimit(total,L.cardDecks.cardsTotal,'Cards total');return data;}
// Token LCS: insertions/deletions and multiple independent corrections. Editor only.
export function sentenceDiff(a,b){const tokenize=s=>s.match(/\s+|[\p{L}\p{N}]+(?:['’][\p{L}\p{N}]+)*|[^\s]/gu)||[];const left=tokenize(a),right=tokenize(b);if(left.length*right.length>250000)return {left:[{text:a,changed:a!==b}],right:[{text:b,changed:a!==b}]};const rows=Array.from({length:left.length+1},()=>new Uint16Array(right.length+1));for(let i=left.length-1;i>=0;i--)for(let j=right.length-1;j>=0;j--)rows[i][j]=left[i]===right[j]?1+rows[i+1][j+1]:Math.max(rows[i+1][j],rows[i][j+1]);const result={left:[],right:[]};let i=0,j=0;while(i<left.length||j<right.length){if(i<left.length&&j<right.length&&left[i]===right[j]){result.left.push({text:left[i++],changed:false});result.right.push({text:right[j++],changed:false});}else if(i<left.length&&(j===right.length||rows[i+1][j]>=rows[i][j+1]))result.left.push({text:left[i++],changed:true});else result.right.push({text:right[j++],changed:true});}return result;}
export const validators={bridge:validateBridge,scene:validateScene,sentenceCorrection:validateSentences,cardDecks:validateDecks};
