import {baseEditor,el,action,input,capacity,id,uploadButton,preview} from './common.js';
import {CONTENT_LIMITS as L} from '../activity/limits.js';
export function mountSceneEditor(options){let selected=null,targetId=null,choosing=false;return baseEditor(options,c=>{const d=c.data;capacity(c.space,'Scene elements',d.objects.length,L.scene.instances,'scene elements');c.space.append(el('p','editor-capacity',`Max. ${L.scene.targets} targets per scene`));if(!d.background){const empty=el('section','editor-section');empty.append(el('h3','','Create a scene'),el('p','','Upload a background to get started.'),uploadButton('+ Add background',file=>c.work(async()=>{d.background=await c.services.upload(file);})));c.space.append(empty);return;}
 const actions=el('div','editor-row');actions.append(uploadButton('Replace background',file=>c.work(async()=>{d.background=await c.services.upload(file);})),action('Remove background',()=>{d.background=null;choosing=false;c.changed();c.draw();}));c.space.append(actions);
 const selectedTarget=d.targets.find(t=>t.id===targetId);if(choosing&&selectedTarget){const selection=el('div','scene-selection');selection.append(el('strong','','Select the correct object(s)'),el('span','',`${selectedTarget.objectIds.length} selected`),action('Done',()=>{choosing=false;c.draw();}));c.space.append(selection);}
 const layout=el('div','scene-layout'),canvas=el('div','scene-canvas');canvas.setAttribute('aria-label','Scene canvas');const bg=preview(d.background,c.services,'Scene background');bg.className='scene-background';bg.onload=()=>{canvas.style.aspectRatio=`${bg.naturalWidth} / ${bg.naturalHeight}`;};canvas.append(bg);layout.append(canvas);
 function addInstance(asset,x,y){if(d.objects.length>=L.scene.instances)return;const size=.15,obj={id:id(),assetId:asset.id,x:Math.max(0,Math.min(1-size,x-size/2)),y:Math.max(0,Math.min(1-size,y-size/2)),width:size,height:size};d.objects.push(obj);selected=obj.id;c.changed();c.draw();}
 for(const object of d.objects){const asset=d.assets.find(a=>a.id===object.assetId);if(!asset)continue;const node=el('div','scene-object');node.tabIndex=0;node.setAttribute('role','button');node.setAttribute('aria-label',asset.name||'Scene element');const setStyle=()=>Object.assign(node.style,{left:object.x*100+'%',top:object.y*100+'%',width:object.width*100+'%',height:object.height*100+'%'});setStyle();node.classList.toggle('selected',object.id===selected);node.classList.toggle('answer',!!selectedTarget?.objectIds.includes(object.id));node.setAttribute('aria-pressed',String(choosing?!!selectedTarget?.objectIds.includes(object.id):object.id===selected));node.append(preview(asset.media,c.services,asset.name));
 function toggle(){if(choosing&&selectedTarget){selectedTarget.objectIds=selectedTarget.objectIds.includes(object.id)?selectedTarget.objectIds.filter(v=>v!==object.id):[...selectedTarget.objectIds,object.id];c.changed();}else selected=object.id;c.draw();}
 node.onclick=()=>{if(choosing)toggle();};node.onkeydown=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();toggle();}};
 function pointer(e,resize=false){if(choosing||e.button!==0)return;e.preventDefault();e.stopPropagation();selected=object.id;node.classList.add('selected');const rect=canvas.getBoundingClientRect();node.setPointerCapture(e.pointerId);const sx=e.clientX,sy=e.clientY,ox=object.x,oy=object.y,ow=object.width,oh=object.height;node.onpointermove=event=>{const dx=(event.clientX-sx)/rect.width,dy=(event.clientY-sy)/rect.height;if(resize){object.width=Math.max(.025,Math.min(1-ox,ow+dx));object.height=Math.max(.025,Math.min(1-oy,oh+dy));}else{object.x=Math.max(0,Math.min(1-ow,ox+dx));object.y=Math.max(0,Math.min(1-oh,oy+dy));}setStyle();};node.onpointerup=node.onpointercancel=()=>{node.onpointermove=null;c.changed();c.draw();};}
 node.onpointerdown=e=>pointer(e);if(object.id===selected&&!choosing){const handle=el('span','scene-resize','↘');handle.setAttribute('aria-label','Drag to resize');handle.onpointerdown=e=>pointer(e,true);node.append(handle);}canvas.append(node);
 }
 const palette=el('aside','scene-palette');palette.append(el('h4','','Elements'),el('p','','Drag elements onto the scene'),uploadButton('+ Upload',file=>c.work(async()=>{const media=await c.services.upload(file);d.assets.push({id:id(),name:file.name,media});})));for(const asset of d.assets){const sticker=action('',()=>{} ,d.objects.length>=L.scene.instances);sticker.className='scene-sticker';sticker.setAttribute('aria-label','Drag '+asset.name);sticker.append(preview(asset.media,c.services,asset.name));sticker.onpointerdown=e=>{if(sticker.disabled||e.button!==0)return;e.preventDefault();sticker.setPointerCapture(e.pointerId);const ghost=sticker.cloneNode(true);ghost.className='sticker-ghost';ghost.style.left=e.clientX+'px';ghost.style.top=e.clientY+'px';document.body.append(ghost);sticker.onpointermove=p=>{ghost.style.left=p.clientX+'px';ghost.style.top=p.clientY+'px';};sticker.onpointerup=p=>{ghost.remove();sticker.onpointermove=null;const r=canvas.getBoundingClientRect();if(p.clientX>=r.left&&p.clientX<=r.right&&p.clientY>=r.top&&p.clientY<=r.bottom)addInstance(asset,(p.clientX-r.left)/r.width,(p.clientY-r.top)/r.height);};sticker.onpointercancel=()=>ghost.remove();};palette.append(sticker,action('Remove asset',()=>{if(d.objects.some(o=>o.assetId===asset.id)){c.error('Remove its scene instances first.');return;}d.assets=d.assets.filter(a=>a.id!==asset.id);c.changed();c.draw();}));}palette.append(el('p','editor-capacity','Scatter: coming later. Quantity will count toward the scene element limit.'));layout.append(palette);c.space.append(layout);
 const obj=d.objects.find(o=>o.id===selected);if(obj&&!choosing){const tools=el('div','editor-row');tools.append(action('Duplicate element',()=>{if(d.objects.length>=L.scene.instances)return;const copy={...obj,id:id(),x:Math.min(1-obj.width,obj.x+.03),y:Math.min(1-obj.height,obj.y+.03)};d.objects.push(copy);selected=copy.id;c.changed();c.draw();},d.objects.length>=L.scene.instances),action('Delete element',()=>{d.objects=d.objects.filter(o=>o.id!==obj.id);d.targets.forEach(t=>t.objectIds=t.objectIds.filter(v=>v!==obj.id));selected=null;c.changed();c.draw();}));for(const key of ['x','y','width','height'])tools.append(input(key+' (%)',Math.round(obj[key]*100),value=>{const n=Number(value)/100;if(!Number.isFinite(n)||n<0||n>1)return;obj[key]=key==='width'||key==='height'?Math.max(.025,n):Math.min(.975,n);obj.width=Math.min(obj.width,1-obj.x);obj.height=Math.min(obj.height,1-obj.y);c.changed();},{type:'number'}));tools.append(action('Apply position / size',()=>c.draw()));c.space.append(tools);}
 const targets=el('section','editor-section');capacity(targets,'Targets',d.targets.length,L.scene.targets,'targets');for(const target of d.targets){const row=el('div','target-card');row.classList.toggle('selected',target.id===targetId);row.append(input('Prompt',target.prompt,v=>{target.prompt=v;c.changed();},{area:true}),action('Edit / highlight',()=>{targetId=target.id;choosing=false;c.draw();}),action('+ Select from scene',()=>{targetId=target.id;choosing=true;c.draw();canvas.scrollIntoView({block:'nearest'});}));const thumbnails=el('div','target-thumbnails');for(const objectId of target.objectIds){const object=d.objects.find(o=>o.id===objectId),asset=d.assets.find(a=>a.id===object?.assetId);if(asset)thumbnails.append(preview(asset.media,c.services,asset.name));}row.append(thumbnails,el('p','',`${target.objectIds.length} answers`),action('Delete target',()=>{d.targets=d.targets.filter(t=>t.id!==target.id);if(targetId===target.id){targetId=null;choosing=false;}c.changed();c.draw();}));targets.append(row);}targets.append(action('+ Add target',()=>{if(d.targets.length>=L.scene.targets)return;const target={id:id(),prompt:'',objectIds:[]};d.targets.push(target);targetId=target.id;c.changed();c.draw();},d.targets.length>=L.scene.targets));c.space.append(targets);
 });}
