import {imageInput} from './image-input.js';
import {baseEditor,el,action,input,capacity,id,uploadButton,preview} from './common.js';
import {CONTENT_LIMITS as L} from '../activity/limits.js';
import {upgradeScene,clampObject} from '../activity/scene.js';
export function mountSceneEditor(options){
 options={...options,activity:{...options.activity,content:{...options.activity.content,data:upgradeScene(options.activity.content.data)}}};
 let selected=null,selectedType='object',targetId=null,choosing=false,tool='object',assetId=null,focusTarget=null,sceneRatio=4/3,observer;
 const controller=baseEditor(options,c=>{
 observer?.disconnect();const d=c.data,target=d.targets.find(t=>t.id===targetId),changed=()=>{c.changed();c.draw();};
 const uploadBackground=file=>c.work(async()=>{d.background=await c.services.upload(file,{original:true});},true);
 if(!d.background){const empty=el('section','editor-section');empty.append(el('h3','','Create a scene'),el('p','','Upload a background. Use a ready-made image with hotspots, or add separate elements.'),imageInput('+ Add image',uploadBackground));c.space.append(empty);return;}
 const top=el('div','editor-row');top.append(imageInput('Change background',uploadBackground),el('span','editor-capacity','Original background resolution is preserved. Max. 50 elements · 50 placed objects · 100 hotspots · 20 targets'));c.space.append(top);
 if(choosing&&target){const bar=el('div','scene-selection');bar.append(el('strong','',tool==='hotspot'?'Draw regions over the background':'Select the correct objects or existing regions'),el('span','',`${target.answers.length} selected`),action('Select objects',()=>{tool='object';c.draw();}),action('Draw hotspots',()=>{tool='hotspot';c.draw();},d.hotspots.length>=L.scene.hotspots),action('Done',()=>{choosing=false;c.draw();}));c.space.append(bar);}
 const workspace=el('div','scene-workspace'),left=el('div','scene-left'),layout=el('div','scene-layout'),stage=el('div','scene-stage'),canvas=el('div','scene-canvas');canvas.style.aspectRatio=String(sceneRatio);canvas.setAttribute('aria-label','Scene canvas');canvas.dataset.tool=choosing?tool:'move';const bg=preview(d.background,c.services,'Scene background');bg.className='scene-background';const fit=()=>{const w=Math.min(stage.clientWidth,stage.clientHeight*sceneRatio);if(w>0){canvas.style.width=w+'px';canvas.style.height=w/sceneRatio+'px';}};bg.onload=()=>{sceneRatio=bg.naturalWidth/bg.naturalHeight;canvas.style.aspectRatio=String(sceneRatio);fit();};canvas.append(bg);stage.append(canvas);layout.append(stage);observer=new ResizeObserver(fit);observer.observe(stage);requestAnimationFrame(fit);
 const assigned=(type,entityId)=>target?.answers.some(a=>a.type===type&&(type==='object'?a.sceneObjectId:a.hotspotId)===entityId);
 function toggle(type,entityId){if(!target)return;const key=type==='object'?'sceneObjectId':'hotspotId';if(assigned(type,entityId))target.answers=target.answers.filter(a=>!(a.type===type&&a[key]===entityId));else target.answers.push({id:id(),type,[key]:entityId});changed();}
 function addInstance(asset,x=.5,y=.5){if(d.objects.length>=L.scene.instances)return;const obj=clampObject({id:id(),assetId:asset.id,x:x-.075,y:y-.075,width:.15,height:.15});d.objects.push(obj);selected=obj.id;selectedType='object';changed();}
 function drawEntity(entity,type){const asset=type==='object'?d.assets.find(a=>a.id===entity.assetId):null;if(type==='object'&&!asset)return;const node=el('div',type==='object'?'scene-object':'scene-hotspot');node.dataset.entityId=entity.id;node.tabIndex=0;node.setAttribute('role','button');node.setAttribute('aria-label',type==='object'?asset.name||'Scene object':'Hotspot');const style=()=>Object.assign(node.style,{left:entity.x*100+'%',top:entity.y*100+'%',width:entity.width*100+'%',height:entity.height*100+'%'});style();node.classList.toggle('selected',selected===entity.id&&selectedType===type);node.classList.toggle('answer',!!assigned(type,entity.id));if(asset)node.append(preview(asset.media,c.services,asset.name));
 const choose=()=>{if(choosing){if(tool==='object')toggle(type,entity.id);}else{selected=entity.id;selectedType=type;c.draw();}};node.onclick=()=>{if(choosing&&tool==='object')choose();};node.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose();}};
 function pointer(e,resize=false){if(choosing||e.button!==0)return;e.preventDefault();e.stopPropagation();selected=entity.id;selectedType=type;node.classList.add('selected');node.setPointerCapture(e.pointerId);const r=canvas.getBoundingClientRect(),start={...entity},sx=e.clientX,sy=e.clientY;node.onpointermove=p=>{const dx=(p.clientX-sx)/r.width,dy=(p.clientY-sy)/r.height;if(resize){entity.width=Math.max(.01,Math.min(type==='hotspot'?1-start.x:1,start.width+dx));entity.height=Math.max(.01,Math.min(type==='hotspot'?1-start.y:1,start.height+dy));}else{entity.x=start.x+dx;entity.y=start.y+dy;}if(type==='object')clampObject(entity);else{entity.x=Math.max(0,Math.min(1-entity.width,entity.x));entity.y=Math.max(0,Math.min(1-entity.height,entity.y));}style();};node.onpointerup=node.onpointercancel=()=>{node.onpointermove=null;changed();};}
 node.onpointerdown=e=>pointer(e);if(selected===entity.id&&!choosing){const handle=el('span','scene-resize','↘');handle.setAttribute('aria-label','Drag to resize');handle.onpointerdown=e=>pointer(e,true);node.append(handle);}canvas.append(node);}
 d.objects.forEach(o=>drawEntity(o,'object'));d.hotspots.forEach(h=>drawEntity(h,'hotspot'));
 canvas.onpointerdown=e=>{if(!choosing||tool!=='hotspot'||!target||e.button!==0||d.hotspots.length>=L.scene.hotspots)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);const r=canvas.getBoundingClientRect(),point=p=>({x:Math.max(0,Math.min(1,(p.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(p.clientY-r.top)/r.height))}),start=point(e);const box=el('div','scene-hotspot drawing');canvas.append(box);let end=start;canvas.onpointermove=p=>{end=point(p);Object.assign(box.style,{left:Math.min(start.x,end.x)*100+'%',top:Math.min(start.y,end.y)*100+'%',width:Math.abs(end.x-start.x)*100+'%',height:Math.abs(end.y-start.y)*100+'%'});};canvas.onpointerup=p=>{end=point(p);canvas.onpointermove=null;const h={id:id(),x:Math.min(start.x,end.x),y:Math.min(start.y,end.y),width:Math.abs(end.x-start.x),height:Math.abs(end.y-start.y)};if(h.width>=.01&&h.height>=.01){d.hotspots.push(h);target.answers.push({id:id(),type:'hotspot',hotspotId:h.id});selected=h.id;selectedType='hotspot';changed();}else box.remove();};canvas.onpointercancel=()=>{canvas.onpointermove=null;box.remove();};};
 const palette=el('aside','scene-palette');capacity(palette,'Elements',d.assets.length,L.scene.assets,'elements');palette.append(el('p','editor-capacity','Drag to place, or select then Add to scene.'));if(d.assets.length<L.scene.assets)palette.append(imageInput('+ Add image',file=>c.work(async()=>{if(d.assets.length>=L.scene.assets)return;const media=await c.services.upload(file,{original:true});d.assets.push({id:id(),name:file.name,media});},true)));const grid=el('div','scene-asset-grid');grid.dataset.scrollKey='assets';
 for(const asset of d.assets){const sticker=action('',()=>{assetId=asset.id;c.draw();});sticker.className='scene-sticker';sticker.setAttribute('aria-label',asset.name);sticker.setAttribute('aria-pressed',String(assetId===asset.id));sticker.append(preview(asset.media,c.services,asset.name));sticker.onpointerdown=e=>{if(e.button!==0||d.objects.length>=L.scene.instances)return;sticker.setPointerCapture(e.pointerId);const sx=e.clientX,sy=e.clientY;let dragged=false;sticker.onpointermove=p=>{if(Math.hypot(p.clientX-sx,p.clientY-sy)>6)dragged=true;};sticker.onpointerup=p=>{sticker.onpointermove=null;if(!dragged)return;const r=canvas.getBoundingClientRect();if(p.clientX>=r.left&&p.clientX<=r.right&&p.clientY>=r.top&&p.clientY<=r.bottom)addInstance(asset,(p.clientX-r.left)/r.width,(p.clientY-r.top)/r.height);};};grid.append(sticker);}palette.append(grid);const selectedAsset=d.assets.find(a=>a.id===assetId);if(selectedAsset){const controls=el('div','editor-row');controls.append(action('Add to scene',()=>addInstance(selectedAsset),d.objects.length>=L.scene.instances),action('Remove asset',()=>{if(d.objects.some(o=>o.assetId===assetId)){c.error('Remove its placed objects first.');return;}d.assets=d.assets.filter(a=>a.id!==assetId);assetId=null;changed();}));palette.append(controls);}layout.append(palette);c.space.append(layout);
 const entity=(selectedType==='object'?d.objects:d.hotspots).find(o=>o.id===selected);if(entity&&!choosing){const controls=el('div','editor-row scene-object-tools');controls.append(el('strong','',selectedType==='object'?'Selected object':'Selected hotspot'));if(selectedType==='object')controls.append(action('Duplicate element',()=>{const copy=clampObject({...entity,id:id(),x:entity.x+.03,y:entity.y+.03});d.objects.push(copy);selected=copy.id;changed();},d.objects.length>=L.scene.instances));controls.append(action(selectedType==='object'?'Delete element':'Delete hotspot',()=>{const key=selectedType==='object'?'objects':'hotspots',ref=selectedType==='object'?'sceneObjectId':'hotspotId';d[key]=d[key].filter(o=>o.id!==entity.id);d.targets.forEach(t=>t.answers=t.answers.filter(a=>a[ref]!==entity.id));selected=null;changed();}));for(const key of ['x','y','width','height'])controls.append(input(key+' (%)',Math.round(entity[key]*100),value=>{const n=Number(value)/100;if(!Number.isFinite(n))return;entity[key]=n;if(selectedType==='object')clampObject(entity);else{entity.width=Math.max(.01,Math.min(1,entity.width));entity.height=Math.max(.01,Math.min(1,entity.height));entity.x=Math.max(0,Math.min(1-entity.width,entity.x));entity.y=Math.max(0,Math.min(1-entity.height,entity.y));}c.changed();},{type:'number'}));controls.append(action('Apply position / size',()=>c.draw()));c.space.append(controls);}
 const targets=el('section','editor-section scene-targets');targets.dataset.scrollKey='targets';capacity(targets,'Targets',d.targets.length,L.scene.targets,'targets');for(const t of d.targets){const row=el('div','target-card');row.dataset.targetId=t.id;const thumbs=el('div','target-thumbnails');for(const a of t.answers.slice(0,4)){if(a.type==='hotspot')thumbs.append(el('span','hotspot-marker','▣'));else{const o=d.objects.find(x=>x.id===a.sceneObjectId),asset=d.assets.find(x=>x.id===o?.assetId);if(asset)thumbs.append(preview(asset.media,c.services,asset.name));}}if(t.answers.length>4)thumbs.append(el('span','',`+${t.answers.length-4}`));const summary=el('div','target-summary');summary.append(el('strong','',t.prompt||'New target'),thumbs,el('span','',`${t.answers.length} answers`),action('Edit',()=>{targetId=t.id;choosing=false;c.draw();}));const menu=el('details','target-menu');menu.append(el('summary','','⋮'),action('Delete target',()=>{d.targets=d.targets.filter(x=>x.id!==t.id);if(targetId===t.id){targetId=null;choosing=false;}changed();}));summary.append(menu);row.append(summary);
 if(t.id===targetId){row.classList.add('selected');row.append(input('Prompt',t.prompt,v=>{t.prompt=v;c.changed();},{area:true}),el('p','',`Answers · ${t.answers.length} — Objects: ${t.answers.filter(a=>a.type==='object').length} · Hotspots: ${t.answers.filter(a=>a.type==='hotspot').length} regions`),action('Select from scene',()=>{choosing=true;tool='object';c.draw();}),action('Done',()=>{targetId=null;choosing=false;c.draw();}));}targets.append(row);}
 targets.append(action('+ Add target',()=>{const t={id:id(),prompt:'',answers:[]};d.targets.push(t);targetId=t.id;focusTarget=t.id;choosing=false;changed();},d.targets.length>=L.scene.targets));const controlbar=el('div','scene-controlbar'),selection=c.space.querySelector('.scene-selection');if(selection)controlbar.append(selection);else controlbar.append(el('span','editor-capacity','Select and move objects or edit a target to choose answers.'));const tools=c.space.querySelector('.scene-object-tools');const toolSlot=el('div','scene-tools-slot');left.append(controlbar,layout,toolSlot);if(tools)toolSlot.append(tools);workspace.append(left,targets);c.space.append(workspace);if(focusTarget){const row=[...targets.querySelectorAll('.target-card')].find(n=>n.dataset.targetId===focusTarget);focusTarget=null;requestAnimationFrame(()=>{targets.scrollTop+=row.getBoundingClientRect().top-targets.getBoundingClientRect().top;row.querySelector('textarea')?.focus({preventScroll:true});});}
 });
 const destroy=controller.destroy;controller.destroy=()=>{observer?.disconnect();destroy();};return controller;
}
