import {prepareSceneContent} from './scene-prepare.js';
import {baseEditor,el,action,input,id,preview} from './common.js';
import {CONTENT_LIMITS as L} from '../activity/limits.js';
import {upgradeScene,clampObject} from '../activity/scene.js';
export function mountSceneEditor(options){
 options={...options,activity:{...options.activity,content:{...options.activity.content,data:upgradeScene(options.activity.content.data)}}};
 let selected=null,selectedType='object',targetId=null,choosing=false,tool='object',sceneRatio=4/3,observer;let step=1,zoom=1,scroll={left:0,top:0};
 const controller=baseEditor(options,c=>{
 observer?.disconnect();const d=c.data;let target=d.targets.find(t=>t.id===targetId);const changed=()=>{c.changed();c.draw();};
 const uploadBackground=file=>c.work(async()=>{d.background=await c.services.upload(file,{original:true});zoom=1;scroll={left:0,top:0};},true);
 if(step===1){prepareSceneContent(c,{uploadBackground,next:()=>{step=2;targetId??=d.targets[0]?.id;c.draw();}});return;}
 if(!target){target=d.targets[0];targetId=target?.id;}
 c.space.dataset.sceneStep='arrange';
 const workspace=el('div','scene-workspace'),left=el('div','scene-left'),layout=el('div','scene-layout'),stage=el('div','scene-stage'),canvas=el('div','scene-canvas');canvas.style.aspectRatio=String(sceneRatio);canvas.setAttribute('aria-label','Scene canvas');canvas.dataset.tool=choosing?tool:'move';const bg=preview(d.background,c.services,'Scene background');bg.className='scene-background';const fit=()=>{if(!stage.clientWidth)return;const w=stage.clientWidth*zoom;Object.assign(canvas.style,{width:w+'px',height:w/sceneRatio+'px',left:'0px',top:'0px'});};bg.onload=()=>{sceneRatio=bg.naturalWidth/bg.naturalHeight;canvas.style.aspectRatio=String(sceneRatio);fit();};canvas.append(bg);stage.append(canvas);const viewbar=el('div','editor-row scene-view-tools'),level=el('output','','100%');
 const refreshView=()=>{fit();level.textContent=Math.round(zoom*100)+'%';out.disabled=zoom<=1;into.disabled=zoom>=4;};
 const changeZoom=factor=>{const old=zoom;zoom=Math.max(1,Math.min(4,zoom*factor));const x=(stage.scrollLeft+stage.clientWidth/2)/old,y=(stage.scrollTop+stage.clientHeight/2)/old;refreshView();stage.scrollLeft=x*zoom-stage.clientWidth/2;stage.scrollTop=y*zoom-stage.clientHeight/2;};
 const out=action('−',()=>changeZoom(1/1.25)),into=action('+',()=>changeZoom(1.25));out.setAttribute('aria-label','Zoom out');into.setAttribute('aria-label','Zoom in');
 const reset=()=>{zoom=1;refreshView();stage.scrollLeft=stage.scrollTop=0;};
 viewbar.append(out,level,into,action('Fit to width',reset),action('Reset view',reset));layout.append(viewbar,stage);refreshView();
 stage.dataset.scrollKey='scene-stage';stage.addEventListener('scroll',()=>{scroll={left:stage.scrollLeft,top:stage.scrollTop};});requestAnimationFrame(()=>{stage.scrollLeft=scroll.left;stage.scrollTop=scroll.top;});
 let panning=false;
 stage.addEventListener('pointerdown',e=>{const entity=e.target.closest('[data-entity-id]');const touchPan=e.pointerType==='touch'&&!choosing&&(!entity||entity.dataset.entityId!==selected);if(e.button!==2&&!touchPan)return;e.preventDefault();e.stopPropagation();stage.setPointerCapture(e.pointerId);const sx=e.clientX,sy=e.clientY,l=stage.scrollLeft,t=stage.scrollTop;panning=false;stage.onpointermove=p=>{if(Math.hypot(p.clientX-sx,p.clientY-sy)>4)panning=true;stage.scrollLeft=l+sx-p.clientX;stage.scrollTop=t+sy-p.clientY;};stage.onpointerup=p=>{stage.onpointermove=null;if(!panning&&entity&&e.button!==2){selected=entity.dataset.entityId;selectedType=entity.classList.contains('scene-object')?'object':'hotspot';c.draw();}};stage.onpointercancel=()=>{stage.onpointermove=null;panning=true;};},true);
 stage.addEventListener('contextmenu',e=>{if(panning){e.preventDefault();panning=false;}});
 stage.addEventListener('click',e=>{if(panning){e.preventDefault();e.stopPropagation();panning=false;}},true);
 observer=new ResizeObserver(fit);observer.observe(stage);requestAnimationFrame(fit);
 const assigned=(type,entityId)=>target?.answers.some(a=>a.type===type&&(type==='object'?a.sceneObjectId:a.hotspotId)===entityId);
 function toggle(type,entityId){if(!target)return;const key=type==='object'?'sceneObjectId':'hotspotId';if(assigned(type,entityId))target.answers=target.answers.filter(a=>!(a.type===type&&a[key]===entityId));else target.answers.push({id:id(),type,[key]:entityId});c.changed();refreshLinks();}
 function addInstance(asset,x=.5,y=.5){if(d.objects.length>=L.scene.instances)return;const obj=clampObject({id:id(),assetId:asset.id,x:x-.075,y:y-.075,width:.15,height:.15});d.objects.push(obj);selected=obj.id;selectedType='object';changed();}
 function drawEntity(entity,type){const asset=type==='object'?d.assets.find(a=>a.id===entity.assetId):null;if(type==='object'&&!asset)return;const node=el('div',type==='object'?'scene-object':'scene-hotspot');node.dataset.entityId=entity.id;node.tabIndex=0;node.setAttribute('role','button');node.setAttribute('aria-label',type==='object'?asset.name||'Scene object':'Hotspot');const style=()=>Object.assign(node.style,{left:entity.x*100+'%',top:entity.y*100+'%',width:entity.width*100+'%',height:entity.height*100+'%'});style();node.classList.toggle('selected',selected===entity.id&&selectedType===type);node.classList.toggle('answer',!!assigned(type,entity.id));node.classList.toggle('available',type==='object'&&choosing&&tool==='object'&&!assigned(type,entity.id));if(asset)node.append(preview(asset.media,c.services,asset.name));
 const choose=()=>{if(panning)return;if(choosing){if(tool==='object')toggle(type,entity.id);}else{selected=entity.id;selectedType=type;c.draw();}};node.onclick=()=>{if(choosing&&tool==='object')choose();};node.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose();}};
 function pointer(e,resize=false){if(choosing||e.button!==0)return;e.preventDefault();e.stopPropagation();selected=entity.id;selectedType=type;node.classList.add('selected');node.setPointerCapture(e.pointerId);const r=canvas.getBoundingClientRect(),start={...entity},sx=e.clientX,sy=e.clientY;node.onpointermove=p=>{const dx=(p.clientX-sx)/r.width,dy=(p.clientY-sy)/r.height;if(resize){entity.width=Math.max(.01,Math.min(type==='hotspot'?1-start.x:1,start.width+dx));entity.height=type==='object'?Math.max(.01,Math.min(1,start.height*entity.width/start.width)):Math.max(.01,Math.min(1-start.y,start.height+dy));}else{entity.x=start.x+dx;entity.y=start.y+dy;}if(type==='object')clampObject(entity);else{entity.x=Math.max(0,Math.min(1-entity.width,entity.x));entity.y=Math.max(0,Math.min(1-entity.height,entity.y));}style();};node.onpointerup=node.onpointercancel=()=>{node.onpointermove=null;changed();};}
 node.onpointerdown=e=>pointer(e);if(selected===entity.id&&!choosing){const handle=el('span','scene-resize','↘');handle.setAttribute('aria-label','Drag to resize');handle.onpointerdown=e=>pointer(e,true);node.append(handle);}canvas.append(node);}
 d.objects.forEach(o=>drawEntity(o,'object'));d.hotspots.forEach(h=>drawEntity(h,'hotspot'));
 canvas.onpointerdown=e=>{if(!choosing||tool!=='hotspot'||!target||e.button!==0||d.hotspots.length>=L.scene.hotspots)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);const r=canvas.getBoundingClientRect(),point=p=>({x:Math.max(0,Math.min(1,(p.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(p.clientY-r.top)/r.height))}),start=point(e);const box=el('div','scene-hotspot drawing');canvas.append(box);let end=start;canvas.onpointermove=p=>{end=point(p);Object.assign(box.style,{left:Math.min(start.x,end.x)*100+'%',top:Math.min(start.y,end.y)*100+'%',width:Math.abs(end.x-start.x)*100+'%',height:Math.abs(end.y-start.y)*100+'%'});};canvas.onpointerup=p=>{end=point(p);canvas.onpointermove=null;const h={id:id(),x:Math.min(start.x,end.x),y:Math.min(start.y,end.y),width:Math.abs(end.x-start.x),height:Math.abs(end.y-start.y)};if(h.width>=.01&&h.height>=.01){d.hotspots.push(h);target.answers.push({id:id(),type:'hotspot',hotspotId:h.id});selected=h.id;selectedType='hotspot';changed();}else box.remove();};canvas.onpointercancel=()=>{canvas.onpointermove=null;box.remove();};};
 const palette=el('div','scene-element-picker');palette.hidden=!(choosing&&tool==='object');
 for(const asset of d.assets){const b=action('Place',()=>addInstance(asset),d.objects.length>=L.scene.instances);b.prepend(preview(asset.media,c.services,asset.name));b.setAttribute('aria-label','Place '+asset.name);palette.append(b);}layout.prepend(palette);
 const entity=(selectedType==='object'?d.objects:d.hotspots).find(o=>o.id===selected);if(entity&&!choosing){const controls=el('div','editor-row scene-object-tools');controls.append(el('strong','',selectedType==='object'?'Selected object':'Selected hotspot'));if(selectedType==='object')controls.append(action('Duplicate element',()=>{const copy=clampObject({...entity,id:id(),x:entity.x+.03,y:entity.y+.03});d.objects.push(copy);selected=copy.id;changed();},d.objects.length>=L.scene.instances));controls.append(action(selectedType==='object'?'Delete element':'Delete hotspot',()=>{const key=selectedType==='object'?'objects':'hotspots',ref=selectedType==='object'?'sceneObjectId':'hotspotId';d[key]=d[key].filter(o=>o.id!==entity.id);d.targets.forEach(t=>t.answers=t.answers.filter(a=>a[ref]!==entity.id));selected=null;changed();}));for(const key of ['x','y','width','height'])controls.append(input(key+' (%)',Math.round(entity[key]*100),value=>{const n=Number(value)/100;if(!Number.isFinite(n))return;entity[key]=n;if(selectedType==='object')clampObject(entity);else{entity.width=Math.max(.01,Math.min(1,entity.width));entity.height=Math.max(.01,Math.min(1,entity.height));entity.x=Math.max(0,Math.min(1-entity.width,entity.x));entity.y=Math.max(0,Math.min(1-entity.height,entity.y));}c.changed();},{type:'number'}));controls.append(action('Apply position / size',()=>c.draw()));c.space.append(controls);}
 const toolbar=el('div','scene-arrange-toolbar'),select=el('select'),label=el('label','','Select Prompt'),count=el('output');select.setAttribute('aria-label','Select Prompt');
 for(const t of d.targets)select.append(new Option(t.prompt,t.id));select.value=targetId||'';label.append(select);
 function refreshLinks(){count.textContent=target?target.answers.length+' targets · '+target.answers.filter(a=>a.type==='hotspot').length+' hotspots · '+target.answers.filter(a=>a.type==='object').length+' elements':'0 targets';for(const node of canvas.querySelectorAll('[data-entity-id]')){const type=node.classList.contains('scene-object')?'object':'hotspot';node.classList.toggle('answer',!!assigned(type,node.dataset.entityId));node.classList.toggle('available',type==='object'&&choosing&&tool==='object'&&!assigned(type,node.dataset.entityId));}}
 select.onchange=()=>{targetId=select.value;target=d.targets.find(t=>t.id===targetId);refreshLinks();};
 const elements=action('Select Elements',()=>{choosing=!(choosing&&tool==='object');tool='object';c.draw();}),hotspot=action('Add Hotspot',()=>{choosing=!(choosing&&tool==='hotspot');tool='hotspot';c.draw();},d.hotspots.length>=L.scene.hotspots);elements.setAttribute('aria-pressed',String(choosing&&tool==='object'));hotspot.setAttribute('aria-pressed',String(choosing&&tool==='hotspot'));
 toolbar.append(action('← Prepare Content',()=>{step=1;c.space.dataset.sceneStep='prepare';c.draw();}),label,count,elements,hotspot,action('Preview',()=>c.services.preview?.(c.read?c.read():structuredClone(d))),action('Done',()=>c.services.save?.()));
 const tools=c.space.querySelector('.scene-object-tools');left.append(toolbar,layout);if(tools)left.append(tools);workspace.classList.add('scene-arrange');workspace.append(left);c.space.append(workspace);refreshLinks();

 });
 const destroy=controller.destroy;controller.destroy=()=>{observer?.disconnect();destroy();};return controller;
}
